# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class B(BaseModel):
    value: int | None = None
