# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel

from tests.data.python.input_model.generic_reuse import Box, Item


class ModelRoot(BaseModel):
    box: Box[Item]
