# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class BoxInt(BaseModel):
    value: int = Field(..., title='Value')


class TypedRoot(BaseModel):
    box: BoxInt
