# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-12-27T06:59:56+00:00

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired

AllExportsCollisionStrategy: TypeAlias = Literal[
    'error', 'minimal-prefix', 'full-prefix'
]


AllExportsScope: TypeAlias = Literal['children', 'recursive']


ModuleSplitMode: TypeAlias = Literal['single']


class ParseConfig(TypedDict):
    with_import: NotRequired[bool | None]
    format_: NotRequired[bool | None]
    settings_path: NotRequired[str | None]
    disable_future_imports: NotRequired[bool]
    all_exports_scope: NotRequired[AllExportsScope | None]
    all_exports_collision_strategy: NotRequired[AllExportsCollisionStrategy | None]
    module_split_mode: NotRequired[ModuleSplitMode | None]
