# generated by datamodel-codegen:
#   filename:  modular.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, NotRequired, Optional, TypedDict


class Thing(TypedDict):
    attributes: NotRequired[Optional[Dict[str, Any]]]


class Thang(TypedDict):
    attributes: NotRequired[Optional[List[Dict[str, Any]]]]


class Others(TypedDict):
    name: NotRequired[Optional[str]]


class Clone(Thing):
    others: NotRequired[Optional[Others]]
