# generated by datamodel-codegen:
#   filename:  _internal
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Parent(BaseModel):
    id: Optional[str] = None
    child: Optional[Child] = None


class Child(BaseModel):
    id: Optional[str] = None
    parent: Optional[Parent] = None


Parent.update_forward_refs()
