# generated by datamodel-codegen:
#   filename:  definitions/machine/robot.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from ... import person
from .. import food, pet
from ..drink import coffee


class Robot(pet.Pet):
    friends: Optional[person.Person] = None
    drink: Optional[coffee.Coffee] = None
    food: Optional[food.Noodle] = None
