# generated by datamodel-codegen:
#   filename:  schema_0.json

from __future__ import annotations

from pydantic import BaseModel

from .outer import Outer


class Root0(BaseModel):
    data0: Outer | None = None
    next: Root0 | None = None


Root0.model_rebuild()
