# generated by datamodel-codegen:
#   filename:  alias.yaml
#   timestamp: 2025-03-26T15:01:47+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional

from . import model_s


class Pet(Enum):
    ca_t = 'ca-t'
    dog_ = 'dog*'


@dataclass(frozen=True, slots=True, keyword_only=True)
class Error:
    code: int
    message: str


@dataclass(frozen=True, slots=True, keyword_only=True)
class HomeAddress:
    address_1: Optional[str] = None


TeamMembers = List[str]


@dataclass(frozen=True, slots=True, keyword_only=True)
class AllOfObj:
    name: Optional[str] = None
    number: Optional[str] = None


Id = str


@dataclass(frozen=True, slots=True, keyword_only=True)
class Result:
    event: Optional[model_s.EvenT] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class Source:
    country_name: Optional[str] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class UserName:
    first_name: Optional[str] = None
    home_address: Optional[HomeAddress] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class AllOfRef(UserName, HomeAddress):
    pass


@dataclass(frozen=True, slots=True, keyword_only=True)
class AllOfCombine(UserName):
    birth_date: Optional[str] = None
    size: Optional[int] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class AnyOfCombine(HomeAddress, UserName):
    age: Optional[str] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class Item(HomeAddress, UserName):
    age: Optional[str] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class AnyOfCombineInObject:
    item: Optional[Item] = None


@dataclass(frozen=True, slots=True, keyword_only=True)
class AnyOfCombineInArrayItem(HomeAddress, UserName):
    age: Optional[str] = None


AnyOfCombineInArray = List[AnyOfCombineInArrayItem]


@dataclass(frozen=True, slots=True, keyword_only=True)
class AnyOfCombineInRoot(HomeAddress, UserName):
    age: Optional[str] = None
    birth_date: Optional[str] = None
