# generated by datamodel-codegen:
#   filename:  simple_frozen_test.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from dataclasses import dataclass

from my_module import my_decorator


@my_decorator
@dataclass
class User:
    name: str
    age: int
    email: str | None = None
