# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from datetime import datetime
from typing import TypedDict

from typing_extensions import NotRequired


class Model(TypedDict):
    created_at: NotRequired[datetime]
