# generated by datamodel-codegen:
#   filename:  generation_context_model.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    # template_version = updated
    # nested_item_count = 1
    value: str | None = None
