"""Module docstring."""
from __future__ import annotations

import sys
#
# generated by datamodel-codegen:
#   filename:  simple_string.json

"""Formatter docstring."""
from pydantic import BaseModel


class Model(BaseModel):
    s: str