# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Any

from my_project.model_base import BaseModel as _BaseModel
from pydantic import ConfigDict, Field, conint


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Person(BaseModel):
    firstName: str | None = Field(None, description="The person's first name.")
    lastName: str | None = Field(None, description="The person's last name.")
    age: conint(ge=0) | None = Field(
        None, description='Age in years which must be equal to or greater than zero.'
    )
    friends: list[Any] | None = None
    comment: None = Field(None)
