# generated by datamodel-codegen:
#   filename:  reuse_type_overrides.json

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel


class A(BaseModel):
    value: str | None = None


class B(BaseModel):
    value: date | None = None


class C(BaseModel):
    code: int | None = None


class E(BaseModel):
    flag: bool | None = None


class Model(BaseModel):
    a: A | None = None
    b: B | None = None
    c: C | None = None
    d: datetime | None = None
    e: E | None = None
    f: E | None = None
