# generated by datamodel-codegen:
#   filename:  type_overrides_scoped.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Any

from my_app import Address
from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any


class Address1(BaseModel):
    __root__: str


class User(BaseModel):
    name: str | None = None
    address: Address | None = None
