# generated by datamodel-codegen:
#   filename:  string_enum.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import StrEnum


class Model(StrEnum):
    A = 'A'
    B = 'B'
