# generated by datamodel-codegen:
#   filename:  schema.json

# formatter_revision = "refactored"
from __future__ import annotations

from pydantic import BaseModel


class WatchedPerson(BaseModel):
    name: str
