# generated by datamodel-codegen:
#   filename:  root.json

from __future__ import annotations

from pydantic import BaseModel


class Child(BaseModel):
    name: str | None = None
    age: int | None = None


class WatchedRoot(BaseModel):
    child: Child | None = None
