# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class Child(BaseModel):
    name: str


class Model(RootModel[Child]):
    root: Child
