# generated by datamodel-codegen:
#   filename:  missing.json

from __future__ import annotations

from pydantic import BaseModel


class WatchedChild(BaseModel):
    name: str | None = None
    age: int | None = None
