# generated by datamodel-codegen:
#   filename:  union.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel

from . import bar, foo


class ExecutionContext(RootModel[foo.JobRun | bar.JobRun]):
    root: foo.JobRun | bar.JobRun = Field(..., description='Execution Configuration.')


class App(BaseModel):
    runtime: ExecutionContext | None = Field(
        None, description='Execution Configuration.'
    )
