# generated by datamodel-codegen:
#   filename:  namespace_subns_ref.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import subns


class Wrapper(BaseModel):
    item: subns.Item | None = None
