# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, RootModel

from tests.data.python.input_model.collision_a import Data as Data6
from tests.data.python.input_model.collision_a import Kind as Kind6
from tests.data.python.input_model.collision_a import Mode as Mode4
from tests.data.python.input_model.collision_b import Data as Data1
from tests.data.python.input_model.collision_b import Data_2
from tests.data.python.input_model.collision_b import Kind as Kind1
from tests.data.python.input_model.collision_b import Mode as Mode1
from tests.data.python.input_model.collision_c import Data, Kind, Mode
from tests.data.python.input_model.collision_reserved import Data_4, Kind_2, Kind_4


class PlainC(BaseModel):
    data: Data
    kind: Kind | None = None
    mode: Mode | None = None
    reserved_data2: Data_2 | None = None
    reserved_data4: Data_4 | None = None
    reserved_kind2: Kind_2 | None = None
    reserved_kind4: Kind_4 | None = None


class PlainB(BaseModel):
    data: Data1
    kind: Kind1 | None = None
    mode: Mode1 | None = None


class PlainA(BaseModel):
    data: Data6
    kind: Kind6 | None = None
    mode: Mode4 | None = None


class Model(RootModel[PlainC | PlainB | PlainA]):
    root: PlainC | PlainB | PlainA
