# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class Spare(RootModel[int]):
    root: int


class ExtraDefinitions(BaseModel):
    first: int = Field(..., title='First')


class EmptyDefinitions(BaseModel):
    second: str = Field(..., title='Second')


class Model(RootModel[ExtraDefinitions | EmptyDefinitions]):
    root: ExtraDefinitions | EmptyDefinitions
