# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Data(BaseModel):
    id: int = Field(..., title='Id')
    child: Data | None = None


class Kind(Enum):
    a = 'a'
    other_a = 'other-a'


class Mode(Enum):
    mode_a = 'mode-a'
    mode_other_a = 'mode-other-a'


class PlainA(BaseModel):
    data: Data
    kind: Kind | None = None
    mode: Mode | None = None


class Data2(BaseModel):
    name: str = Field(..., title='Name')
    child: Data2 | None = None


class Kind2(Enum):
    b = 'b'
    other_b = 'other-b'


class Mode2(Enum):
    mode_b = 'mode-b'
    mode_other_b = 'mode-other-b'


class PlainB(BaseModel):
    data: Data2
    kind: Kind2 | None = None
    mode: Mode2 | None = None


class Model(RootModel[PlainA | PlainB]):
    root: PlainA | PlainB


Data.model_rebuild()
Data2.model_rebuild()
