# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class Scalar(BaseModel):
    value: int = Field(..., title='Value')


class ScalarRoot(BaseModel):
    child: Scalar
