# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class Raising(BaseModel):
    value: int = Field(..., title='Value')


class RaisingRoot(BaseModel):
    child: Raising
