# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, RootModel

from tests.data.python.input_model.same_schema_a import Alias, Node
from tests.data.python.input_model.same_schema_b import Alias as Alias1


class AliasRoot(BaseModel):
    left: Alias
    right: Alias1


class Shared(BaseModel):
    left: Node
    right: Node


class Model(RootModel[AliasRoot | Shared]):
    root: AliasRoot | Shared
