# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, RootModel

from tests.data.python.input_model.same_schema_a import Node as Node1
from tests.data.python.input_model.same_schema_b import Node


class Reversed(BaseModel):
    right: Node
    left: Node1


class Shared(BaseModel):
    left: Node1
    right: Node1


class Model(RootModel[Reversed | Shared]):
    root: Reversed | Shared
