# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TypedDict


class Tag(TypedDict):
    values: frozenset[str]


class ModelWithPythonTypes(TypedDict):
    tags: set[str]
    frozen_tags: frozenset[int]
    metadata: Mapping[str, int]
    items: Sequence[str]
    nested_mapping: Mapping[str, list[int]]
    tag_obj: Tag
    nested_in_list: list[list[int]]
    optional_set: set[str] | None
    nullable_frozenset: frozenset[str] | None
    optional_mapping: Mapping[str, str] | None
