# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from collections.abc import Mapping, Sequence

from pydantic import BaseModel, Field


class Tag(BaseModel):
    values: frozenset[str] = Field(..., title='Values', unique_items=True)


class ModelWithPythonTypes(BaseModel):
    tags: set[str] = Field(..., title='Tags', unique_items=True)
    frozen_tags: frozenset[int] = Field(..., title='Frozen Tags', unique_items=True)
    metadata: Mapping[str, int] = Field(..., title='Metadata')
    items: Sequence[str] = Field(..., title='Items')
    nested_mapping: Mapping[str, list[int]] = Field(..., title='Nested Mapping')
    tag_obj: Tag
    nested_in_list: list[list[int]] = Field(..., title='Nested In List')
    optional_set: set[str] | None = Field(..., title='Optional Set')
    nullable_frozenset: frozenset[str] | None = Field(..., title='Nullable Frozenset')
    optional_mapping: Mapping[str, str] | None = Field(..., title='Optional Mapping')
