# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias


@dataclass
class GrandParent:
    grand_field: str


@dataclass
class Parent(GrandParent):
    parent_field: int


@dataclass
class ChildA(Parent):
    child_a_field: float


@dataclass
class ChildB(Parent):
    child_b_field: bool


Model: TypeAlias = ChildA | ChildB
