# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class GrandParent(BaseModel):
    grand_field: str = Field(..., title='Grand Field')


class Parent(GrandParent):
    parent_field: int = Field(..., title='Parent Field')


class ChildA(Parent):
    child_a_field: float = Field(..., title='Child A Field')


class TempModel(BaseModel):
    value: str = Field(..., title='Value')


class Model(RootModel[ChildA | TempModel]):
    root: ChildA | TempModel
