# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Inner(BaseModel):
    label: str = Field(..., title='Label')


class OtherRoot(BaseModel):
    child: Inner


class Inner2(BaseModel):
    inherited: int | None = Field(1, title='Inherited')
    value: int = Field(..., title='Value')


class Kind(Enum):
    first = 'first'
    second = 'second'


class Leaf(BaseModel):
    label: str = Field(..., title='Label')


class Node(BaseModel):
    value: int = Field(..., title='Value')
    child: Node | None = None


class Record(BaseModel):
    number: int = Field(..., title='Number')


class NestedRoot(BaseModel):
    child: Inner2
    leaf: Leaf
    kind: Kind
    record: Record
    node: Node
    tests: str | None = Field(None, title='Tests')


class Model(RootModel[OtherRoot | NestedRoot]):
    root: OtherRoot | NestedRoot


Node.model_rebuild()
