# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import TypedDict


class NoInheritance(TypedDict):
    simple_field: str
