# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import TypedDict

from tests.data.python.input_model.nested_models import Status
from typing_extensions import NotRequired


class Address(TypedDict):
    street: str
    city: str


class Metadata(TypedDict):
    key: str
    value: str


class User(TypedDict):
    name: str
    status: Status
    metadata: NotRequired[Metadata | None]
    address: NotRequired[Address | None]
