# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from dataclasses import dataclass

from tests.data.python.input_model.typeddict_nested import Profile, Role


@dataclass
class Member:
    name: str
    role: Role
    profile: Profile | None
