# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations
from pydantic import Field, RootModel


class Lookup(RootModel[dict[str, str]]):
    root: dict[str, str] = Field(..., title='Lookup')
