# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from collections.abc import Callable

from pydantic import BaseModel, Field


class Serialization(BaseModel):
    first: int = Field(..., title='First')
    values: frozenset[int] = Field(..., title='Values')
    callback: Callable[[int], int] = Field(..., title='Callback')
    last: str = Field(..., title='Last')
