# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class ListWins(BaseModel):
    first: int = Field(..., title='First')
    shared: list[int] = Field(..., title='Shared')
    last: str = Field(..., title='Last')
