# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class Item(BaseModel):
    wire: list[int] = Field(..., title='Wire')


class InlineDuplicate(BaseModel):
    item: Item = Field(..., title='Item')


class Plain(BaseModel):
    first: int = Field(..., title='First')
    second: int = Field(..., title='Second')
    third: int = Field(..., title='Third')


class Model(RootModel[InlineDuplicate | Plain]):
    root: InlineDuplicate | Plain
