# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class Serialization(BaseModel):
    first: int = Field(..., title='First')
    values: frozenset[int] = Field(..., title='Values')
    items: list[int] = Field(..., title='Items')
    last: str = Field(..., title='Last')
