# generated by datamodel-codegen:
#   filename:  body_and_parameters_remote_ref.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class Pet(BaseModel):
    id: int
    name: str
    tag: str | None = None


class Error(BaseModel):
    code: int
    message: str


class PetForm(BaseModel):
    name: str | None = None
    age: int | None = None


class PetsGetResponse(RootModel[list[Pet]]):
    root: list[Pet]


class FoodFoodIdGetResponse(RootModel[list[int]]):
    root: list[int]
