# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class AliasParent(BaseModel):
    old: int = Field(1, title='Old')


class AliasRequiredChild(AliasParent):
    old: int = Field(..., alias='new', title='New')
