# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class DefaultParent(BaseModel):
    before: int = Field(10, title='Before')
    value: int = Field(1, title='Value')
    after: int = Field(30, title='After')


class MultipleChild(DefaultParent):
    other: str = Field('other', title='Other')
    value: int = Field(4, title='Value')
