# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field


class RequiredParent(BaseModel):
    value: int = Field(..., title='Value')


class OptionalChild(RequiredParent):
    value: int = Field(2, title='Value')
