# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class StrictParent(BaseModel):
    value: conint(ge=5) = Field(..., title='Value')


class RelaxedChild(StrictParent):
    value: conint(ge=0) = Field(..., title='Value')
