# generated by datamodel-codegen:
#   filename:  msgspec_unset_fastpath.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, constr


class Status(Enum):
    ready = 'ready'
    waiting = 'waiting'


class Nested(BaseModel):
    id: int


class UnsetFastPath(BaseModel):
    required_value: str
    plain: str | None = None
    items: list[str] | None = None
    mapping: dict[str, int] | None = None
    constrained: constr(min_length=1) | None = None
    nullable: str | None = None
    combined: str | int | None = None
    nested: Nested | None = None
    status: Status | None = None
