# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field, StrictStr


class Pet(BaseModel):
    id: int
    name: StrictStr
    tag: StrictStr | None = None


class Pets(BaseModel):
    __root__: list[Pet]


class User(BaseModel):
    id: int
    name: StrictStr
    tag: StrictStr | None = None


class Users(BaseModel):
    __root__: list[User]


class Id(BaseModel):
    __root__: StrictStr


class Rules(BaseModel):
    __root__: list[StrictStr]


class Error(BaseModel):
    code: int
    message: StrictStr


class Api(BaseModel):
    apiKey: StrictStr | None = Field(
        None, description='To be used as a dataset parameter value'
    )
    apiVersionNumber: StrictStr | None = Field(
        None, description='To be used as a version parameter value'
    )
    apiUrl: AnyUrl | None = Field(
        None, description="The URL describing the dataset's fields"
    )
    apiDocumentationUrl: AnyUrl | None = Field(
        None, description='A URL to the API console for each API'
    )


class Apis(BaseModel):
    __root__: list[Api]


class Event(BaseModel):
    name: StrictStr | None = None


class Result(BaseModel):
    event: Event | None = None
