# generated by datamodel-codegen:
#   filename:  no_alias.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Person(BaseModel):
    first_name: str = Field(..., serialization_alias='first-name')
    last_name: str = Field(..., serialization_alias='last-name')
    email_address: str | None = None
