# generated by datamodel-codegen:
#   filename:  integer.xsd

from __future__ import annotations

from pydantic import BaseModel, Field


class Base(BaseModel):
    value: int = Field(..., ge=-2147483648, le=2147483647)
    id: int = Field(..., ge=-2147483648, le=2147483647)


class Derived(BaseModel):
    value: int = Field(..., ge=-2147483648, le=2147483647)
    id: int = Field(..., ge=-2147483648, le=2147483647)
    label: str


class Root(Derived):
    pass
