# generated by datamodel-codegen:
#   filename:  normal_builtin.xsd

from __future__ import annotations

from pydantic import BaseModel


class Derived(BaseModel):
    value: str
    label: str | None = 'kept'


class Root(Derived):
    pass
