# generated by datamodel-codegen:
#   filename:  redefined.xsd

from __future__ import annotations

from pydantic import BaseModel, Field


class Base(BaseModel):
    value: str
    id: int = Field(..., ge=-2147483648, le=2147483647)
    label: str


class Root(Base):
    pass
