# generated by datamodel-codegen:
#   filename:  restriction_inline.xsd

from __future__ import annotations

from pydantic import BaseModel, Field


class Base(BaseModel):
    value: str
    id: int = Field(..., ge=-2147483648, le=2147483647)


class Derived(BaseModel):
    value: str = Field(..., max_length=4, min_length=2)
    id: int = Field(..., ge=-2147483648, le=2147483647)


class Root(Derived):
    pass
