# generated by datamodel-codegen:
#   filename:  api_ordered_required_fields.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct, field
from typing_extensions import Annotated


class Pet(Struct):
    id: int
    name: str
    z_last: str = field(name='zLast')
    tag: Optional[str] = None


Pets = List[Pet]


class User(Struct):
    id: int
    name: str
    tag: Optional[str] = None


Users = List[User]


Id = str


Rules = List[str]


class Error(Struct):
    code: int
    message: str


class Api(Struct):
    api_key: Optional[
        Annotated[str, Meta(description='To be used as a dataset parameter value')]
    ] = None
    api_version_number: Optional[
        Annotated[str, Meta(description='To be used as a version parameter value')]
    ] = None
    api_url: Optional[
        Annotated[str, Meta(description="The URL describing the dataset's fields")]
    ] = None
    api_documentation_url: Optional[
        Annotated[str, Meta(description='A URL to the API console for each API')]
    ] = None


Apis = List[Api]


class Event(Struct):
    name: Optional[str] = None


class Result(Struct):
    event: Optional[Event] = None
