# generated by datamodel-codegen:
#   filename:  enum_pattern.json

from __future__ import annotations

from enum import Enum

from pydantic import Field, RootModel


class Root(Enum):
    aa = 'aa'
    bb = 'bb'


class Base(RootModel[str]):
    root: str = Field(..., pattern='^a')
