# generated by datamodel-codegen:
#   filename:  enum_pattern.json

from __future__ import annotations

from enum import Enum

from pydantic import RootModel, constr


class Root(Enum):
    aa = 'aa'
    bb = 'bb'


class Base(RootModel[constr(pattern=r'^a')]):
    root: constr(pattern=r'^a')
