# generated by datamodel-codegen:
#   filename:  enum_objects.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, RootModel


class Root(Enum):
    array___ = []
    array____a___1___b___2__ = [{'a': 1, 'b': 2}]


class BaseItem(BaseModel):
    a: int
    b: int


class Base(RootModel[list[BaseItem]]):
    root: list[BaseItem]
