# generated by datamodel-codegen:
#   filename:  items_true.json

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class RootItem(RootModel[int]):
    root: int = Field(..., ge=2)


class Root(RootModel[list[RootItem]]):
    root: list[RootItem] = Field(..., title='Root')


class Base(RootModel[list[Any]]):
    root: list[Any]
