# generated by datamodel-codegen:
#   filename:  items_number.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[list[int | None]]):
    root: list[int | None] = Field(..., title='Root')


class Base(RootModel[list[float | None]]):
    root: list[float | None]
