# generated by datamodel-codegen:
#   filename:  items_sibling.json

from __future__ import annotations

from pydantic import Field, RootModel


class RootItem(RootModel[int]):
    root: int = Field(..., ge=2, le=3)


class Root(RootModel[list[RootItem]]):
    root: list[RootItem] = Field(..., title='Root')


class BaseItem(RootModel[int]):
    root: int = Field(..., ge=2)


class Base(RootModel[list[BaseItem]]):
    root: list[BaseItem]
