# generated by datamodel-codegen:
#   filename:  string_draft-07.json

from __future__ import annotations

from pydantic import Field, RootModel, constr


class Token(RootModel[constr(min_length=2, max_length=5)]):
    root: constr(min_length=2, max_length=5)


class Root(RootModel[Token]):
    root: Token = Field(..., title='Root')
