# generated by datamodel-codegen:
#   filename:  collision.json

from builtins import list as list_aliased_2
from dataclasses import dataclass
from typing import Literal


@dataclass
class Child:
    value: int | None = None


@dataclass
class Record:
    list: str | None = None
    list_aliased: str | None = None
    list_aliased_1: str | None = None
    items: list_aliased_2[int] | None = None
    Field: str | None = None
    count: int | None = None
    Optional: str | None = None
    choice: Literal['list', 'Optional', 'Field'] | None = None
    child: Child | None = None
