# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel

import tests.data.python.input_model.generic_reuse_future


class NestedRoot(BaseModel):
    box: tests.data.python.input_model.generic_reuse_future.NestedOwner.NestedRoot.model_fields['box'].annotation
