# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, conint

from tests.data.python.input_model.generic_reuse import Box, Item
from tests.data.python.input_model.generic_reuse_future import FutureMixedRoot


class DefaultBoxAnnotatedIntFieldInfoAnnotationNoneTypeRequiredTrueMetadataGtGt3(BaseModel):
    value: conint(gt=3) | None = Field(4, title='Value')
    label: str | None = Field('kept', title='Label')


class PairAnnotatedIntFieldInfoAnnotationNoneTypeRequiredTrueMetadataGtGt3Item(BaseModel):
    first: conint(gt=3) = Field(..., title='First')
    second: Item


class MixedFutureRoot(BaseModel):
    mixed: FutureMixedRoot


class RepeatedRoot(BaseModel):
    first: Box[int]
    second: Box[int]
    strings: Box[str]
    items: list[Box[int]] = Field(..., title='Items')


class Model(RootModel[MixedFutureRoot | RepeatedRoot]):
    root: MixedFutureRoot | RepeatedRoot
