version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "10:30"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  groups:
    github-actions:
      patterns:
      - "*"
