# generated by datamodel-codegen:
#   filename:  wire_collision_missing.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class Cat(BaseModel):
    other: Literal['ordinary'] | None = Field(None, alias='kind')
    meow: str | None = None
    kind: Literal['cat'] = Field(..., alias='petType')


class Dog(BaseModel):
    other: Literal['ordinary'] | None = Field(None, alias='kind')
    bark: str | None = None
    kind: Literal['dog'] = Field(..., alias='petType')


class Pet(RootModel[Cat | Dog]):
    root: Cat | Dog = Field(..., discriminator='kind')


class Unrelated(BaseModel):
    kind: str | None = Field(None, alias='petType')
