# generated by datamodel-codegen:
#   filename:  wire_collision_enum.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, RootModel


class Other(Enum):
    ordinary = 'ordinary'


class Kind(Enum):
    cat = 'cat'


class Cat(BaseModel):
    other: Other | None = Field(None, alias='kind')
    kind: Literal['cat'] = Field(..., alias='petType')
    meow: str | None = None


class Kind1(Enum):
    dog = 'dog'


class Dog(BaseModel):
    other: Other | None = Field(None, alias='kind')
    kind: Literal['dog'] = Field(..., alias='petType')
    bark: str | None = None


class Pet(RootModel[Cat | Dog]):
    root: Cat | Dog = Field(..., discriminator='kind')


class Unrelated(BaseModel):
    kind: str | None = Field(None, alias='petType')
