# generated by datamodel-codegen:
#   filename:  exact_imports_ancestor_package.yaml

from __future__ import annotations

from pydantic import BaseModel


class Tag(BaseModel):
    label: str | None = None
