# generated by datamodel-codegen:
#   filename:  _internal
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import models


class CustomOptional(BaseModel):
    __root__: str


class CustomId(BaseModel):
    __root__: str


class CustomError(BaseModel):
    code: int
    message: str


class CustomResult(BaseModel):
    event: models.CustomEvent | None = None


class CustomSource(BaseModel):
    country: str | None = None


class CustomDifferentTea(BaseModel):
    foo: CustomTea | None = None
    nested: CustomTea_1 | None = None


class CustomTea(BaseModel):
    flavour: str | None = None
    id: CustomId | None = None


class CustomCocoa(BaseModel):
    quality: int | None = None


class CustomTea_1(BaseModel):
    flavour: str | None = None
    id: CustomId | None = None
    self: CustomTea_1 | None = None
    optional: list[CustomOptional] | None = None


class CustomTeaClone(BaseModel):
    flavour: str | None = None
    id: CustomId | None = None
    self: CustomTea_1 | None = None
    optional: list[CustomOptional] | None = None


class CustomList(BaseModel):
    __root__: list[CustomTea_1]


CustomTea_1.update_forward_refs()
