# generated by datamodel-codegen:
#   filename:  default_object.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypeAlias

from msgspec import Struct, UnsetType, convert, field

from . import Foo as Foo_1
from . import Nested

Foo: TypeAlias = str


class Bar(Struct):
    original_foo: Foo_1 | UnsetType = field(
        default_factory=lambda: convert({'text': 'abc', 'number': 123}, type=Foo_1)
    )
    nested_foo: list[Nested.Foo] | UnsetType = field(
        default_factory=lambda: convert(['abc', 'efg'], type=list[Nested.Foo])
    )
