# generated by datamodel-codegen:
#   filename:  schema_base_open.json

from __future__ import annotations

from pydantic import ConfigDict

from tests.data.python.pattern_intersection_base import AttributeBase


class Root(AttributeBase):
    model_config = ConfigDict(
        extra='allow',
    )
    known: int | None = 4
