name: 'datamodel-code-generator'
description: 'Generate Python data models from schema definitions (OpenAPI, JSON Schema, GraphQL, and more)'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  input:
    description: 'Input schema file or directory'
    required: false
    default: ''
  output:
    description: 'Output file or directory'
    required: false
    default: ''
  input-file-type:
    description: 'Input file type (openapi, jsonschema, json, yaml, csv, graphql)'
    required: false
    default: ''
  output-model-type:
    description: 'Output model type (pydantic_v2.BaseModel, pydantic.BaseModel, dataclasses.dataclass, typing.TypedDict, msgspec.Struct)'
    required: false
    default: ''
  check:
    description: 'Validate that existing output is up to date (no generation)'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory (where pyproject.toml is located)'
    required: false
    default: '.'
  profile:
    description: 'Named profile from pyproject.toml [tool.datamodel-codegen.profiles.<name>]'
    required: false
    default: ''
  extra-args:
    description: 'Additional CLI arguments'
    required: false
    default: ''
  version:
    description: 'Specific version to install (defaults to action tag version if tag looks like a version, otherwise latest)'
    required: false
    default: ''
  extras:
    description: 'Optional extras to install (comma-separated: graphql, http, validation, ruff, all)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: datamodel-codegen-${{ runner.os }}

    - run: |
        EXTRAS=""
        if [ -n "${{ inputs.extras }}" ]; then
          EXTRAS="[${{ inputs.extras }}]"
        fi

        if [ -n "${{ inputs.version }}" ]; then
          pip install "datamodel-code-generator${EXTRAS}==${{ inputs.version }}"
        elif [[ "${{ github.action_ref }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          pip install "datamodel-code-generator${EXTRAS}==${{ github.action_ref }}"
        else
          pip install "datamodel-code-generator${EXTRAS}"
        fi
      shell: bash

    - run: |
        ARGS=()

        if [ -n "${{ inputs.input }}" ]; then
          ARGS+=(--input "${{ inputs.input }}")
        fi

        if [ -n "${{ inputs.output }}" ]; then
          ARGS+=(--output "${{ inputs.output }}")
        fi

        if [ -n "${{ inputs.input-file-type }}" ]; then
          ARGS+=(--input-file-type "${{ inputs.input-file-type }}")
        fi

        if [ -n "${{ inputs.output-model-type }}" ]; then
          ARGS+=(--output-model-type "${{ inputs.output-model-type }}")
        fi

        if [ "${{ inputs.check }}" = "true" ]; then
          ARGS+=(--check)
        fi

        if [ -n "${{ inputs.profile }}" ]; then
          ARGS+=(--profile "${{ inputs.profile }}")
        fi

        datamodel-codegen "${ARGS[@]}" ${{ inputs.extra-args }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
