# generated by datamodel-codegen:
#   filename:  empty_namespace_reuse.xsd

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, conint


class Code(RootModel[conint(ge=-2147483648, le=2147483647)]):
    root: conint(ge=-2147483648, le=2147483647) = Field(..., title='Code')


class Root(BaseModel):
    code: Code


class Model(BaseModel):
    code: conint(ge=-2147483648, le=2147483647) = Field(..., title='Code')
    root: Root = Field(..., title='Root')
