# generated by datamodel-codegen:
#   filename:  group_reuse.xsd

from __future__ import annotations

from pydantic import BaseModel, conint


class Root(BaseModel):
    code: conint(ge=-2147483648, le=2147483647)
