# generated by datamodel-codegen:
#   filename:  inherited_override.xsd

from __future__ import annotations

from pydantic import BaseModel


class Base(BaseModel):
    code: str | None = None


class Child(BaseModel):
    code: str


class Root(Child):
    pass
