# generated by datamodel-codegen:
#   filename:  ordinary.xsd

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class Root(Struct):
    item: Annotated[int, Meta(ge=-2147483648, le=2147483647)]
    code: str
