# generated by datamodel-codegen:
#   filename:  boolean_schema_openapi.yaml

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class Anything(RootModel[Any]):
    root: Any


class User(BaseModel):
    name: str | None = None
