# generated by datamodel-codegen:
#   filename:  boolean_integer_alias.json

from __future__ import annotations

from enum import Enum

from msgspec import UNSET, Struct, UnsetType


class Value(Enum):
    int_1 = 1
    bool_True = True


class Payload(Struct):
    value: Value | UnsetType = UNSET
