# generated by datamodel-codegen:
#   filename:  other_backends.json

from __future__ import annotations

from typing import Literal, TypedDict

from typing_extensions import NotRequired


class Payload(TypedDict):
    enabled: NotRequired[Literal[True, False]]
    always: NotRequired[Literal[True]]
    never: NotRequired[Literal[False]]
    amount: NotRequired[float]
