# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, RootModel

from datamodel_code_generator.enums import DataModelType
from tests.data.dynamic_models.root_model_alias_imports import ImportedIntegerRoot, ImportedObject

from . import a_text
from . import color as color_1
from . import items as items_1
from . import maybe_number, plain_object, twin_number, z_number


class AliasModels(BaseModel):
    number: z_number.ZNumber
    text: a_text.AText
    twin: twin_number.TwinNumber
    items: items_1.Items
    maybe: maybe_number.MaybeNumber
    color: color_1.Color
    plain: plain_object.PlainObject