# generated by datamodel-codegen:
#   filename:  ordinary.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[list[str]]):
    root: list[str] = Field(..., title='Root')
