# generated by datamodel-codegen:
#   filename:  datatypes_and_mixed_content.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from datetime import timedelta
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel


class DatatypeSample(BaseModel):
    notation: str | None = None
    timestamp: AwareDatetime
    yearMonth: str | None = None
    dayTime: timedelta | None = None
    atomic: Any | None = None


class ParagraphBase(BaseModel):
    emphasis: list[str] | None = None


class MixedExtension(ParagraphBase):
    link: AnyUrl | None = None
    value: str | None = None


class Sample(BaseModel):
    content: MixedExtension
    datatypes: DatatypeSample
