# generated by datamodel-codegen:
#   filename:  datetime_classes.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class Root(BaseModel):
    dateTime: AwareDatetime | None = None
    dateTimeStamp: AwareDatetime | None = None
