# generated by datamodel-codegen:
#   filename:  import_namespace.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class ImportedCode(RootModel[constr(min_length=5, max_length=5)]):
    root: constr(min_length=5, max_length=5) = Field(..., title='ImportedCode')


class Code(RootModel[ImportedCode]):
    root: ImportedCode = Field(..., title='Code')
