# generated by datamodel-codegen:
#   filename:  model_groups_and_wildcards.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class SearchToken(RootModel[str | conint(ge=-2147483648, le=2147483647)]):
    root: str | conint(ge=-2147483648, le=2147483647) = Field(..., title='SearchToken')


class EventLog(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: list[str | None] | None = None
    count: list[Literal[1]] | None = None
    segment: list[str] = Field(..., max_length=12, min_length=4)
    tag: list[str] | None = Field(None, max_length=6, min_length=1)
    status: str | None = 'open'
    kind: Literal['audit']
    search: SearchToken | None = None
    inlineSearch: str | conint(ge=-2147483648, le=2147483647) | None = None
