# generated by datamodel-codegen:
#   filename:  pattern_alternatives.xsd

from __future__ import annotations

from re import compile

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Branches(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ..., pattern=compile('(?=\\A)(?:ab|cd|xy|[0-9]{2})\\Z'), title='Branches'
    )


class Deeper(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ...,
        pattern=compile(
            '(?=\\A(?:(?=\\A(?:(?=\\A)(?:[A-Z]+|[0-9]+)\\Z)\\Z)(?:(?=\\A)(?:[A-M]+|[3-7]+)\\Z)\\Z)\\Z)(?:(?=\\A)(?:[A-C]+|[4-5]+)\\Z)\\Z'
        ),
        title='Deeper',
    )


class Derived(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ...,
        pattern=compile(
            '(?=\\A(?:(?=\\A)(?:[A-Z]+|[0-9]+)\\Z)\\Z)(?:(?=\\A)(?:[A-M]+|[3-7]+)\\Z)\\Z'
        ),
        title='Derived',
    )


class Empty(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern=compile('(?=\\A)(?:|Q)\\Z'), title='Empty')


class Escaped(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ..., pattern=compile('(?=\\A)(?:a\\+b|x\\.y)\\Z'), title='Escaped'
    )


class Newline(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern=compile('(?=\\A)(?:A\nB|C)\\Z'), title='Newline')


class Reversed(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ..., pattern=compile('(?=\\A)(?:[0-9]+|[A-Z]+)\\Z'), title='Reversed'
    )


class SingleBase(RootModel[str]):
    root: str = Field(..., pattern='[A-Z]{2}|[0-9]{3}', title='SingleBase')


class SingleDerived(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ...,
        pattern=compile('(?=\\A(?:[A-Z]{2}|[0-9]{3})\\Z)(?:[A-Z]+)\\Z'),
        title='SingleDerived',
    )


class Token(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(
        ..., pattern=compile('(?=\\A)(?:[A-Z]+|[0-9]+)\\Z'), title='Token'
    )


class Root(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    token: Token
    reversed: Reversed
    branches: Branches
    derived: Derived
    deeper: Deeper
    single_derivation: SingleDerived
    empty: Empty
    escaped: Escaped
    newline: Newline
    inline: str = Field(
        ..., pattern=compile('(?=\\A(?:[ab]+)\\Z)(?:(?=\\A)(?:a+|b+)\\Z)\\Z')
    )
