# generated by datamodel-codegen:
#   filename:  pattern_controls.xsd

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType

Duplicate = TypeAliasType(
    "Duplicate", Annotated[str, Field(..., pattern='[A-Z]+', title='Duplicate')]
)


EmptySingle = TypeAliasType(
    "EmptySingle", Annotated[str, Field(..., pattern='', title='EmptySingle')]
)


SameDerived = TypeAliasType(
    "SameDerived",
    Annotated[
        str,
        Field(..., max_length=4, min_length=1, pattern='[A-Z]+', title='SameDerived'),
    ],
)


Single = TypeAliasType(
    "Single",
    Annotated[
        str, Field(..., max_length=4, min_length=1, pattern='[A-Z]+', title='Single')
    ],
)


Unsupported = TypeAliasType(
    "Unsupported", Annotated[str, Field(..., pattern='[A-Z]+', title='Unsupported')]
)


UnsupportedDerived = TypeAliasType(
    "UnsupportedDerived",
    Annotated[
        str,
        Field(
            ...,
            max_length=4,
            min_length=1,
            pattern='[A-Z]+',
            title='UnsupportedDerived',
        ),
    ],
)


@dataclass
class Root:
    single: Single
    duplicate: Duplicate
    same: SameDerived
    unsupported: Unsupported
    inherited: UnsupportedDerived
    empty: EmptySingle
    ordinary: str
