# generated by datamodel-codegen:
#   filename:  pattern_alternatives_simple.xsd

from __future__ import annotations

from typing import Annotated, TypeAlias

from msgspec import Meta, Struct

Token: TypeAlias = Annotated[
    str, Meta(pattern='(?=\\A)(?:[A-Z]+|[0-9]+)\\Z', title='Token')
]


class Root(Struct):
    value: Token
