# generated by datamodel-codegen:
#   filename:  pattern_alternatives_simple.xsd

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType

Token = TypeAliasType(
    "Token",
    Annotated[str, Field(..., pattern='(?=\\A)(?:[A-Z]+|[0-9]+)\\Z', title='Token')],
)


@dataclass(config=ConfigDict(regex_engine="python-re"))
class Root:
    value: Token
