# generated by datamodel-codegen:
#   filename:  special_float_defaults.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from math import inf, nan
from pydantic import BaseModel, confloat


class Model(BaseModel):
    finite: float | None = 1.5
    positive: float | None = inf
    positiveXsd11: float | None = inf
    negative: float | None = -inf
    notNumber: float | None = nan
    bounded: confloat(ge=-inf, lt=inf) | None = None
    limit: float | None = inf
