# generated by datamodel-codegen:
#   filename:  unicode_ncname_schema.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Root(BaseModel):
    field_ue33_62: int | None = Field(None, alias='ำ62')
