# generated by datamodel-codegen:
#   filename:  redefine_self_reference.xsd
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Container(BaseModel):
    before: str
    base: str
    after: str
    baseAttr: str | None = None
    addedAttr: str | None = None
    tail: str


class Root(Container):
    pass
