# generated by datamodel-codegen:
#   filename:  tagged.json

from __future__ import annotations

from typing import TypeAlias

from msgspec import Struct as _Struct


class Struct(_Struct, frozen=True):
    pass


class Cat(Struct, tag_field='kind', tag='cat'):
    value: int


class Dog(Struct, tag_field='kind', tag='dog'):
    value: int


Items: TypeAlias = Cat | Dog


class Container(Struct):
    items: set[Items]
