# generated by datamodel-codegen:
#   filename:  ir_callable.json

from __future__ import annotations

from collections import deque
from typing import Callable

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: Callable[[deque[int]], int]


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
