# generated by datamodel-codegen:
#   filename:  nested.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Child(BaseModel):
    value: int


class Item(BaseModel):
    value: Child


class Container(BaseModel):
    items: set[Item]
