# generated by datamodel-codegen:
#   filename:  object.json

from __future__ import annotations

from msgspec import Struct as _Struct


class Struct(_Struct, frozen=True):
    pass


class Item(Struct):
    value: int


class Container(Struct):
    items: set[Item]
