"""Regression tests for raw sample-data input handling."""

from __future__ import annotations

from typing import TYPE_CHECKING

from datamodel_code_generator.__main__ import Exit
from tests.conftest import freeze_time
from tests.main.conftest import run_main_and_assert

if TYPE_CHECKING:
    from pathlib import Path

    import pytest

PYDANTIC_V2_ARGS = ["--output-model-type", "pydantic_v2.BaseModel"]


def _write_input(tmp_path: Path, name: str, content: str) -> Path:
    input_path = tmp_path / name
    input_path.write_text(content, encoding="utf-8")
    return input_path


@freeze_time("2019-07-26")
def test_dict_text_input_is_parsed(output_file: Path, tmp_path: Path) -> None:
    """Parse dict text input instead of treating it as a raw string sample."""
    run_main_and_assert(
        input_path=_write_input(tmp_path, "dict_text_input.txt", "{'a': 1}"),
        output_path=output_file,
        input_file_type="dict",
        expected_output="""# generated by datamodel-codegen:
#   filename:  dict_text_input.txt
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    a: int
""",
        extra_args=PYDANTIC_V2_ARGS,
    )


@freeze_time("2019-07-26")
def test_csv_duplicate_header_keeps_following_columns(output_file: Path, tmp_path: Path) -> None:
    """Use DictReader row values so duplicate headers do not hide later columns."""
    run_main_and_assert(
        input_path=_write_input(tmp_path, "duplicate_header.csv", "a,a,b\n1,2,3\n"),
        output_path=output_file,
        input_file_type="csv",
        expected_output="""# generated by datamodel-codegen:
#   filename:  duplicate_header.csv
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    a: str
    b: str
""",
        extra_args=PYDANTIC_V2_ARGS,
    )


@freeze_time("2019-07-26")
def test_csv_missing_trailing_cell_infers_null_column(output_file: Path, tmp_path: Path) -> None:
    """Preserve missing trailing cells from the first row."""
    run_main_and_assert(
        input_path=_write_input(tmp_path, "missing_trailing_cell.csv", "a,b,c\n1,2\n"),
        output_path=output_file,
        input_file_type="csv",
        expected_output="""# generated by datamodel-codegen:
#   filename:  missing_trailing_cell.csv
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    a: str
    b: str
    c: None
""",
        extra_args=PYDANTIC_V2_ARGS,
    )


@freeze_time("2019-07-26")
def test_yaml_top_level_list_is_supported(output_file: Path, tmp_path: Path) -> None:
    """Allow YAML raw sample data to use a top-level list like JSON input."""
    run_main_and_assert(
        input_path=_write_input(tmp_path, "top_level_list.yaml", "- a: 1\n"),
        output_path=output_file,
        input_file_type="yaml",
        expected_output="""# generated by datamodel-codegen:
#   filename:  top_level_list.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class ModelItem(BaseModel):
    a: int


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem]
""",
        extra_args=PYDANTIC_V2_ARGS,
    )


def test_yaml_genson_errors_are_wrapped(output_file: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Wrap genson failures for YAML values that cannot become JSON Schema."""
    run_main_and_assert(
        input_path=_write_input(tmp_path, "set_value.yaml", "fruits: !!set\n  ? apple\n  ? banana\n"),
        output_path=output_file,
        input_file_type="yaml",
        expected_exit=Exit.ERROR,
        capsys=capsys,
        expected_stderr_contains="Invalid file format for yaml",
        extra_args=PYDANTIC_V2_ARGS,
    )
