"""Validate public API option sets against origin/main baseline."""

from __future__ import annotations

from datamodel_code_generator import GenerateConfig
from datamodel_code_generator.config import ParserConfig
from datamodel_code_generator.util import is_pydantic_v2

EXPECTED_GENERATE_KWONLY = {
    "input_filename",
    "input_file_type",
    "output",
    "output_model_type",
    "target_python_version",
    "target_pydantic_version",
    "base_class",
    "base_class_map",
    "additional_imports",
    "class_decorators",
    "custom_template_dir",
    "extra_template_data",
    "validation",
    "field_constraints",
    "snake_case_field",
    "strip_default_none",
    "aliases",
    "disable_timestamp",
    "enable_version_header",
    "enable_command_header",
    "command_line",
    "allow_population_by_field_name",
    "allow_extra_fields",
    "extra_fields",
    "use_generic_base_class",
    "apply_default_values_for_required_fields",
    "force_optional_for_required_fields",
    "class_name",
    "use_standard_collections",
    "use_schema_description",
    "use_field_description",
    "use_field_description_example",
    "use_attribute_docstrings",
    "use_inline_field_description",
    "use_default_kwarg",
    "reuse_model",
    "reuse_scope",
    "shared_module_name",
    "encoding",
    "enum_field_as_literal",
    "enum_field_as_literal_map",
    "ignore_enum_constraints",
    "use_one_literal_as_default",
    "use_enum_values_in_discriminator",
    "set_default_enum_member",
    "use_subclass_enum",
    "use_specialized_enum",
    "strict_nullable",
    "use_generic_container_types",
    "enable_faux_immutability",
    "disable_appending_item_suffix",
    "strict_types",
    "empty_enum_field_name",
    "custom_class_name_generator",
    "field_extra_keys",
    "field_include_all_keys",
    "field_extra_keys_without_x_prefix",
    "model_extra_keys",
    "model_extra_keys_without_x_prefix",
    "openapi_scopes",
    "include_path_parameters",
    "graphql_scopes",
    "wrap_string_literal",
    "use_title_as_name",
    "use_operation_id_as_name",
    "use_unique_items_as_set",
    "use_tuple_for_fixed_items",
    "allof_merge_mode",
    "http_headers",
    "http_ignore_tls",
    "http_timeout",
    "use_annotated",
    "use_serialize_as_any",
    "use_non_positive_negative_number_constrained_types",
    "use_decimal_for_multiple_of",
    "original_field_name_delimiter",
    "use_double_quotes",
    "use_union_operator",
    "collapse_root_models",
    "collapse_root_models_name_strategy",
    "collapse_reuse_models",
    "skip_root_model",
    "use_type_alias",
    "use_root_model_type_alias",
    "special_field_name_prefix",
    "remove_special_field_name_prefix",
    "capitalise_enum_members",
    "keep_model_order",
    "custom_file_header",
    "custom_file_header_path",
    "custom_formatters",
    "custom_formatters_kwargs",
    "use_pendulum",
    "use_standard_primitive_types",
    "http_query_parameters",
    "treat_dot_as_module",
    "use_exact_imports",
    "union_mode",
    "output_datetime_class",
    "output_date_class",
    "keyword_only",
    "frozen_dataclasses",
    "no_alias",
    "use_frozen_field",
    "use_default_factory_for_optional_nested_models",
    "formatters",
    "settings_path",
    "parent_scoped_naming",
    "naming_strategy",
    "duplicate_name_suffix",
    "dataclass_arguments",
    "disable_future_imports",
    "type_mappings",
    "type_overrides",
    "read_only_write_only_model_type",
    "use_status_code_in_response_name",
    "all_exports_scope",
    "all_exports_collision_strategy",
    "field_type_collision_strategy",
    "module_split_mode",
}

EXPECTED_PARSER_KWONLY = {
    "data_model_type",
    "data_model_root_type",
    "data_type_manager_type",
    "data_model_field_type",
    "base_class",
    "base_class_map",
    "additional_imports",
    "class_decorators",
    "custom_template_dir",
    "extra_template_data",
    "target_python_version",
    "dump_resolve_reference_action",
    "validation",
    "field_constraints",
    "snake_case_field",
    "strip_default_none",
    "aliases",
    "allow_population_by_field_name",
    "apply_default_values_for_required_fields",
    "allow_extra_fields",
    "extra_fields",
    "use_generic_base_class",
    "force_optional_for_required_fields",
    "class_name",
    "use_standard_collections",
    "base_path",
    "use_schema_description",
    "use_field_description",
    "use_field_description_example",
    "use_attribute_docstrings",
    "use_inline_field_description",
    "use_default_kwarg",
    "reuse_model",
    "reuse_scope",
    "shared_module_name",
    "encoding",
    "enum_field_as_literal",
    "enum_field_as_literal_map",
    "ignore_enum_constraints",
    "set_default_enum_member",
    "use_subclass_enum",
    "use_specialized_enum",
    "strict_nullable",
    "use_generic_container_types",
    "enable_faux_immutability",
    "remote_text_cache",
    "disable_appending_item_suffix",
    "strict_types",
    "empty_enum_field_name",
    "custom_class_name_generator",
    "field_extra_keys",
    "field_include_all_keys",
    "field_extra_keys_without_x_prefix",
    "model_extra_keys",
    "model_extra_keys_without_x_prefix",
    "wrap_string_literal",
    "use_title_as_name",
    "use_operation_id_as_name",
    "use_unique_items_as_set",
    "use_tuple_for_fixed_items",
    "allof_merge_mode",
    "http_headers",
    "http_ignore_tls",
    "http_timeout",
    "use_annotated",
    "use_serialize_as_any",
    "use_non_positive_negative_number_constrained_types",
    "use_decimal_for_multiple_of",
    "original_field_name_delimiter",
    "use_double_quotes",
    "use_union_operator",
    "allow_responses_without_content",
    "collapse_root_models",
    "collapse_root_models_name_strategy",
    "collapse_reuse_models",
    "skip_root_model",
    "use_type_alias",
    "special_field_name_prefix",
    "remove_special_field_name_prefix",
    "capitalise_enum_members",
    "keep_model_order",
    "use_one_literal_as_default",
    "use_enum_values_in_discriminator",
    "known_third_party",
    "custom_formatters",
    "custom_formatters_kwargs",
    "use_pendulum",
    "use_standard_primitive_types",
    "http_query_parameters",
    "treat_dot_as_module",
    "use_exact_imports",
    "default_field_extras",
    "target_datetime_class",
    "target_date_class",
    "keyword_only",
    "frozen_dataclasses",
    "no_alias",
    "use_frozen_field",
    "use_default_factory_for_optional_nested_models",
    "formatters",
    "defer_formatting",
    "parent_scoped_naming",
    "naming_strategy",
    "duplicate_name_suffix",
    "dataclass_arguments",
    "type_mappings",
    "type_overrides",
    "read_only_write_only_model_type",
    "field_type_collision_strategy",
    "target_pydantic_version",
}


def _get_field_names(model: object) -> set[str]:
    if is_pydantic_v2():
        return set(model.model_fields)
    return set(model.__fields__)


def test_generate_options_match_origin_main() -> None:
    assert _get_field_names(GenerateConfig) == EXPECTED_GENERATE_KWONLY


def test_parser_options_match_origin_main() -> None:
    assert _get_field_names(ParserConfig) == EXPECTED_PARSER_KWONLY
