# generated by datamodel-codegen:
#   filename:  control.json

from __future__ import annotations

from typing import Annotated, Literal, Union

from msgspec import UNSET, Meta, Struct, UnsetType


class Child(Struct):
    value: Union[int, UnsetType] = UNSET


class Record(Struct):
    label: Union[str, UnsetType] = UNSET
    list_aliased: Union[str, UnsetType] = UNSET
    list_aliased_1: Union[str, UnsetType] = UNSET
    items: Union[list[int], UnsetType] = UNSET
    field_label: Union[str, UnsetType] = UNSET
    count: Union[Annotated[int, Meta(description='Field list')], UnsetType] = UNSET
    optional_label: Union[str, UnsetType] = UNSET
    choice: Union[Literal['list', 'Optional', 'Field'], UnsetType] = UNSET
    child: Union[Child, UnsetType] = UNSET
