# generated by datamodel-codegen:
#   filename:  control.json

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class Child(BaseModel):
    value: Optional[int] = None


class Record(BaseModel):
    label: Optional[str] = None
    list_aliased: Optional[str] = None
    list_aliased_1: Optional[str] = None
    items: Optional[list[int]] = None
    field_label: Optional[str] = None
    count: Optional[int] = Field(None, description='Field list')
    optional_label: Optional[str] = None
    choice: Optional[Literal['list', 'Optional', 'Field']] = None
    child: Optional[Child] = None
