# generated by datamodel-codegen:
#   filename:  schema_b.json

from __future__ import annotations

from pydantic.dataclasses import dataclass

from . import shared


@dataclass
class Model:
    info: shared.SharedModel | None = None
