# generated by datamodel-codegen:
#   filename:  schema_a.json

from __future__ import annotations

from pydantic.dataclasses import dataclass

from . import shared


@dataclass
class Model:
    data: shared.SharedModel | None = None
