# generated by datamodel-codegen:
#   filename:  a.schema.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class TypeA(BaseModel):
    value: str
