# generated by datamodel-codegen:
#   filename:  protobuf
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ExampleSpecProto2SpecProto2LegacyGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
