# generated by datamodel-codegen:
#   filename:  protobuf
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ExampleShopV1OrderLineItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sku: str | None = ''
    quantity: int | None = 0
