# generated by datamodel-codegen:
#   filename:  unused.json

from typing import Optional

from pydantic import BaseModel


class Record(BaseModel):
    list: Optional[str] = 'list Optional Field'
    Field: Optional[str] = None
