# generated by datamodel-codegen:
#   filename:  unused.json

from pydantic.dataclasses import dataclass


@dataclass
class Record:
    list: str | None = 'list Optional Field'
    Field: str | None = None
