# generated by datamodel-codegen:
#   filename:  unused.json

from __future__ import annotations

from pydantic import BaseModel


class Record(BaseModel):
    list: str | None = 'list Optional Field'
    Field: str | None = None
