# generated by datamodel-codegen:
#   filename:  boolean_property.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic.dataclasses import dataclass


@dataclass
class Model:
    field: Any | None = None
