# generated by datamodel-codegen:
#   filename:  reuse_scope_tree_dataclass
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass

from .shared import SharedModel as SharedModel_1


@dataclass(frozen=True)
class SharedModel(SharedModel_1):
    pass


@dataclass(frozen=True)
class Model:
    data: SharedModel | None = None
