# generated by datamodel-codegen:
#   filename:  special_enum.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class ModelEnum(Enum):
    True_ = True
    False_ = False
    empty = ''
    _ = '\n'
    __ = '\r\n'
    __1 = '\t'
    __2 = '\b'
    __3 = '\\'


class Model(BaseModel):
    __root__: Optional[ModelEnum] = None
