# generated by datamodel-codegen:
#   filename:  cyclic-mutual-types.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


ID = TypeAliasType("ID", str)
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class A(BaseModel):
    id: ID
    link: B | None = None
    name: String | None = None
    typename__: Literal['A'] | None = Field('A', alias='__typename')


class B(BaseModel):
    id: ID
    link: A | None = None
    name: String | None = None
    typename__: Literal['B'] | None = Field('B', alias='__typename')


A.model_rebuild()
