# generated by datamodel-codegen:
#   filename:  enums.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


Color: TypeAlias = Literal['BLUE', 'GREEN', 'RED']


EmployeeShiftStatus: TypeAlias = Literal['NOT_ON_SHIFT', 'ON_SHIFT']
"""
Employee shift status
"""


EnumWithOneField: TypeAlias = Literal['FIELD']
