# generated by datamodel-codegen:
#   filename:  enums.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Color(BaseModel):
    __root__: Literal['BLUE', 'GREEN', 'RED']


class EmployeeShiftStatus(BaseModel):
    """
    Employee shift status
    """

    __root__: Literal['NOT_ON_SHIFT', 'ON_SHIFT']


class EnumWithOneField(BaseModel):
    __root__: Literal['FIELD']
