# generated by datamodel-codegen:
#   filename:  msgspec_empty_list_defaults.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Item(BaseModel):
    n: int


class Box(BaseModel):
    items: list[Item] | None = Field([], validate_default=True)
    nullable_items: list[Item | None] | None = Field([], validate_default=True)
    nullable_container: list[Item] | None = Field([], validate_default=True)
    nonnull_nullable_items: list[Item | None] | None = Field([], validate_default=True)
    empty: list[Item] | None = Field([], validate_default=True)
    direct_item: Item | None = Field({'n': 8}, validate_default=True)
    count: int | None = 9
    numbers: list[int] | None = [3, 1, 2]
    matrix: list[list[Item]] | None = Field([], validate_default=True)
    cube: list[list[list[Item]]] | None = Field([], validate_default=True)
    scalar_cube: list[list[list[int]]] | None = [[[3, 1], [2]]]
