# generated by datamodel-codegen:
#   filename:  root_union_query.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict, Union

from typing_extensions import NotRequired

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Other(TypedDict):
    value: String
    typename__: NotRequired[Literal['Other']]


Choice: TypeAlias = Union[
    'Other',
    'Query',
]


class Query(TypedDict):
    choice: NotRequired[Choice | None]
    self: NotRequired[Query | None]
    value: String
    typename__: NotRequired[Literal['Query']]


class Holder(TypedDict):
    mutation: NotRequired[Any]
    query: NotRequired[Query | None]
    subscription: NotRequired[Any]
    typename__: NotRequired[Literal['Holder']]
