# generated by datamodel-codegen:
#   filename:  root_union_ordinary.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, Literal, Union

from pydantic import Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


@dataclass
class Holder:
    mutation: Any | None = None
    query: Any | None = None
    subscription: Any | None = None
    typename__: Literal['Holder'] | None = Field('Holder', alias='__typename')


@dataclass
class Other:
    value: String
    typename__: Literal['Other'] | None = Field('Other', alias='__typename')


@dataclass
class Second:
    value: String
    self: Second | None = None
    typename__: Literal['Second'] | None = Field('Second', alias='__typename')


Choice = TypeAliasType(
    "Choice",
    Union[
        'Other',
        'Second',
    ],
)
