# generated by datamodel-codegen:
#   filename:  split
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Baz(BaseModel):
    quux: Int
    typename__: Literal['Baz'] | None = Field('Baz', alias='__typename')


class Bar(BaseModel):
    eggs: String
    foo: Foo
    typename__: Literal['Bar'] | None = Field('Bar', alias='__typename')


class Foo(BaseModel):
    baz: Bar
    id: Int
    typename__: Literal['Foo'] | None = Field('Foo', alias='__typename')


Bar.update_forward_refs()
