# generated by datamodel-codegen:
#   filename:  typename_collision.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias, Union

from msgspec import Struct, UnsetType, field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Base(Struct):
    value: Int
    typename__: Literal['Base'] | UnsetType = field(name='__typename', default='Base')


class ZNode(Struct):
    camel_value: Int = field(name='camelValue')
    typename__: String
    typename___1: Literal['ZNode'] | UnsetType = field(
        name='__typename', default='ZNode'
    )


class Cross(Base, kw_only=True):
    typename___1: String = field(name='typename__')
    value: Int
    typename__: Literal['Cross'] | UnsetType = field(name='__typename', default='Cross')


class Item(ZNode, kw_only=True):
    camel_value: Int = field(name='camelValue')
    typename__: String
    typename___1_1: Int = field(name='typename___1')
    typename___1: Literal['Item'] | UnsetType = field(name='__typename', default='Item')


class Ordinary(Base):
    value: Int
    typename__: Literal['Ordinary'] | UnsetType = field(
        name='__typename', default='Ordinary'
    )


class Second(ZNode, kw_only=True):
    camel_value: Int = field(name='camelValue')
    typename__: String
    typename___1_1: Int = field(name='typename___1')
    typename___1: Literal['Second'] | UnsetType = field(
        name='__typename', default='Second'
    )


class Solo(Struct):
    typename__: String
    typename___1: Literal['Solo'] | UnsetType = field(name='__typename', default='Solo')


class ItemInput(Struct):
    camel_value: Int = field(name='camelValue')
    typename__: String
    typename___1: Int
    typename___2: Literal['ItemInput'] | UnsetType = field(
        name='__typename', default='ItemInput'
    )


Choice: TypeAlias = Union[
    'Item',
    'Second',
]


class ANode(ZNode, kw_only=True):
    camel_value: Int = field(name='camelValue')
    typename__: String
    typename___1_1: Int = field(name='typename___1')
    typename___1: Literal['ANode'] | UnsetType = field(
        name='__typename', default='ANode'
    )
