# generated by datamodel-codegen:
#   filename:  typename_collision.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Union

from pydantic import Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType

Boolean = TypeAliasType("Boolean", bool)
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int = TypeAliasType("Int", int)
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String = TypeAliasType("String", str)
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


@dataclass
class Base:
    value: Int


@dataclass
class ZNode:
    typename__: String
    camel_value: Int = Field(..., alias='camelValue')


@dataclass
class Cross(Base):
    typename__: String
    value: Int


@dataclass
class Item(ZNode):
    typename__: String
    typename___1: Int = Field(..., kw_only=True)
    camel_value: Int = Field(..., alias='camelValue')


@dataclass
class Second(ZNode):
    typename__: String
    typename___1: Int = Field(..., kw_only=True)
    camel_value: Int = Field(..., alias='camelValue')


@dataclass
class Solo:
    typename__: String


@dataclass
class ItemInput:
    typename__: String
    typename___1: Int
    camel_value: Int = Field(..., alias='camelValue')


Choice = TypeAliasType(
    "Choice",
    Union[
        'Item',
        'Second',
    ],
)


@dataclass
class ANode(ZNode):
    typename__: String
    typename___1: Int = Field(..., kw_only=True)
    camel_value: Int = Field(..., alias='camelValue')
