# generated by datamodel-codegen:
#   filename:  typename_collision_scoped.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypeAlias, TypedDict

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Base(TypedDict):
    typename__: String
    value: Int


class Common(TypedDict):
    value: Int


class Mid(Base):
    typename__: String
    typename___1: Int
    value: Int


class OtherBase(Common):
    value: Int


class Side(Common):
    typename__: Int
    value: Int


class Item(Mid, Base):
    renamed: String
    spare: Int
    value: Int


class Multi(OtherBase, Side, Common):
    spare: Int
    value: Int


class MultiOrdinary(OtherBase, Common):
    value: Int


class Ordinary(Base):
    label: String
    value: Int


class Terminal(Mid, Base):
    label: String
    typename___2: Int
    value: Int
