# generated by datamodel-codegen:
#   filename:  typename_collision_scoped.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias

from msgspec import Struct, UnsetType, field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class Base(Struct):
    typename__: String = field(name='label')
    value: Int
    typename___1: Literal['Base'] | UnsetType = field(name='__typename', default='Base')


class Common(Struct):
    value: Int
    typename__: Literal['Common'] | UnsetType = field(
        name='__typename', default='Common'
    )


class Mid(Base):
    typename__: String = field(name='label')
    typename___1: Int = field(name='spare')
    value: Int
    typename___2: Literal['Mid'] | UnsetType = field(name='__typename', default='Mid')


class OtherBase(Common):
    value: Int
    typename__: Literal['OtherBase'] | UnsetType = field(
        name='__typename', default='OtherBase'
    )


class Side(Common):
    typename__: Int = field(name='spare')
    value: Int
    typename___1: Literal['Side'] | UnsetType = field(name='__typename', default='Side')


class Item(Mid, Base, kw_only=True):
    renamed: String = field(name='label')
    spare: Int
    value: Int
    typename___1: Int = field(name='spare')
    typename___2: Literal['Item'] | UnsetType = field(name='__typename', default='Item')


class Multi(OtherBase, Side, Common, kw_only=True):
    spare: Int
    value: Int
    typename__: Int = field(name='spare')
    typename___1: Literal['Multi'] | UnsetType = field(
        name='__typename', default='Multi'
    )


class MultiOrdinary(OtherBase, Common):
    value: Int
    typename__: Literal['MultiOrdinary'] | UnsetType = field(
        name='__typename', default='MultiOrdinary'
    )


class Ordinary(Base, kw_only=True):
    label: String
    value: Int
    typename___1: Literal['Ordinary'] | UnsetType = field(
        name='__typename', default='Ordinary'
    )


class Terminal(Mid, Base):
    label: String
    typename___2: Int = field(name='spare')
    value: Int
    typename___1: Int = field(name='spare')
    typename___3: Literal['Terminal'] | UnsetType = field(
        name='__typename', default='Terminal'
    )
