# generated by datamodel-codegen:
#   filename:  typename_collision.graphql
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias, Union

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


@dataclass
class Base:
    value: Int


@dataclass
class ZNode:
    camel_value: Int
    typename__: String


@dataclass
class Cross(Base):
    typename__: String
    value: Int


@dataclass
class Item(ZNode):
    camel_value: Int
    typename__: String
    typename___1: Int


@dataclass
class Ordinary(Base):
    value: Int


@dataclass
class Second(ZNode):
    camel_value: Int
    typename__: String
    typename___1: Int


@dataclass
class Solo:
    typename__: String


@dataclass
class ItemInput:
    camel_value: Int
    typename__: String
    typename___1: Int


Choice: TypeAlias = Union[
    'Item',
    'Second',
]


@dataclass
class ANode(ZNode):
    camel_value: Int
    typename__: String
    typename___1: Int
