# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from collections.abc import Callable

from pydantic import BaseModel, Field


class NoneFirst(BaseModel):
    value: int | Callable[[int], int] | None = Field(..., title='Value')
