# generated by datamodel-codegen:
#   filename:  dotted_module_exports_collision

from __future__ import annotations

from .api.v1.user.user import User as UserUserUser
from .api.v2.user.user import User as UserUser

__all__ = [
    "UserUser",
    "UserUserUser",
]
