# generated by datamodel-codegen:
#   filename:  condecimal_decimal_collision_no_default.json

from __future__ import annotations

from decimal import Decimal as Decimal_aliased

from pydantic import BaseModel, condecimal


class CondecimalDecimalCollisionNoDefault(BaseModel):
    Decimal: str | None = None
    amount: (
        condecimal(ge=Decimal_aliased('0'), multiple_of=Decimal_aliased('0.25')) | None
    ) = None
