# generated by datamodel-codegen:
#   filename:  serialized_decimal_defaults.json

from __future__ import annotations

from pydantic import BaseModel


class Invoice(BaseModel):
    amount: str | None = '12.340'
    invalid_amount: str | None = 'not-a-decimal'
    nullable_amount: str | None = None
    label: str | None = 'retail'
