# generated by datamodel-codegen:
#   filename:  const.json

from __future__ import annotations

from typing import Literal

from pydantic import Field, RootModel


class Root(RootModel[Literal['a']]):
    root: Literal['a'] = Field(..., min_length=1)


class Base(RootModel[str]):
    root: str
