# generated by datamodel-codegen:
#   filename:  const.json

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class Root(RootModel[Literal['a']]):
    root: Literal['a']


class Base(RootModel[str]):
    root: str
