# generated by datamodel-codegen:
#   filename:  date_time_length.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[str]):
    root: str = Field(..., max_length=30, min_length=1)


class Base(RootModel[str]):
    root: str
