# generated by datamodel-codegen:
#   filename:  format.json

from __future__ import annotations

from pydantic import EmailStr, RootModel


class Root(RootModel[EmailStr]):
    root: EmailStr


class Base(RootModel[str]):
    root: str
