# generated by datamodel-codegen:
#   filename:  length.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[str]):
    root: str = Field(
        'base', description='Outer description', max_length=3, min_length=1
    )


class Base(RootModel[str]):
    root: str = 'base'
