# generated by datamodel-codegen:
#   filename:  multiple.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[int]):
    root: int = Field(..., multiple_of=6)


class Base(RootModel[int]):
    root: int
