# generated by datamodel-codegen:
#   filename:  number_mapped_string_length.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[bytes]):
    root: bytes = Field(..., max_length=4, min_length=3)


class Base(RootModel[float]):
    root: float
