# generated by datamodel-codegen:
#   filename:  allof.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ApiBaseSchema:
    base: int


@dataclass
class ApiChildSchema(ApiBaseSchema):
    renamed: str
    y: int | None = 2
    z: bool | None = True


@dataclass
class ApiRootSchema:
    child: ApiChildSchema
