# generated by datamodel-codegen:
#   filename:  allof.json

from __future__ import annotations

from pydantic import AliasChoices, BaseModel, Field


class ApiBaseSchema(BaseModel):
    base: int


class ApiChildSchema(ApiBaseSchema):
    renamed: str = Field(
        ..., validation_alias=AliasChoices('x', 'renamed', 'alternate')
    )
    y: int | None = 2
    z: bool | None = True


class ApiRootSchema(BaseModel):
    child: ApiChildSchema
