# generated by datamodel-codegen:
#   filename:  direct.json

from __future__ import annotations

from pydantic import BaseModel, Field


class ApiBaseSchema(BaseModel):
    base: int


class ApiChildSchema(BaseModel):
    base: int
    renamed: str = Field(..., alias='x')
    y: int | None = 2
    z: bool | None = True


class ApiRootSchema(BaseModel):
    child: ApiChildSchema
