# generated by datamodel-codegen:
#   filename:  allof.json

from __future__ import annotations

from pydantic import BaseModel, Field


class ApiBaseSchema(BaseModel):
    base: int


class ApiChildSchema(ApiBaseSchema):
    renamed: str = Field(..., alias='x')
    legacy_count: int | None = Field(2, alias='y')
    flag: bool | None = Field(True, alias='z')


class ApiRootSchema(BaseModel):
    child: ApiChildSchema
