# generated by datamodel-codegen:
#   filename:  _internal
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Item(BaseModel):
    id: str | None = None
    sub_item: Authorization | None = None


class Item_1(BaseModel):
    id: str | None = None


class Invoice(BaseModel):
    id: str | None = None
    billing_item: Item_1 | None = None
    session: Session | None = None


class Item_2(BaseModel):
    id: str | None = None


class Session(BaseModel):
    id: str | None = None
    checkout_item: Item_2 | None = None
    root_item: Item | None = None


class Item_3(BaseModel):
    id: str | None = None


class Authorization(BaseModel):
    id: str | None = None
    item: Item_3 | None = None
    invoice: Invoice | None = None


Item.update_forward_refs()
Invoice.update_forward_refs()
Authorization.update_forward_refs()
