# generated by datamodel-codegen:
#   filename:  array_field_constraints.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class TestSchema(BaseModel):
    numbers: List[str] = Field(
        ..., description='A list of numbers', regex='^\\d{1,15}$'
    )
