# generated by datamodel-codegen:
#   filename:  file_d.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import file_a


class ModelD(BaseModel):
    firstName: str | None = None
    modelA: file_a.ModelA | None = None
