# generated by datamodel-codegen:
#   filename:  circular_imports_acyclic.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from . import RootModel


class ChildModel(BaseModel):
    id: Optional[str] = None
    parent: Optional[RootModel] = None


class AnotherChild(BaseModel):
    sibling: Optional[ChildModel] = None
