# generated by datamodel-codegen:
#   filename:  wire.json

from builtins import list as list_aliased_2
from typing import Literal

from pydantic import BaseModel
from pydantic import Field as Field_aliased


class Child(BaseModel):
    value: int | None = None


class Record(BaseModel):
    list: str | None = Field_aliased(None, alias='wire_list')
    list_aliased: str | None = None
    list_aliased_1: str | None = None
    items: list_aliased_2[int] | None = None
    Field: str | None = Field_aliased(None, alias='wire_field')
    count: int | None = Field_aliased(None, description='Field list')
    Optional: str | None = Field_aliased(None, alias='wire_optional')
    choice: Literal['list', 'Optional', 'Field'] | None = None
    child: Child | None = None
