# generated by datamodel-codegen:
#   filename:  root_model_aliases.json

from __future__ import annotations

from pydantic import RootModel

from datamodel_code_generator.enums import DataModelType
from tests.data.dynamic_models.root_model_alias_imports import (
    ImportedIntegerRoot,
    ImportedObject,
)

TwinNumber = RootModel[int]
