# generated by datamodel-codegen:
#   filename:  allof_with_description_only.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class MyModel(BaseModel):
    """
    A model that has a description.
    """

    name: Optional[str] = None


class MyOtherModel(MyModel):
    """
    Another model that should also have a description.
    """
