# generated by datamodel-codegen:
#   filename:  character_class.json

from __future__ import annotations

from pydantic import ConfigDict, Field, RootModel


class Root(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern='(?=[ab])(?=b)')


class Base(RootModel[str]):
    root: str = Field(..., pattern='[ab]')
