# generated by datamodel-codegen:
#   filename:  escaped_identical.json

from __future__ import annotations

from pydantic import RootModel, constr


class Root(RootModel[constr(pattern=r'\.')]):
    root: constr(pattern=r'\.')


class Base(RootModel[constr(pattern=r'\.')]):
    root: constr(pattern=r'\.')
