# generated by datamodel-codegen:
#   filename:  escaped_dot.json

from __future__ import annotations

from pydantic import ConfigDict, Field, RootModel


class Root(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern='\\A(?=[\\s\\S]*\\.)(?=[\\s\\S]*x)')


class Base(RootModel[str]):
    root: str = Field(..., pattern='\\.')
