# generated by datamodel-codegen:
#   filename:  single.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[str]):
    root: str = Field(..., min_length=1, pattern='a')


class Base(RootModel[str]):
    root: str = Field(..., pattern='a')
