# generated by datamodel-codegen:
#   filename:  single.json

from __future__ import annotations

from pydantic import RootModel, constr


class Root(RootModel[constr(pattern=r'a', min_length=1)]):
    root: constr(pattern=r'a', min_length=1)


class Base(RootModel[constr(pattern=r'a')]):
    root: constr(pattern=r'a')
