# generated by datamodel-codegen:
#   filename:  unicode.json

from __future__ import annotations

from pydantic import ConfigDict, RootModel, constr


class Root(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'\A(?=[\s\S]*猫)(?=[\s\S]*犬)')


class Base(RootModel[constr(pattern=r'猫')]):
    root: constr(pattern=r'猫')
