# generated by datamodel-codegen:
#   filename:  unknown_escape.json

from __future__ import annotations

from pydantic import ConfigDict, Field, RootModel


class Root(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: str = Field(..., pattern='(?=\\d)(?=1)')


class Base(RootModel[str]):
    root: str = Field(..., pattern='\\d')
