# generated by datamodel-codegen:
#   filename:  use_decimal_for_multiple_of.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, condecimal, confloat


class Model(BaseModel):
    price: Optional[condecimal(ge=0, le=99999.99, multiple_of=0.01)] = None
    quantity: Optional[condecimal(multiple_of=0.1)] = None
    rate: Optional[condecimal(multiple_of=0.001, lt=1.0, gt=0.0)] = None
    simple_float: Optional[confloat(ge=0.0, le=100.0)] = None
