# generated by datamodel-codegen:
#   filename:  decimal_defaults.avsc

from __future__ import annotations

from decimal import Decimal as Decimal_aliased
from typing import Annotated, TypeAlias

from msgspec import UNSET, Meta, Struct, UnsetType, convert, field

Money: TypeAlias = Annotated[Decimal_aliased, Meta(title='Money')]


class Ledger(Struct):
    amount: Money


Raw: TypeAlias = Annotated[bytes, Meta(max_length=2, min_length=2, title='Raw')]


class DecimalDefaults(Struct):
    Decimal: Decimal_aliased | UnsetType = Decimal_aliased('1E-2')
    positive: Decimal_aliased | UnsetType = Decimal_aliased('258E-2')
    negative: Decimal_aliased | UnsetType = Decimal_aliased('-258E-2')
    zero: Decimal_aliased | UnsetType = Decimal_aliased('0E-4')
    trailing: Decimal_aliased | UnsetType = Decimal_aliased('1200E-2')
    no_scale: Decimal_aliased | UnsetType = Decimal_aliased('123E-0')
    large: Decimal_aliased | UnsetType = (
        Decimal_aliased('12345678901234567890123456789012345678901234567890123456789012345678901234567890E-29')
    )
    fixed: Money | UnsetType = Decimal_aliased('258E-2')
    reference: Money | UnsetType = Decimal_aliased('-258E-2')
    array: list[Decimal_aliased] | UnsetType = field(
        default_factory=lambda: [Decimal_aliased('1E-2'), Decimal_aliased('-1E-2')]
    )
    map: dict[str, Money] | UnsetType = field(
        default_factory=lambda: {'z': Decimal_aliased('0E-2'), 'a': Decimal_aliased('1200E-2')}
    )
    union: Decimal_aliased | None | UnsetType = Decimal_aliased('1E-2')
    string_first: str | Decimal_aliased | UnsetType = '12'
    nullable: Decimal_aliased | None | UnsetType = UNSET
    record: Ledger | UnsetType = field(
        default_factory=lambda: convert(
            {'amount': Decimal_aliased('258E-2')}, type=Ledger
        )
    )
    record_array: list[Ledger] | UnsetType = field(
        default_factory=lambda: convert(
            [{'amount': Decimal_aliased('-258E-2')}], type=list[Ledger]
        )
    )
    nested: list[dict[str, Decimal_aliased]] | UnsetType = field(
        default_factory=lambda: [{'z': Decimal_aliased('12E-3'), 'a': Decimal_aliased('-12E-3')}]
    )
    ordinary: bytes | UnsetType = b'\xff'
    plain_fixed: Raw | UnsetType = b'\x01\x02'
