# generated by datamodel-codegen:
#   filename:  duration_defaults.avsc

from __future__ import annotations

from datetime import timedelta as timedelta_aliased
from typing import TypeAlias, TypedDict

from typing_extensions import NotRequired

Elapsed: TypeAlias = timedelta_aliased


class Frame(TypedDict):
    elapsed: Elapsed


Raw: TypeAlias = bytes


class DurationDefaults(TypedDict):
    timedelta: NotRequired[Elapsed]
    one: NotRequired[Elapsed]
    milliseconds: NotRequired[Elapsed]
    endian: NotRequired[Elapsed]
    maximum: NotRequired[Elapsed]
    array: NotRequired[list[Elapsed]]
    map: NotRequired[dict[str, Elapsed]]
    union: NotRequired[Elapsed | None]
    string_first: NotRequired[str | Elapsed]
    nullable: NotRequired[Elapsed | None]
    record: NotRequired[Frame]
    record_array: NotRequired[list[Frame]]
    nested: NotRequired[list[dict[str, Elapsed]]]
    ordinary_fixed: NotRequired[Raw]
    ordinary_bytes: NotRequired[bytes]
