# generated by datamodel-codegen:
#   filename:  duration_defaults.avsc

from __future__ import annotations

from datetime import timedelta as timedelta_aliased
from typing import Annotated, TypeAlias

from msgspec import UNSET, Meta, Struct, UnsetType, convert, field

Elapsed: TypeAlias = Annotated[timedelta_aliased, Meta(title='Elapsed')]


class Frame(Struct):
    elapsed: Elapsed


Raw: TypeAlias = Annotated[bytes, Meta(max_length=12, min_length=12, title='Raw')]


class DurationDefaults(Struct):
    timedelta: Elapsed | UnsetType = timedelta_aliased(milliseconds=0)
    one: Elapsed | UnsetType = timedelta_aliased(milliseconds=1)
    milliseconds: Elapsed | UnsetType = timedelta_aliased(milliseconds=1001)
    endian: Elapsed | UnsetType = timedelta_aliased(milliseconds=16909060)
    maximum: Elapsed | UnsetType = timedelta_aliased(milliseconds=4294967295)
    array: list[Elapsed] | UnsetType = field(
        default_factory=lambda: convert(
            [timedelta_aliased(milliseconds=0), timedelta_aliased(milliseconds=1), timedelta_aliased(milliseconds=1001)],
            type=list[Elapsed],
        )
    )
    map: dict[str, Elapsed] | UnsetType = field(
        default_factory=lambda: {'z': timedelta_aliased(milliseconds=4294967295), 'a': timedelta_aliased(milliseconds=1)}
    )
    union: Elapsed | None | UnsetType = timedelta_aliased(milliseconds=1001)
    string_first: str | Elapsed | UnsetType = 'kept'
    nullable: Elapsed | None | UnsetType = UNSET
    record: Frame | UnsetType = field(
        default_factory=lambda: convert(
            {'elapsed': timedelta_aliased(milliseconds=1001)}, type=Frame
        )
    )
    record_array: list[Frame] | UnsetType = field(
        default_factory=lambda: convert(
            [{'elapsed': timedelta_aliased(milliseconds=1)}], type=list[Frame]
        )
    )
    nested: list[dict[str, Elapsed]] | UnsetType = field(
        default_factory=lambda: [{'z': timedelta_aliased(milliseconds=1001), 'a': timedelta_aliased(milliseconds=1)}]
    )
    ordinary_fixed: Raw | UnsetType = (
        b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
    )
    ordinary_bytes: bytes | UnsetType = (
        b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
    )
