# generated by datamodel-codegen:
#   filename:  temporal_defaults_simple.avsc

from __future__ import annotations

from pydantic import BaseModel


class TemporalDefaults(BaseModel):
    day: str | None = '1970-01-02'
    clock: str | None = '00:00:01'
