# generated by datamodel-codegen:
#   filename:  temporal_defaults.avsc

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class LogicalRecord:
    day: str
    instant: str


@dataclass
class TemporalDefaults:
    datetime_module: str | None = '1970-01-01'
    date_before: str | None = '1969-12-31'
    date_after: str | None = '1970-01-02'
    date_min: str | None = '0001-01-01'
    date_max: str | None = '9999-12-31'
    time_millis_zero: str | None = '00:00:00'
    time_millis: str | None = '00:00:01.001000'
    time_millis_last: str | None = '23:59:59.999000'
    time_micros: str | None = '00:00:01.234567'
    time_micros_last: str | None = '23:59:59.999999'
    timestamp_millis: str | None = '1970-01-01T00:00:01.001000+00:00'
    timestamp_micros_before: str | None = '1969-12-31T23:59:59.999999+00:00'
    timestamp_micros_exact: str | None = '2255-06-05T23:47:34.740991+00:00'
    timestamp_micros_min: str | None = '0001-01-01T00:00:00+00:00'
    timestamp_micros_max: str | None = '9999-12-31T23:59:59.999999+00:00'
    timestamp_nanos: str | None = '1970-01-01T00:00:00.000001+00:00'
    timestamp_nanos_before: str | None = '1969-12-31T23:59:59.999999+00:00'
    local_millis: str | None = '1969-12-31T23:59:59.999000'
    local_micros: str | None = '1970-01-01T00:00:01.000001'
    local_nanos: str | None = '1969-12-31T23:59:59.999999'
    date_union: str | None = '1970-01-02'
    plain_union: int | str | None = 1000
    nullable: str | None = None
    wrapped: str | None = '1969-12-31T23:59:59.999999'
    wrapped_union: str | None = '00:00:01'
    date_array: list[str] | None = field(
        default_factory=lambda: ['1970-01-02', '1969-12-31']
    )
    time_map: dict[str, str] | None = field(
        default_factory=lambda: {'z': '00:00:00.001001', 'a': '00:00:00.000001'}
    )
    record: LogicalRecord | None = field(
        default_factory=lambda: LogicalRecord(
            instant='1970-01-01T00:00:01.000001+00:00', day='1970-01-02'
        )
    )
    record_array: list[LogicalRecord] | None = field(
        default_factory=lambda: [{'day': '1969-12-31', 'instant': '1969-12-31T23:59:59.999999+00:00'}]
    )
    ordinary: int | None = 1000
