# generated by datamodel-codegen:
#   filename:  datatypes/BarStats.json

from __future__ import annotations

from pydantic import BaseModel


class BarStats(BaseModel):
    value: float | None = None
