# generated by datamodel-codegen:
#   filename:  namespace_null_fixed.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, conbytes


class Z(RootModel[conbytes(min_length=8, max_length=8)]):
    root: conbytes(min_length=8, max_length=8) = Field(..., title='Z')


class Y(BaseModel):
    e: Z


class R(BaseModel):
    s: Y
    t: Z
