# generated by datamodel-codegen:
#   filename:  special_field_name_with_inheritance_model.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import NotRequired, Optional, TypedDict


class NestedBase(TypedDict):
    age: NotRequired[Optional[str]]


class Base(NestedBase):
    name: NotRequired[Optional[str]]


SpecialField = TypedDict(
    'SpecialField',
    {
        'age': NotRequired[Optional[str]],
        'name': NotRequired[Optional[str]],
        'global': NotRequired[Optional[str]],
        'with': NotRequired[Optional[str]],
        'class': NotRequired[Optional[int]],
        'class\'s': NotRequired[Optional[int]],
        'class-s': NotRequired[Optional[str]],
        '#': NotRequired[Optional[str]],
    },
)
