# generated by datamodel-codegen:
#   filename:  schema_b.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired

from . import shared


class Model(TypedDict):
    info: NotRequired[shared.SharedModel]
