# generated by datamodel-codegen:
#   filename:  simple.csv
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Model:
    id: str
    name: str
    tel: str
    zip_code: str
