# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, Field


class NumericConstraints(BaseModel):
    greater: int = Field(..., gt=9007199254740993)
    less: int = Field(..., lt=9007199254740993)
    negative_greater: int = Field(..., gt=-9007199254740993)
    negative_less: int = Field(..., lt=-9007199254740993)
    false_minimum: int = Field(..., ge=1)
    false_maximum: int = Field(..., le=3)
    without_bound: int
    small_greater: int = Field(..., gt=1)
    small_less: int = Field(..., lt=5)