# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, conint


class NumericConstraints(BaseModel):
    greater: conint(gt=9007199254740993)
    less: conint(lt=9007199254740993)
    negative_greater: conint(gt=-9007199254740993)
    negative_less: conint(lt=-9007199254740993)
    false_minimum: conint(ge=1)
    false_maximum: conint(le=3)
    without_bound: int
    small_greater: conint(gt=1)
    small_less: conint(lt=5)