# generated by datamodel-codegen:
#   filename:  ordinary.json

from __future__ import annotations

from pydantic import BaseModel, Field, confloat, conint


class NumericConstraints(BaseModel):
    integer_greater: conint(gt=1)
    integer_less: conint(lt=5)
    integer_multiple: conint(multiple_of=2)
    number_greater: confloat(gt=1.0)
    number_less: confloat(lt=5.0)
    number_multiple: confloat(multiple_of=2.0)
    fractional_multiple: confloat(multiple_of=0.125)
    fractional_bound: conint(ge=2)
    integral_float: confloat(lt=3.0)
    exact_large_integer: conint(gt=18014398509481984)
    negative_exact: conint(lt=-18014398509481984)
    ordered_data: int | None = Field(7, examples=[9, 7, 8])
