# generated by datamodel-codegen:
#   filename:  use_generic_base_class_deep_inheritance.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from .mammal import Mammal


class Dog(Mammal):
    breed: str | None = None
