# generated by datamodel-codegen:
#   filename:  shared.py

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType


class SharedModel(Struct):
    id: int | UnsetType = UNSET
    name: str | UnsetType = UNSET
