# generated by datamodel-codegen:
#   filename:  required.json

from typing import Literal

from pydantic import BaseModel, Field


class Child(BaseModel):
    value: int | None = None


class Record(BaseModel):
    list: str
    Field: str
    Optional: str
    list_aliased: str | None = None
    list_aliased_1: str | None = None
    items: list[int] | None = None
    count: int | None = Field(None, description='Field list')
    choice: Literal['list', 'Optional', 'Field'] | None = None
    child: Child | None = None
