# generated by datamodel-codegen:
#   filename:  required.json

from __future__ import annotations

from typing import Literal

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Child:
    value: int | None = None


@dataclass
class Record:
    list: str
    Field: str
    Optional: str
    list_aliased: str | None = None
    list_aliased_1: str | None = None
    items: list[int] | None = None
    count: int | None = Field(None, description='Field list')
    choice: Literal['list', 'Optional', 'Field'] | None = None
    child: Child | None = None
