# generated by datamodel-codegen:
#   filename:  late.json

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Record:
    count: int | None = Field(None, description='Field list')
    Field: str | None = None
