# generated by datamodel-codegen:
#   filename:  late.json

from pydantic import BaseModel, Field


class Record(BaseModel):
    count: int | None = Field(None, description='Field list')
    Field: str | None = None
