# generated by datamodel-codegen:
#   filename:  boolean_number_enum.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Value(Enum):
    bool_True = True
    int_1 = 1


class Root(BaseModel):
    value: Value | None = None
