# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Value(Enum):
    value_0 = {'kind': [True, 1]}
    value_1 = {'kind': [False, 0]}
    value_2 = {'other': []}
    value_3 = {'kind': [False, 0]}
    value_4 = {'kind': [True, 1]}
    value_5 = {'extra': []}


class Equal(Enum):
    value_0 = {'a': 1}
    value_1 = {'b': 2}
    value_2 = {'b': 2}
    value_3 = {'a': 1}


class Nullable(Enum):
    NoneType_None = None
    a = 'a'
    b = 'b'
    b_1 = 'b'
    c = 'c'


class Number(Enum):
    int_1 = 1
    int_2 = 2
    float_1_0 = 1.0
    int_3 = 3


class Root(BaseModel):
    value: Value
    equal: Equal
    nullable: Nullable
    number: Number