# generated by datamodel-codegen:
#   filename:  complex_empty_enum.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Value(Enum):
    value_0 = {'a': True}
    value_1 = {'a': 1}


class Root(BaseModel):
    value: Value | None = None
