# generated by datamodel-codegen:
#   filename:  scalars_partial.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Integer(Enum):
    int_1 = 1


class String(Enum):
    a = 'a'


class Number(Enum):
    float_1_5 = 1.5


class Root(BaseModel):
    integer: Integer
    string: String
    number: Number
