# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import IntEnum
from typing import Literal

from pydantic import BaseModel, Field


class Value(IntEnum):
    integer_1 = 1
    integer_0 = 0


class BoxLiteralLocalNumberLocalNumber(BaseModel):
    value: Value = Field(..., title='Value')


class BoxLiteralLocalTag(BaseModel):
    value: Literal['a'] = Field(..., title='Value')


class LocalEnumDataclass(BaseModel):
    box: BoxLiteralLocalTag
    validated: BoxLiteralLocalNumberLocalNumber
