# generated by datamodel-codegen:
#   filename:  nullvalue.proto

from __future__ import annotations

from enum import Enum

from msgspec import Struct, UnsetType, field


class GoogleProtobufNullValue(Enum):
    NULL_VALUE = 'NULL_VALUE'


class Payload(Struct):
    value: GoogleProtobufNullValue | UnsetType = 'NULL_VALUE'
    values: list[GoogleProtobufNullValue] | UnsetType = field(default_factory=list)
    lookup: dict[str, GoogleProtobufNullValue] | UnsetType = field(default_factory=dict)
