# generated by datamodel-codegen:
#   filename:  nullvalue.proto

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class GoogleProtobufNullValue(Enum):
    NULL_VALUE = 'NULL_VALUE'


@dataclass
class Payload:
    value: GoogleProtobufNullValue | None = GoogleProtobufNullValue.NULL_VALUE
    values: list[GoogleProtobufNullValue] | None = field(default_factory=list)
    lookup: dict[str, GoogleProtobufNullValue] | None = field(default_factory=dict)
