# generated by datamodel-codegen:
#   filename:  standard_enum.proto

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class UserState(Enum):
    UNKNOWN = 'UNKNOWN'
    READY = 'READY'


class GoogleProtobufSyntax(Enum):
    SYNTAX_PROTO2 = 'SYNTAX_PROTO2'
    """
    Syntax `proto2`.
    """
    SYNTAX_PROTO3 = 'SYNTAX_PROTO3'
    """
    Syntax `proto3`.
    """
    SYNTAX_EDITIONS = 'SYNTAX_EDITIONS'
    """
    Syntax `editions`.
    """


class GoogleProtobufFieldKind(Enum):
    TYPE_UNKNOWN = 'TYPE_UNKNOWN'
    """
    Field type unknown.
    """
    TYPE_DOUBLE = 'TYPE_DOUBLE'
    """
    Field type double.
    """
    TYPE_FLOAT = 'TYPE_FLOAT'
    """
    Field type float.
    """
    TYPE_INT64 = 'TYPE_INT64'
    """
    Field type int64.
    """
    TYPE_UINT64 = 'TYPE_UINT64'
    """
    Field type uint64.
    """
    TYPE_INT32 = 'TYPE_INT32'
    """
    Field type int32.
    """
    TYPE_FIXED64 = 'TYPE_FIXED64'
    """
    Field type fixed64.
    """
    TYPE_FIXED32 = 'TYPE_FIXED32'
    """
    Field type fixed32.
    """
    TYPE_BOOL = 'TYPE_BOOL'
    """
    Field type bool.
    """
    TYPE_STRING = 'TYPE_STRING'
    """
    Field type string.
    """
    TYPE_GROUP = 'TYPE_GROUP'
    """
    Field type group. Proto2 syntax only, and deprecated.
    """
    TYPE_MESSAGE = 'TYPE_MESSAGE'
    """
    Field type message.
    """
    TYPE_BYTES = 'TYPE_BYTES'
    """
    Field type bytes.
    """
    TYPE_UINT32 = 'TYPE_UINT32'
    """
    Field type uint32.
    """
    TYPE_ENUM = 'TYPE_ENUM'
    """
    Field type enum.
    """
    TYPE_SFIXED32 = 'TYPE_SFIXED32'
    """
    Field type sfixed32.
    """
    TYPE_SFIXED64 = 'TYPE_SFIXED64'
    """
    Field type sfixed64.
    """
    TYPE_SINT32 = 'TYPE_SINT32'
    """
    Field type sint32.
    """
    TYPE_SINT64 = 'TYPE_SINT64'
    """
    Field type sint64.
    """


class GoogleProtobufFieldDescriptorProtoType(Enum):
    TYPE_DOUBLE = 'TYPE_DOUBLE'
    """
    0 is reserved for errors.
    Order is weird for historical reasons.
    """
    TYPE_FLOAT = 'TYPE_FLOAT'
    TYPE_INT64 = 'TYPE_INT64'
    """
    Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT64 if
    negative values are likely.
    """
    TYPE_UINT64 = 'TYPE_UINT64'
    TYPE_INT32 = 'TYPE_INT32'
    """
    Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT32 if
    negative values are likely.
    """
    TYPE_FIXED64 = 'TYPE_FIXED64'
    TYPE_FIXED32 = 'TYPE_FIXED32'
    TYPE_BOOL = 'TYPE_BOOL'
    TYPE_STRING = 'TYPE_STRING'
    TYPE_GROUP = 'TYPE_GROUP'
    """
    Tag-delimited aggregate.
    Group type is deprecated and not supported after google.protobuf. However, Proto3
    implementations should still be able to parse the group wire format and
    treat group fields as unknown fields.  In Editions, the group wire format
    can be enabled via the `message_encoding` feature.
    """
    TYPE_MESSAGE = 'TYPE_MESSAGE'
    """
    Length-delimited aggregate.
    """
    TYPE_BYTES = 'TYPE_BYTES'
    """
    New in version 2.
    """
    TYPE_UINT32 = 'TYPE_UINT32'
    TYPE_ENUM = 'TYPE_ENUM'
    TYPE_SFIXED32 = 'TYPE_SFIXED32'
    TYPE_SFIXED64 = 'TYPE_SFIXED64'
    TYPE_SINT32 = 'TYPE_SINT32'
    """
    Uses ZigZag encoding.
    """
    TYPE_SINT64 = 'TYPE_SINT64'
    """
    Uses ZigZag encoding.
    """


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    syntax: GoogleProtobufSyntax | None = None
    """
    Referenced top-level standard enum.
    """
    kind: GoogleProtobufFieldKind | None = None
    descriptor_type: GoogleProtobufFieldDescriptorProtoType | None = None
    state: UserState | None = None
    syntaxes: list[GoogleProtobufSyntax] | None = []
