# generated by datamodel-codegen:
#   filename:  user_namespace.proto

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class GoogleProtobufUserState(Enum):
    UNKNOWN = 'UNKNOWN'
    READY = 'READY'


class GoogleProtobufUserChild(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = ''


class GoogleProtobufPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    state: GoogleProtobufUserState | None = 'UNKNOWN'
    child: GoogleProtobufUserChild | None = None
