# generated by datamodel-codegen:
#   filename:  redundant_declared.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Root(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: str
