# generated by datamodel-codegen:
#   filename:  shared.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Shared(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    a: int


class Root(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anchor: Shared | None = None
