# generated by datamodel-codegen:
#   filename:  default_object.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Foo(BaseModel):
    text: str | None = '987'
    number: float | None = None


class Bar(BaseModel):
    foo: Foo | None = Field({'text': 'abc', 'number': 123}, validate_default=True)
    baz: list[Foo] | None = Field(
        [{'text': 'abc', 'number': 123}, {'text': 'efg', 'number': 456}],
        validate_default=True,
    )
