"""Independent Jinja AST-to-Python compiler for project-owned templates.

Only this development-time module imports Jinja.  Generated modules depend on
the small standard-library-only runtime in ``model._compiled_template_runtime``.
"""

from __future__ import annotations

import ast as python_ast
from hashlib import sha256
from json import dumps
from typing import TYPE_CHECKING, Any

from jinja2 import Environment, nodes

if TYPE_CHECKING:
    from pathlib import Path

_RUNTIME_IMPORT_MARKER = "# __standalone_template_runtime_imports__"
_RUNTIME_HELPERS = (
    ("MISSING", "_MISSING"),
    ("Scope", "_Scope"),
    ("concat", "_concat"),
    ("filter_default", "_filter_default"),
    ("filter_indent", "_filter_indent"),
    ("filter_join", "_filter_join"),
    ("filter_length", "_filter_length"),
    ("filter_list", "_filter_list"),
    ("filter_pprint", "_filter_pprint"),
    ("filter_replace", "_filter_replace"),
    ("filter_repr", "_filter_repr"),
    ("filter_selectattr", "_filter_selectattr"),
    ("getattr_", "_getattr"),
    ("getitem", "_getitem"),
    ("is_defined", "_is_defined"),
    ("loop_last_iter", "_loop_last_iter"),
    ("namespace", "_namespace"),
    ("setattr_", "_setattr"),
    ("stringify", "_stringify"),
)


def _runtime_imports(source: str) -> str:
    loaded_names = {
        node.id
        for node in python_ast.walk(python_ast.parse(source))
        if isinstance(node, python_ast.Name) and isinstance(node.ctx, python_ast.Load)
    }
    imports = [f"    {name} as {alias}," for name, alias in _RUNTIME_HELPERS if alias in loaded_names]
    return "\n".join([
        "from datamodel_code_generator.model._compiled_template_runtime import (",
        *imports,
        ")",
    ])


def module_name_for_path(relative_path: Path) -> str:
    """Return a stable, valid Python module name for a template-relative path."""
    stem = relative_path.with_suffix("").as_posix().replace("/", "_").replace("-", "_")
    return "_".join(part.lower() for part in stem.split("_"))


class _Compiler:
    def __init__(self, template_dir: Path, relative_path: Path, ast: nodes.Template) -> None:
        self.template_dir = template_dir
        self.relative_path = relative_path
        self.ast = ast
        self.lines: list[str] = []
        self.indent = 0
        self._counter = 0
        self._macros = {macro.name for macro in ast.body if isinstance(macro, nodes.Macro)}
        self._includes: dict[Path, str] = {}

    def compile(self) -> str:
        source_hash = sha256((self.template_dir / self.relative_path).read_bytes()).hexdigest()[:16]
        self.lines.extend([
            "# Generated by scripts/compile_builtin_templates.py; do not edit directly.",
            f"# Source: {self.relative_path.as_posix()} (sha256:{source_hash})",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            _RUNTIME_IMPORT_MARKER,
            "",
        ])
        for include_path, alias in self._discover_includes().items():
            self.lines.append(f"from .{module_name_for_path(include_path)} import render_with_scope as {alias}")
        if self._includes:
            self.lines.append("")
        self.emit("def render(**context: Any) -> str:")
        with self.block():
            self.emit("return render_with_scope(_Scope(context))")
        self.emit("")
        self.emit("def render_with_scope(_scope: _Scope) -> str:")
        with self.block():
            for macro in self.ast.body:
                if isinstance(macro, nodes.Macro):
                    self._emit_macro(macro)
                    self.emit("")
            names = {name: f"_context_{name}" for name in self._external_names()}
            for name, identifier in names.items():
                self.emit(f"{identifier} = _scope.get({name!r})")
            self.emit("_parts: list[str] = []")
            self._emit_nodes(
                (node for node in self.ast.body if not isinstance(node, nodes.Macro)), "_scope", "_parts", names
            )
            self.emit("return ''.join(_parts)")
        source = "\n".join(self.lines) + "\n"
        return source.replace(_RUNTIME_IMPORT_MARKER, _runtime_imports(source))

    def _external_names(self) -> tuple[str, ...]:
        bound_names: set[str] = set()
        for assignment in self.ast.find_all(nodes.Assign):
            if isinstance(assignment.target, nodes.Name):
                bound_names.add(assignment.target.name)
        for loop in self.ast.find_all(nodes.For):
            bound_names.update(self._target_names(loop.target))
            bound_names.add("loop")
        for macro in self.ast.find_all(nodes.Macro):
            bound_names.update(argument.name for argument in macro.args)
        return tuple(
            sorted({
                name.name
                for name in self.ast.find_all(nodes.Name)
                if name.ctx == "load" and name.name not in bound_names | self._macros | {"namespace"}
            })
        )

    def _discover_includes(self) -> dict[Path, str]:
        for include in self.ast.find_all(nodes.Include):
            if not isinstance(include.template, nodes.Const) or not isinstance(include.template.value, str):
                self._unsupported(include, "only static includes are supported")
            include_path = (
                (self.template_dir / self.relative_path.parent / include.template.value)
                .resolve()
                .relative_to(self.template_dir.resolve())
            )
            if not (self.template_dir / include_path).is_file():
                self._unsupported(include, f"included template {include.template.value!r} does not exist")
            if include_path == self.relative_path:
                self._unsupported(include, "include cycle detected")
            self._includes.setdefault(include_path, f"_include_{len(self._includes)}")
        return self._includes

    def emit(self, line: str) -> None:
        self.lines.append("    " * self.indent + line)

    class _Block:
        def __init__(self, compiler: _Compiler) -> None:
            self.compiler = compiler

        def __enter__(self) -> None:
            self.compiler.indent += 1

        def __exit__(self, *args: object) -> None:
            self.compiler.indent -= 1

    def block(self) -> _Block:
        return self._Block(self)

    def unique(self, prefix: str) -> str:
        value = f"_{prefix}_{self._counter}"
        self._counter += 1
        return value

    def _unsupported(self, node: nodes.Node, message: str) -> None:
        error_message = (
            f"{self.relative_path}:{getattr(node, 'lineno', '?')}: unsupported Jinja construct: {message}; "
            "update the standalone template compiler"
        )
        raise ValueError(error_message)

    def _emit_macro(self, macro: nodes.Macro) -> None:
        if macro.defaults:
            self._unsupported(macro, "macro defaults")
        if (
            getattr(macro, "catch_kwargs", False)
            or getattr(macro, "catch_varargs", False)
            or getattr(macro, "caller", False)
        ):
            self._unsupported(macro, "macro varargs, kwargs, or caller")
        parameters = [arg.name for arg in macro.args]
        signature = ", ".join(["_parent: _Scope", *(f"{name}: Any" for name in parameters)])
        self.emit(f"def _macro_{macro.name}({signature}) -> str:")
        with self.block():
            self.emit("_parts: list[str] = []")
            self._emit_nodes(macro.body, "_parent", "_parts", {parameter: parameter for parameter in parameters})
            self.emit("return ''.join(_parts)")

    def _emit_nodes(self, template_nodes: Any, scope: str, parts: str, names: dict[str, str]) -> None:
        for node in template_nodes:
            match node:
                case nodes.Output():
                    self._emit_output(node, scope, parts, names)
                case nodes.If():
                    self._emit_if(node, scope, parts, names)
                case nodes.For():
                    self._emit_for(node, scope, parts, names)
                case nodes.Assign():
                    self._emit_assign(node, scope, names)
                case nodes.Include():
                    self._emit_include(node, scope, parts, names)
                case nodes.FilterBlock():
                    self._emit_filter_block(node, scope, parts, names)
                case nodes.Macro():
                    # Definitions are emitted before the root body.
                    continue
                case _:
                    self._unsupported(node, type(node).__name__)

    def _emit_output(self, node: nodes.Output, scope: str, parts: str, names: dict[str, str]) -> None:
        static: list[str] = []
        format_segments: list[str] = []
        has_dynamic = False
        for output_node in node.nodes:
            if isinstance(output_node, nodes.TemplateData):
                if output_node.data:
                    static.append(output_node.data)
                    format_segments.append(output_node.data.replace("{", "{{").replace("}", "}}"))
            else:
                has_dynamic = True
                value = self.unique("value")
                self.emit(f"{value} = _stringify({self.expression(output_node, scope, names)})")
                format_segments.append("{" + value + "}")
        if not format_segments:
            return
        if not has_dynamic:
            self.emit(f"{parts}.append({''.join(static)!r})")
            return
        self.emit(f"{parts}.append(f{dumps(''.join(format_segments), ensure_ascii=False)})")

    def _emit_if(self, node: nodes.If, scope: str, parts: str, names: dict[str, str]) -> None:
        self.emit(f"if {self.expression(node.test, scope, names)}:")
        with self.block():
            start = len(self.lines)
            self._emit_nodes(node.body, scope, parts, dict(names))
            if len(self.lines) == start:
                self.emit("pass")
        for elif_node in node.elif_:
            self.emit(f"elif {self.expression(elif_node.test, scope, names)}:")
            with self.block():
                start = len(self.lines)
                self._emit_nodes(elif_node.body, scope, parts, dict(names))
                if len(self.lines) == start:
                    self.emit("pass")
        if node.else_:
            self.emit("else:")
            with self.block():
                start = len(self.lines)
                self._emit_nodes(node.else_, scope, parts, dict(names))
                if len(self.lines) == start:
                    self.emit("pass")

    def _emit_for(self, node: nodes.For, scope: str, parts: str, names: dict[str, str]) -> None:
        if node.test is not None or node.recursive:
            self._unsupported(node, "filtered or recursive for loop")
        loop_last = self._uses_loop_last(node)
        target = self._target_source(node.target)
        iterated = self.unique("iterated") if node.else_ else None
        if iterated is not None:
            self.emit(f"{iterated} = False")
        body_names = dict(names)
        body_names.update({name: name for name in self._target_names(node.target)})
        if loop_last:
            loop_name = self.unique("loop_last")
            body_names["loop"] = loop_name
            self.emit(f"for {target}, {loop_name} in _loop_last_iter({self.expression(node.iter, scope, names)}):")
        else:
            self.emit(f"for {target} in {self.expression(node.iter, scope, names)}:")
        with self.block():
            if iterated is not None:
                self.emit(f"{iterated} = True")
            self._emit_nodes(node.body, scope, parts, body_names)
        if node.else_:
            self.emit(f"if not {iterated}:")
            with self.block():
                self._emit_nodes(node.else_, scope, parts, dict(names))

    def _target_names(self, target: nodes.Expr) -> tuple[str, ...]:
        if isinstance(target, nodes.Name):
            return (target.name,)
        if isinstance(target, nodes.Tuple):
            return tuple(name for item in target.items for name in self._target_names(item))
        self._unsupported(target, f"for target {type(target).__name__}")
        return ()

    def _target_source(self, target: nodes.Expr) -> str:
        if isinstance(target, nodes.Name):
            return target.name
        if isinstance(target, nodes.Tuple):
            return ", ".join(self._target_source(item) for item in target.items)
        self._unsupported(target, f"for target {type(target).__name__}")
        return ""

    @staticmethod
    def _uses_loop_last(node: nodes.For) -> bool:
        return any(
            isinstance(value.node, nodes.Name) and value.node.name == "loop" and value.attr == "last"
            for value in node.find_all(nodes.Getattr)
        )

    def _emit_assign(self, node: nodes.Assign, scope: str, names: dict[str, str]) -> None:
        value = self.expression(node.node, scope, names)
        if isinstance(node.target, nodes.Name):
            names[node.target.name] = node.target.name
            self.emit(f"{node.target.name} = {value}")
            return
        if isinstance(node.target, nodes.NSRef):
            namespace = names.get(node.target.name, f"{scope}.get({node.target.name!r})")
            self.emit(f"_setattr({namespace}, {node.target.attr!r}, {value})")
            return
        self._unsupported(node, f"assignment target {type(node.target).__name__}")

    def _emit_include(self, node: nodes.Include, scope: str, parts: str, names: dict[str, str]) -> None:
        if not isinstance(node.template, nodes.Const) or not isinstance(node.template.value, str):
            self._unsupported(node, "dynamic include")
        include_path = (
            (self.template_dir / self.relative_path.parent / node.template.value)
            .resolve()
            .relative_to(self.template_dir.resolve())
        )
        alias = self._includes.get(include_path)
        if alias is None:
            self._unsupported(node, f"unresolved include {node.template.value!r}")
        if not node.with_context or node.ignore_missing:
            self._unsupported(node, "include without context or with ignore missing")
        include_scope = self.unique("include_scope")
        self.emit(f"{include_scope} = {scope}.child()")
        for name, identifier in names.items():
            if not identifier.startswith("_context_"):
                self.emit(f"{include_scope}.set({name!r}, {identifier})")
        self.emit(f"{parts}.append({alias}({include_scope}))")

    def _emit_filter_block(self, node: nodes.FilterBlock, scope: str, parts: str, names: dict[str, str]) -> None:
        captured = self.unique("captured")
        self.emit(f"{captured}: list[str] = []")
        self._emit_nodes(node.body, scope, captured, dict(names))
        if node.filter.node is not None:
            self._unsupported(node, "filter block with an input expression")
        captured_value = f"''.join({captured})"
        self.emit(f"{parts}.append({self._filter(node.filter, captured_value, scope, names)})")

    def expression(self, node: nodes.Expr, scope: str, names: dict[str, str]) -> str:  # noqa: PLR0911
        match node:
            case nodes.Name():
                name = node.name
                if (local := names.get(name)) is not None:
                    return local
                if name in self._macros:
                    return f"_macro_{name}"
                if name == "namespace":
                    return "_namespace"
                return f"{scope}.get({name!r})"
            case nodes.Const(value=value):
                return repr(value)
            case nodes.List(items=items):
                return "[" + ", ".join(self.expression(item, scope, names) for item in items) + "]"
            case nodes.Tuple(items=items):
                values = ", ".join(self.expression(item, scope, names) for item in items)
                return f"({values}{',' if len(items) == 1 else ''})"
            case nodes.Dict(items=items):
                values = ", ".join(
                    f"{self.expression(item.key, scope, names)}: {self.expression(item.value, scope, names)}"
                    for item in items
                )
                return "{" + values + "}"
            case nodes.Getattr(node=nodes.Name(name="loop"), attr="last") if loop_last := names.get("loop"):
                return loop_last
            case nodes.Getattr(node=value, attr=attr):
                return f"_getattr({self.expression(value, scope, names)}, {attr!r})"
            case nodes.Getitem(node=value, arg=argument):
                return f"_getitem({self.expression(value, scope, names)}, {self.expression(argument, scope, names)})"
            case nodes.Not(node=value):
                return f"(not {self.expression(value, scope, names)})"
            case nodes.And(left=left, right=right):
                return f"({self.expression(left, scope, names)} and {self.expression(right, scope, names)})"
            case nodes.Or(left=left, right=right):
                return f"({self.expression(left, scope, names)} or {self.expression(right, scope, names)})"
            case nodes.Concat(nodes=items):
                return "_concat(" + ", ".join(self.expression(item, scope, names) for item in items) + ")"
            case nodes.Compare(expr=left, ops=operations):
                return self._compare(left, operations, scope, names)
            case nodes.Test():
                return self._test(node, scope, names)
            case nodes.Filter():
                return self._filter(node, self.expression(node.node, scope, names), scope, names)
            case nodes.Call():
                return self._call(node, scope, names)
            case _:
                self._unsupported(node, type(node).__name__)
        error_message = "unreachable"
        raise AssertionError(error_message)

    def _compare(self, left: nodes.Expr, operations: list[nodes.Operand], scope: str, names: dict[str, str]) -> str:
        operators = {
            "eq": "==",
            "ne": "!=",
            "gt": ">",
            "gteq": ">=",
            "lt": "<",
            "lteq": "<=",
            "in": "in",
            "notin": "not in",  # codespell:ignore notin
        }
        result = self.expression(left, scope, names)
        for operation in operations:
            if (operator := operators.get(operation.op)) is None:
                self._unsupported(operation, f"comparison {operation.op}")
            result += f" {operator} {self.expression(operation.expr, scope, names)}"
        return f"({result})"

    def _test(self, node: nodes.Test, scope: str, names: dict[str, str]) -> str:
        if node.args or node.kwargs or node.dyn_args is not None or node.dyn_kwargs is not None:
            self._unsupported(node, f"test arguments for {node.name}")
        value = self.expression(node.node, scope, names)
        match node.name:
            case "defined":
                return f"_is_defined({value})"
            case "none":
                return f"({value} is None)"
            case "false":
                return f"({value} is False)"
            case _:
                self._unsupported(node, f"test {node.name}")
        error_message = "unreachable"
        raise AssertionError(error_message)

    def _filter(self, node: nodes.Filter, value: str, scope: str, names: dict[str, str]) -> str:  # noqa: PLR0911
        if node.dyn_args is not None or node.dyn_kwargs is not None:
            self._unsupported(node, f"dynamic filter arguments for {node.name}")
        arguments = [self.expression(argument, scope, names) for argument in node.args]
        if node.kwargs:
            arguments.extend(f"{keyword.key}={self.expression(keyword.value, scope, names)}" for keyword in node.kwargs)
        match node.name:
            case "default":
                return f"_filter_default({', '.join([value, *arguments])})"
            case "indent":
                return f"_filter_indent({', '.join([value, *arguments])})"
            case "join":
                return f"_filter_join({', '.join([value, *arguments])})"
            case "length":
                if arguments:
                    self._unsupported(node, "length filter arguments")
                return f"_filter_length({value})"
            case "list":
                if arguments:
                    self._unsupported(node, "list filter arguments")
                return f"_filter_list({value})"
            case "pprint":
                if arguments:
                    self._unsupported(node, "pprint filter arguments")
                return f"_filter_pprint({value})"
            case "replace":
                return f"_filter_replace({', '.join([value, *arguments])})"
            case "repr":
                if arguments:
                    self._unsupported(node, "repr filter arguments")
                return f"_filter_repr({value})"
            case "selectattr":
                return f"_filter_selectattr({', '.join([value, *arguments])})"
            case _:
                self._unsupported(node, f"filter {node.name}")
        error_message = "unreachable"
        raise AssertionError(error_message)

    def _call(self, node: nodes.Call, scope: str, names: dict[str, str]) -> str:
        if node.dyn_args is not None or node.dyn_kwargs is not None:
            self._unsupported(node, "dynamic call arguments")
        arguments = [self.expression(argument, scope, names) for argument in node.args]
        arguments.extend(f"{keyword.key}={self.expression(keyword.value, scope, names)}" for keyword in node.kwargs)
        target = self.expression(node.node, scope, names)
        if isinstance(node.node, nodes.Name) and node.node.name in self._macros:
            target = f"_macro_{node.node.name}({scope}"
            return target + (", " + ", ".join(arguments) if arguments else "") + ")"
        return f"{target}({', '.join(arguments)})"


def compile_template(template_dir: Path, relative_path: Path, environment: Environment) -> str:
    """Compile one template source to deterministic Python source."""
    source = (template_dir / relative_path).read_text(encoding="utf-8")
    ast = environment.parse(source)
    return _Compiler(template_dir, relative_path, ast).compile()
