# generated by datamodel-codegen:
#   filename:  all_exports_collision_success.yaml

from __future__ import annotations

from pydantic import BaseModel


class Message(BaseModel):
    result: str | None = None
