# generated by datamodel-codegen:
#   filename:  dot_notation_root_package_inheritance.yaml

from __future__ import annotations

from pydantic import BaseModel


class Animal(BaseModel):
    species: str | None = None
