# generated by datamodel-codegen:
#   filename:  circular_imports_with_inheritance.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from ._internal import BaseEntity, RootModel

__all__ = ["BaseEntity", "RootModel"]
