# generated by datamodel-codegen:
#   filename:  force_optional_with_const.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel
from typing_extensions import Literal


class ForceOptionalWithConst(BaseModel):
    foo: Literal["foo"] = "foo"
