# generated by datamodel-codegen:
#   filename:  relative_parent_import.json

from __future__ import annotations

from pydantic import BaseModel


class Shared(BaseModel):
    right_value: int | None = None
