# generated by datamodel-codegen:
#   filename:  schema_1.json

from __future__ import annotations

from pydantic import BaseModel

from .outer import Outer


class Root1(BaseModel):
    data1: Outer | None = None
    next: Root1 | None = None


Root1.model_rebuild()
