# generated by datamodel-codegen:
#   filename:  multiple.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

Root = RootModel[Annotated[int, Field(..., ge=3, le=8, title='Root')]]


from typing import Annotated

First = RootModel[Annotated[int, Field(..., ge=3, le=8)]]


from typing import Annotated

Second = RootModel[Annotated[int, Field(..., ge=3, le=8)]]
