# generated by datamodel-codegen:
#   filename:  nonunique.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[list[int]]):
    root: list[int] = Field(..., title='Root')
