# generated by datamodel-codegen:
#   filename:  plain.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class Root(RootModel[str]):
    root: Annotated[
        str, Field(description='An ordinary root alias.', title='Root')
    ] = 'kept'
