# generated by datamodel-codegen:
#   filename:  anyof.json

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import BaseModel, Field, RootModel, model_validator


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_one_of_required_groups__: ClassVar[tuple[Any, ...]] = ()
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_required_groups(
            data,
            required_group_rules=cls.__json_schema_one_of_required_groups__,
            require_exactly_one=True,
        )
        data = cls._validate_json_schema_required_groups(
            data,
            required_group_rules=cls.__json_schema_any_of_required_groups__,
            require_exactly_one=False,
        )
        return data

    @classmethod
    def _validate_json_schema_required_groups(
        cls,
        data: Any,
        *,
        required_group_rules: tuple[Any, ...],
        require_exactly_one: bool,
    ) -> Any:
        if not required_group_rules or not isinstance(data, dict):
            return data
        for required_groups in required_group_rules:
            matches = sum(
                all(any(name in data for name in names) for names in group)
                for group in required_groups
            )
            if require_exactly_one:
                if matches != 1:
                    raise ValueError(
                        'Expected exactly one required property group to be present'
                    )
            elif matches == 0:
                raise ValueError(
                    'Expected at least one required property group to be present'
                )
        return data


class Root1(BaseModel):
    mode: str | None = None
    a_name: str = Field(..., alias='a-name')
    b: str | None = None


class Root2(BaseModel):
    mode: str | None = None
    a_name: str | None = Field(None, alias='a-name')
    b: str


class Parent(BaseModel):
    p: str | None = None


class Root3(_JsonSchemaRuntimeValidationBase, Parent):
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('a-name',),), (('b',),)),
    )

    mode: str | None = None
    a_name: str | None = Field(None, alias='a-name')
    b: str | None = None


class Root4(Root1, Root3):
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('a-name',),), (('b',),)),
    )


class Root5(Root2, Root3):
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('a-name',),), (('b',),)),
    )


class Root(RootModel[Root4 | Root5]):
    root: Root4 | Root5 = Field(..., title='Root')
