# generated by datamodel-codegen:
#   filename:  modular.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict

from typing_extensions import TypeAliasType

from . import models

Pets = TypeAliasType("Pets", List[models.Pet])


Users = TypeAliasType("Users", List[models.User])


Rules = TypeAliasType("Rules", List[str])


class Api(TypedDict):
    apiKey: NotRequired[str]
    apiVersionNumber: NotRequired[str]
    apiUrl: NotRequired[str]
    apiDocumentationUrl: NotRequired[str]
    stage: NotRequired[Literal['test', 'dev', 'stg', 'prod']]


Apis = TypeAliasType("Apis", List[Api])
