# generated by datamodel-codegen:
#   filename:  modular.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict

from . import models

Pets: TypeAlias = list[models.Pet]


Users: TypeAlias = list[models.User]


Rules: TypeAlias = list[str]


class Api(TypedDict):
    apiKey: NotRequired[str]
    apiVersionNumber: NotRequired[str]
    apiUrl: NotRequired[str]
    apiDocumentationUrl: NotRequired[str]
    stage: NotRequired[Literal['test', 'dev', 'stg', 'prod']]


Apis: TypeAlias = list[Api]
