"""Shared fixtures for XML Schema tests."""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.conftest import create_assert_file_content
from tests.main.conftest import EXPECTED_XML_SCHEMA_PATH

assert_file_content = create_assert_file_content(EXPECTED_XML_SCHEMA_PATH)

XMLSCHEMA_SNIPPETS: dict[str, tuple[str, ...]] = {
    "constructs_matrix": (
        "class IncludedCode(RootModel[constr(pattern=r'[A-Z]+', min_length=3, max_length=3)]):",
        "class TokenList(RootModel[list[str]]):",
        "class InlineTokenList(RootModel[list[InlineTokenListEnum]]):",
        "class BooleanFacet(Enum):",
        "class ArrayFacet(RootModel[list[str]]):",
        "class BaseType(BaseModel):",
        "sharedElement: list[SharedElement | None] | None = Field(None, max_length=2)",
        "left: str | None = None",
        "fromGroup: str | None = None",
        "localNumber: conint(ge=-2147483648, le=2147483647) | None = 1",
        "inlineAttribute: constr(max_length=8) | None = None",
        "globalFlag: Literal[True]",
        "emptyDefault: str | None = ''",
        "class ExtendedType(BaseType):",
        "extra: list[str] | None = Field(None, max_length=3)",
        "class RestrictedType(BaseModel):",
        "only: str",
        "class FallbackContent(BaseModel):",
        "class Amount(BaseModel):",
        "value: conint(ge=1, le=2147483647)",
        "unit: str | None = None",
        "class InlineRestrictedText(BaseModel):",
        "value: constr(min_length=2, max_length=6)",
        "code: str",
        "class TextWithAttrs(BaseModel):",
        "kind: Literal['plain'] = 'plain'",
        "emptyFixed: Literal[''] = ''",
        "first: ExtendedType",
        "inlineRestrictedText: InlineRestrictedText",
        "class Second(BaseModel):",
        "inlineChild: constr(min_length=2)",
    ),
    "edge_cases": (
        "class EmptyRestriction(RootModel[str]):",
        "class NotAPythonType(RootModel[str]):",
        "class SelfRestricted(RootModel[constr(pattern=r'[A-Z]+')]):",
        "class NoSimpleChild(BaseModel):",
        "value: str",
        "class Loose(BaseModel):",
        "inlineGroupElement: Literal['v'] = Field(",
        "not_a_python_name: str",
        "optionalGrouped: str | None = None",
        "badGrouped: list[str] = Field(..., max_length=2)",
        "unboundedItem: list[str] | None = None",
        "badOccurs: list[str]",
        "empty: Any",
        "unknownNamespace: Any",
        "localGrouped: str | None = Field(None, description='Grouped attr')",
        "plain: str",
        "loose: Loose",
        "selfRestricted: SelfRestricted",
    ),
    "single_root_item": (
        "class Item(BaseModel):",
        "name: str",
    ),
    "inline_root": (
        "class InlineRoot(BaseModel):",
        "value: str",
    ),
    "recursive_node": (
        "class Node(BaseModel):",
        "child: Node | None = None",
    ),
    "import_namespace": (
        "class ImportedCode(RootModel[constr(min_length=5, max_length=5)]):",
        "class Code(BaseModel):",
    ),
    "namespace_collisions": (
        "class HttpsExampleComBillingAddress(BaseModel):",
        "class HttpsExampleComCommonBillingCode(RootModel[constr(max_length=4)]):",
        "class HttpsExampleComShippingAddress(BaseModel):",
        "class HttpsExampleComCommonShippingCode(RootModel[constr(min_length=2)]):",
        "class UrnABThing(RootModel[str]):",
        "class UrnABThing2(RootModel[str]):",
        "shipping: HttpsExampleComShippingAddress",
        "billing: HttpsExampleComBillingAddress",
    ),
    "no_namespace_collision": (
        "class HttpsExampleComExternalCode(RootModel[str]):",
        "class NoNamespaceCode(RootModel[str]):",
        "localCode: NoNamespaceCode",
        "externalCode: HttpsExampleComExternalCode",
    ),
    "namespace_fallback": (
        "class LocalThing(BaseModel):",
        "value: str",
        "class SharedType(BaseModel):",
        "name: str",
        "class SharedElement(RootModel[LocalThing]):",
        "root: LocalThing = Field(..., title='SharedElement')",
        "class Holder(BaseModel):",
        "Shared: SharedElement",
    ),
    "advanced_constructs": (
        "class Cat(Animal):",
        "lives: conint(ge=1)",
        "class Dog(Animal):",
        "breed: str",
        "class Vehicle(BaseModel):",
        "vin: str",
        "class Car(Vehicle):",
        "doors: conint(ge=1)",
        "class Paragraph(BaseModel):",
        "value: str | None = None",
        "emphasis: list[str] | None = None",
        "lang: str | None = None",
        "class Zoo(BaseModel):",
        "animal: list[Cat | Dog]",
        "vehicle: Vehicle | Car | None = None",
        "description: Paragraph | None = None",
    ),
    "multiple_substitution_groups": (
        "class ConcreteThing(BaseThing):",
        "label: str",
        "class Document(BaseModel):",
        "thing: ConcreteThing",
        "namedThing: ConcreteThing | None = None",
    ),
    "include_local_elements": (
        "class Model(BaseModel):",
        "included: conint(ge=-2147483648, le=2147483647)",
        "main: str",
    ),
    "type_element_symbol_spaces": (
        "class ItemType(BaseModel):",
        "value: str",
        "class ItemElement(BaseModel):",
        "code: conint(ge=-2147483648, le=2147483647)",
        "class Document(BaseModel):",
        "typed: ItemType",
        "Item: ItemElement",
    ),
    "versioning": (
        "class Versioned(BaseModel):",
        "modern: str",
        "invalidVersion: str",
    ),
    "versioning_xsd10": (
        "class Versioned(BaseModel):",
        "legacy: str",
        "invalidVersion: str",
    ),
    "versioning_include": (
        "class VersionedInclude(BaseModel):",
        "modern: str",
    ),
    "versioning_include_xsd10": (
        "class VersionedInclude(BaseModel):",
        "legacy: str",
    ),
    "model_groups_and_wildcards": (
        "class SearchToken(RootModel[str | conint(ge=-2147483648, le=2147483647)]):",
        "class EventLog(BaseModel):",
        "extra='allow'",
        "message: list[str | None] | None = None",
        "count: list[Literal[1]] | None = None",
        "segment: list[str] = Field(..., max_length=12, min_length=4)",
        "tag: list[str] | None = Field(None, max_length=6, min_length=1)",
        "status: str | None = 'open'",
        "kind: Literal['audit']",
        "search: SearchToken | None = None",
        "inlineSearch: str | conint(ge=-2147483648, le=2147483647) | None = None",
    ),
    "spec_constructs": (
        "from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr",
        "class IdList(RootModel[list[str]]):",
        "class StampRange(RootModel[AwareDatetime]):",
        "class StampInclusiveRange(RootModel[AwareDatetime]):",
        "class AllParticleType(BaseModel):",
        "first: str",
        "maybe: conint(ge=-2147483648, le=2147483647) | None = None",
        "class RestrictedAllType(BaseModel):",
        "restrictedAttr: Literal[False] = False",
        "class AnonymousComplex(BaseModel):",
        "value: float",
        "flag: bool | None = True",
        "class TextWithLanguage(BaseModel):",
        "value: str",
        "lang: str",
        "globalCode: Literal['fixedCode'] = 'fixedCode'",
        "class ScopedTypes(BaseModel):",
        "anonymousSimple: constr(pattern=r'[a-z]{2}')",
        "anonymousComplex: AnonymousComplex",
        "text: TextWithLanguage",
        "ids: IdList | None = None",
        "stamp: StampRange | None = None",
        "inclusiveStamp: StampInclusiveRange | None = None",
        "class Catalog(BaseModel):",
        "scoped: ScopedTypes",
        "allParticle: AllParticleType | None = None",
        "restrictedAll: RestrictedAllType | None = None",
        "globalCode: str",
    ),
    "schema_composition": (
        "class ChameleonType(BaseModel):",
        "chameleonValue: str",
        "class RedefinedCode(RootModel[constr(min_length=4)]):",
        "class OverriddenType(BaseModel):",
        "newValue: str",
        "class Container(BaseModel):",
        "chameleon: ChameleonType",
        "code: RedefinedCode",
        "newGroupElement: str",
        "overrideValue: OverriddenType",
        "newAttr: conint(ge=-2147483648, le=2147483647) | None = None",
    ),
    "xsd11_constructs": (
        "class DefaultOpen(BaseModel):",
        "extra='allow'",
        "known: str",
        "class EmptyDefaultClosed(BaseModel):",
        "pass",
        "class ClosedOpen(BaseModel):",
        "closedKnown: str",
        "class ExplicitOpen(BaseModel):",
        "explicitKnown: str",
        "class AlphaPayload(BaseModel):",
        "alpha: str",
        "class BetaPayload(BaseModel):",
        "beta: conint(ge=-2147483648, le=2147483647)",
        "class InlineSimpleAlternative(Enum):",
        "inline = 'inline'",
        "class InlineComplexAlternative(BaseModel):",
        "inlineComplexValue: str",
        "class Document(BaseModel):",
        "defaultOpen: DefaultOpen",
        "emptyDefaultClosed: EmptyDefaultClosed",
        "closedOpen: ClosedOpen",
        "explicitOpen: ExplicitOpen",
        "payload: AlphaPayload | BetaPayload",
        "typedAlternative: AlphaPayload | str",
        "inlineSimpleAlternative: InlineSimpleAlternative",
        "inlineComplexAlternative: InlineComplexAlternative",
        "emptyAlternative: Any",
    ),
    "default_open_content_applies_to_empty": (
        "class EmptyDefaultOpen(BaseModel):",
        "extra='allow'",
        "class Container(BaseModel):",
        "empty: EmptyDefaultOpen",
    ),
    "datatypes_and_mixed_content": (
        "from datetime import timedelta",
        "from pydantic import AnyUrl, AwareDatetime, BaseModel",
        "class DatatypeSample(BaseModel):",
        "notation: str | None = None",
        "timestamp: AwareDatetime",
        "yearMonth: timedelta | None = None",
        "dayTime: timedelta | None = None",
        "atomic: Any | None = None",
        "class ParagraphBase(BaseModel):",
        "emphasis: list[str] | None = None",
        "class MixedExtension(ParagraphBase):",
        "link: AnyUrl | None = None",
        "value: str | None = None",
        "class Sample(BaseModel):",
        "content: MixedExtension",
        "datatypes: DatatypeSample",
    ),
}

XMLSCHEMA_ABSENT_SNIPPETS: dict[str, tuple[str, ...]] = {
    "constructs_matrix": (
        "class BlockedGroup",
        "blockedElement",
        "blockedGroupElement",
        "blockedParticleElement",
        "class GlobalFlag",
        "class NamedAttributes",
        "class NamedGroup",
    ),
    "schema_composition": (
        "oldGroupElement",
        "oldAttr",
        "oldValue",
        "class HttpsExampleComSchemaCompositionChameleonType",
    ),
    "xsd11_constructs": (
        "class ClosedOpen(BaseModel):\n    model_config",
        "class EmptyDefaultClosed(BaseModel):\n    model_config",
    ),
    "versioning": ("legacy: str",),
    "versioning_xsd10": ("modern: str",),
    "versioning_include": ("legacy: str",),
    "versioning_include_xsd10": ("modern: str",),
}


def assert_xmlschema_snippets(
    output_file: Path,
    expected_name: str | Path | None = None,
    encoding: str = "utf-8",
    transform: object = None,
) -> None:
    """Assert generated XML Schema output contains the snippets for a fixture."""
    __tracebackhide__ = True
    assert transform is None
    if expected_name is None:  # pragma: no cover
        pytest.fail("expected_name is required for XML Schema snippet assertions")
    content = output_file.read_text(encoding=encoding)
    key = Path(expected_name).stem
    expected_snippets = XMLSCHEMA_SNIPPETS.get(key)
    if expected_snippets is None:  # pragma: no cover
        pytest.fail(f"Unknown XML Schema snippet fixture: {expected_name}")
    missing = [snippet for snippet in expected_snippets if snippet not in content]
    if missing:  # pragma: no cover
        pytest.fail("Generated XML Schema output is missing snippets:\n" + "\n\n".join(missing))
    unexpected = [snippet for snippet in XMLSCHEMA_ABSENT_SNIPPETS.get(key, ()) if snippet in content]
    if unexpected:  # pragma: no cover
        pytest.fail("Generated XML Schema output contains unexpected snippets:\n" + "\n\n".join(unexpected))
