# generated by datamodel-codegen:
#   filename:  root_type_union.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel


class Model(RootModel[str | None]):
    root: str | None = Field(..., description='Nullable root', title='Model')
