# generated by datamodel-codegen:
#   filename:  classvar.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Item:
    value: int


@dataclass
class Root:
    item: Item | None = None
