# generated by datamodel-codegen:
#   filename:  classvar.json

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class Item(Struct):
    pass


class Root(Struct):
    item: Item | UnsetType = field(default_factory=Item)
