# generated by datamodel-codegen:
#   filename:  normal.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Item(BaseModel):
    value: int | None = 4


class Root(BaseModel):
    item: Item | None = Field(default_factory=Item)
