# generated by datamodel-codegen:
#   filename:  normal.json

from __future__ import annotations

from typing import final

from pydantic import BaseModel, Field


@final
class Item(BaseModel):
    value: int | None = 4


@final
class Root(BaseModel):
    item: Item | None = Field(default_factory=Item)
