# generated by datamodel-codegen:
#   filename:  default_required.json

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class Item(Struct):
    value: int = 3


class Root(Struct):
    item: Item | UnsetType = field(default_factory=Item)
