# generated by datamodel-codegen:
#   filename:  inherited.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Base:
    value: int


@dataclass
class Item(Base):
    pass


@dataclass
class Root:
    item: Item | None = None
