# generated by datamodel-codegen:
#   filename:  normal.json

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class Item(Struct):
    value: int | UnsetType = 4


class Root(Struct):
    item: Item | UnsetType = field(default_factory=Item)
