# generated by datamodel-codegen:
#   filename:  normal.json

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Item:
    value: int | None = 4


@dataclass
class Root:
    item: Item | None = Field(default_factory=Item)
