# generated by datamodel-codegen:
#   filename:  null_default.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Item(BaseModel):
    value: int | None = None


class Root(BaseModel):
    item: Item | None = Field(default_factory=Item)
