# generated by datamodel-codegen:
#   filename:  override_before_base.json

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Base:
    value: int


@dataclass
class Item(Base):
    value: int = 11


@dataclass
class Root:
    item: Item | None = Field(default_factory=Item)
