# generated by datamodel-codegen:
#   filename:  override_before_base.json

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Base:
    value: int


@dataclass
class Item(Base):
    value: int = 11


@dataclass
class Root:
    item: Item | None = field(default_factory=Item)
