# generated by datamodel-codegen:
#   filename:  override_before_base.json

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class Base(Struct):
    value: int


class Item(Base):
    value: int = 11


class Root(Struct):
    item: Item | UnsetType = field(default_factory=Item)
