# generated by datamodel-codegen:
#   filename:  required.json

from __future__ import annotations

from pydantic.dataclasses import dataclass


@dataclass
class Item:
    value: int


@dataclass
class Root:
    item: Item | None = None
