# generated by datamodel-codegen:
#   filename:  reused.json

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType


class Item(Struct):
    value: int


class Duplicate(Item):
    pass


class Root(Struct):
    item: Item | UnsetType = UNSET
    other: Duplicate | UnsetType = UNSET
