# generated by datamodel-codegen:
#   filename:  untyped_null_default.json

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Item:
    value: int = None


@dataclass
class Root:
    item: Item | None = Field(default_factory=Item)
