# generated by datamodel-codegen:
#   filename:  alias.yaml
#   timestamp: 2025-03-26T15:01:47+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .. import Source, fo_o


@dataclass(frozen=True, slots=True, keyword_only=True)
class ChocolatE:
    flavour_name: Optional[str] = None
    sourc_e: Optional[Source] = None
    coco_a: Optional[fo_o.CocoA] = None
