# generated by datamodel-codegen:
#   filename:  _internal

from __future__ import annotations

from pydantic import BaseModel


class Node(BaseModel):
    b: Node_1 | None = None


class Node_1(BaseModel):
    a: Node | None = None


Node.model_rebuild()
