# generated by datamodel-codegen:
#   filename:  root_type_object.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from uuid import UUID

from pydantic import Field, RootModel


class Model(RootModel[UUID]):
    root: UUID = Field(..., title='Model')
