# generated by datamodel-codegen:
#   filename:  second.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class Second(RootModel[int]):
    root: int


class Model(BaseModel):
    second: Second | None = None
