# generated by datamodel-codegen:
#   filename:  first.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class First(RootModel[str]):
    root: str


class Model(BaseModel):
    first: First | None = None
