# generated by datamodel-codegen:
#   filename:  spec_matrix.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from datetime import timedelta
from decimal import Decimal
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field, RootModel, conbytes


class DefaultRecord(BaseModel):
    value: int = 1


class DefaultEnum(StrEnum):
    FOO = 'FOO'
    BAR = 'BAR'


class DefaultFixed(RootModel[conbytes(min_length=1, max_length=1)]):
    root: conbytes(min_length=1, max_length=1) = Field(..., title='DefaultFixed')


class RA(BaseModel):
    a: str


class RB(BaseModel):
    b: str


class EA(StrEnum):
    A = 'A'


class EB(StrEnum):
    B = 'B'


class FA(RootModel[conbytes(min_length=4, max_length=4)]):
    root: conbytes(min_length=4, max_length=4) = Field(..., title='FA')


class FB(RootModel[conbytes(min_length=8, max_length=8)]):
    root: conbytes(min_length=8, max_length=8) = Field(..., title='FB')


class ArrayItem(BaseModel):
    label: str


class MapValue(StrEnum):
    ONE = 'ONE'
    TWO = 'TWO'


class EmptyNamespaceFixed(RootModel[conbytes(min_length=2, max_length=2)]):
    root: conbytes(min_length=2, max_length=2) = Field(..., title='EmptyNamespaceFixed')


class Understanding(StrEnum):
    YES = 'YES'
    NO = 'NO'


class Name(BaseModel):
    understanding: Understanding
    understandingRef: Understanding


class Array(BaseModel):
    value: str


class DefaultUuid(RootModel[UUID]):
    root: UUID = Field(..., title='DefaultUuid')


class DefaultDuration(RootModel[timedelta]):
    root: timedelta = Field(..., title='DefaultDuration')


class SpecMatrix(BaseModel):
    nullDefault: None = None
    booleanDefault: bool = False
    intDefault: int = 1
    longDefault: int = 2
    floatDefault: float = 1.5
    doubleDefault: float = 2.5
    bytesDefault: bytes = b'\xff'
    stringDefault: str = 'foo'
    recordDefault: DefaultRecord = Field({'value': 1}, validate_default=True)
    enumDefault: DefaultEnum = DefaultEnum.FOO
    arrayDefault: list[int] = [1]
    mapDefault: dict[str, int] = {'a': 1}
    fixedDefault: DefaultFixed = Field(b'\xff', validate_default=True)
    ascendingOrder: str
    descendingOrder: str
    nullableAfterValue: str | None = 'value'
    sameKindNamedUnion: RA | RB | EA | EB | FA | FB
    arrayOfRecords: list[ArrayItem]
    mapOfEnums: dict[str, MapValue]
    emptyNamespace: EmptyNamespaceFixed
    fullnameIgnoresNamespace: Name
    fullnameReference: Name
    complexTypeNameReuse: Array
    unknownLogicalType: int
    precisionOnlyDecimal: Decimal
    logicalDecimalDefault: Decimal = Decimal('12.34')
    logicalFixedUuidDefault: DefaultUuid = Field(
        UUID('00112233-4455-6677-8899-aabbccddeeff'), validate_default=True
    )
    logicalDurationDefault: DefaultDuration = Field(
        timedelta(days=2, milliseconds=3000), validate_default=True
    )
