# generated by datamodel-codegen:
#   filename:  dot_notation_inheritance.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from . import Animal


class Dog(Animal):
    breed: str | None = None
