# generated by datamodel-codegen:
#   filename:  mixed.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class Value(RootModel[int]):
    root: int


class Root(BaseModel):
    value: Value | None = None
