# generated by datamodel-codegen:
#   filename:  allof_required_inherited_dataclass_metadata.yaml

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType, field


class InitBase(Struct):
    inheritedScalar: Annotated[str, Meta(min_length=2)] | UnsetType = 'inherited'
    inheritedFactory: list[str] | UnsetType = field(default_factory=list)
    inheritedMetadata: str | UnsetType = UNSET


class RequiredOverrideChild(InitBase):
    inheritedScalar: Annotated[str, Meta(min_length=2)]
    inheritedFactory: list[str]
    inheritedMetadata: str
    newRequired: int


class ExplicitInitBase(Struct):
    explicitInit: str | UnsetType = 'inherited'


class ExplicitInitChild(ExplicitInitBase):
    explicitInit: str
    newAfterExplicitInit: int


class InheritedInitDefaultChild(InitBase, kw_only=True):
    newAfterInheritedInit: int


class RequiredAliasBase(Struct):
    aliased_value: str = field(name='aliased-value')


class RequiredAliasChild(RequiredAliasBase):
    newAfterAlias: int


class RequiredMetadataBase(Struct):
    requiredMetadata: str


class RequiredMetadataChild(RequiredMetadataBase):
    requiredMetadata: str
    newAfterMetadata: int


class KeywordOverrideBase(Struct):
    retainedDefault: str | UnsetType = 'retained'
    positionalOverride: str | UnsetType = 'inherited'


class KeywordOverrideChild(KeywordOverrideBase, kw_only=True):
    positionalOverride: str


class OrderingBase(Struct):
    earlyFactory: list[str] | UnsetType = field(default_factory=list)
    priorDefault: str | UnsetType = 'inherited'
    lateFactory: list[str] | UnsetType = field(default_factory=list)


class OrderingChild(OrderingBase, kw_only=True):
    earlyFactory: list[str]
    lateFactory: list[str]
    newRequired: int


class LiteralDefaultBase(Struct):
    literalDefault: str | UnsetType = 'contains default_factory= marker'


class LiteralDefaultChild(LiteralDefaultBase):
    literalDefault: str
    afterLiteral: int
