# generated by datamodel-codegen:
#   filename:  allof_no_merge_backend_types.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypeAlias, TypedDict

ScalarValue: TypeAlias = str


ScalarArray: TypeAlias = list[ScalarValue]


ScalarMapping: TypeAlias = dict[str, ScalarValue]


class Base(TypedDict):
    direct: ScalarValue
    inline: str
    array: list[ScalarValue]
    mapping: dict[str, ScalarValue]
    deep: list[list[ScalarValue]]
    arrayRoot: ScalarArray
    mappingRoot: ScalarMapping


class Child(Base):
    direct: str
    inline: str
    array: list[str]
    mapping: dict[str, str]
    deep: list[list[str]]
    arrayRoot: list[ScalarValue]
    mappingRoot: dict[str, ScalarValue]
