# generated by datamodel-codegen:
#   filename:  dotted_module_exports_collision

from __future__ import annotations

from .api.v1.user.user import User as ApiV1UserUserUser
from .api.v2.user.user import User as ApiV2UserUserUser

__all__ = [
    "ApiV1UserUserUser",
    "ApiV2UserUserUser",
]
