# generated by datamodel-codegen:
#   filename:  sequence_None_None.xsd

from __future__ import annotations

from pydantic import BaseModel


class Root(BaseModel):
    value: str
    marker: str | None = 'kept'
    """
    Marker order control
    """
