# generated by datamodel-codegen:
#   filename:  sequence_unbounded_unbounded.xsd

from __future__ import annotations

from pydantic import BaseModel, Field


class Root(BaseModel):
    value: list[str] = Field(..., min_length=1)
    marker: str | None = 'kept'
    """
    Marker order control
    """
