# generated by datamodel-codegen:
#   filename:  reuse_scope_tree_enum_discriminator
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from . import PetBase as PetBase_2
from .shared import Lizard as Lizard_1
from .shared import Pet as Pet_1
from .shared import PetBase as PetBase_1

PetBase = PetBase_1


class Cat(PetBase_2):
    cat_name: str


Lizard = Lizard_1


class Pet(Pet_1):
    pass
