# generated by datamodel-codegen:
#   filename:  modular.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import NotRequired, TypedDict

from .. import bar
from .._internal import Cocoa, Source


class Chocolate(TypedDict):
    flavour: NotRequired[str]
    source: NotRequired[Source]
    cocoa: NotRequired[Cocoa]
    field: NotRequired[bar.Field]
