# generated by datamodel-codegen:
#   filename:  parameter_field_policy.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Nested:
    value: str | None = None


@dataclass
class Defaulted:
    nested: Nested | None = Field(
        default_factory=lambda: {'value': 'preset'}, validate_default=True
    )


@dataclass
class ContentNested:
    value: str | None = None


@dataclass
class ContentMulti:
    value: str | None = None


@dataclass
class ListItemsParametersQuery:
    schema_nested: Nested | None = Field(default_factory=Nested)
    content_nested: ContentNested | None = Field(default_factory=ContentNested)
    schema_read_only: str | None = Field(None, frozen=True)
    content_read_only: str | None = Field(None, frozen=True)
    schema_write_only: str | None = None
    content_write_only: str | None = None
    content_array: list[str] | None = Field(None, min_length=1)
    content_multi: ContentMulti | str | None = Field(default_factory=ContentMulti)
