# generated by datamodel-codegen:
#   filename:  parameter_field_policy.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired, ReadOnly


class Nested(TypedDict):
    value: NotRequired[str]


class Defaulted(TypedDict):
    nested: NotRequired[Nested]


class ContentNested(TypedDict):
    value: NotRequired[str]


class ContentMulti(TypedDict):
    value: NotRequired[str]


class ListItemsParametersQuery(TypedDict):
    schema_nested: NotRequired[Nested]
    content_nested: NotRequired[ContentNested]
    schema_read_only: NotRequired[ReadOnly[str]]
    content_read_only: NotRequired[ReadOnly[str]]
    schema_write_only: NotRequired[str]
    content_write_only: NotRequired[str]
    content_array: NotRequired[list[str]]
    content_multi: NotRequired[ContentMulti | str]
