"""Build hand-written documentation examples from tested fixtures."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable

ROOT = Path(__file__).parent.parent
DOCS = ROOT / "docs"
TEST_DATA = ROOT / "tests" / "data"
EXPECTED_MAIN = TEST_DATA / "expected" / "main"

BEGIN_MARKER_TEMPLATE = "<!-- BEGIN AUTO-GENERATED DOC EXAMPLE: {example_id} -->"
END_MARKER_TEMPLATE = "<!-- END AUTO-GENERATED DOC EXAMPLE: {example_id} -->"

PYTHON_GENERATED_HEADER_PATTERN = re.compile(
    r"\A# generated by datamodel-codegen:\n"
    r"#   filename:  .+\n"
    r"(?:#   timestamp:\s+.+\n)?"
    r"\n",
)


@dataclass(frozen=True, slots=True)
class DocsExample:
    """One generated docs example section."""

    example_id: str
    path: Path
    render: Callable[[], str]


def read_text(path: Path) -> str:
    """Read a UTF-8 fixture file."""
    return path.read_text(encoding="utf-8").rstrip()


def read_python_output(path: Path) -> str:
    """Read generated Python output without volatile generated-file headers."""
    return PYTHON_GENERATED_HEADER_PATTERN.sub("", read_text(path), count=1)


def fenced(language: str, content: str) -> str:
    """Render a Markdown fenced code block."""
    return f"\n```{language}\n{content.rstrip()}\n```\n"


def details(summary: str, language: str, content: str) -> str:
    """Render a collapsible Markdown details block containing a code fence."""
    return f"\n<details>\n<summary>{summary}</summary>\n{fenced(language, content)}</details>\n"


def render_file_example(*, language: str, path: Path, strip_python_header: bool = False) -> str:
    """Render one fixture file as a Markdown code block."""
    content = read_python_output(path) if strip_python_header else read_text(path)
    return fenced(language, content)


def directory_tree(path: Path, *, root_name: str) -> str:
    """Render a stable text tree for generated directory examples."""
    lines = [f"{root_name}/"]
    files = sorted(file for file in path.iterdir() if file.is_file())
    for index, file in enumerate(files):
        branch = "`--" if index == len(files) - 1 else "|--"
        lines.append(f"{branch} {file.name}")
    return "\n".join(lines)


def render_reuse_scope_tree_example() -> str:
    """Render tested reuse-scope tree output with representative files."""
    output_path = EXPECTED_MAIN / "jsonschema" / "reuse_scope_tree"
    lines = [
        "",
        "**Output with `--reuse-scope tree`:**",
        fenced("text", directory_tree(output_path, root_name="models")),
    ]
    for file_name in ("schema_a.py", "schema_b.py", "shared.py"):
        lines.extend((
            f"**models/{file_name}:**",
            fenced("python", read_python_output(output_path / file_name)),
        ))
    return "\n".join(lines)


def docs_examples() -> tuple[DocsExample, ...]:
    """Return all generated docs example sections."""
    return (
        DocsExample(
            example_id="openapi.quick-start.schema",
            path=DOCS / "openapi.md",
            render=lambda: details("api.yaml", "yaml", read_text(TEST_DATA / "openapi" / "api.yaml")),
        ),
        DocsExample(
            example_id="openapi.quick-start.output",
            path=DOCS / "openapi.md",
            render=lambda: render_file_example(
                language="python",
                path=EXPECTED_MAIN / "openapi" / "general.py",
                strip_python_header=True,
            ),
        ),
        DocsExample(
            example_id="openapi.read-only-write-only.schema",
            path=DOCS / "openapi.md",
            render=lambda: render_file_example(
                language="yaml",
                path=TEST_DATA / "openapi" / "read_only_write_only.yaml",
            ),
        ),
        DocsExample(
            example_id="openapi.read-only-write-only.output",
            path=DOCS / "openapi.md",
            render=lambda: render_file_example(
                language="python",
                path=EXPECTED_MAIN / "openapi" / "read_only_write_only_all.py",
                strip_python_header=True,
            ),
        ),
        DocsExample(
            example_id="openapi.read-only-write-only-allof.schema",
            path=DOCS / "openapi.md",
            render=lambda: render_file_example(
                language="yaml",
                path=TEST_DATA / "openapi" / "read_only_write_only_allof.yaml",
            ),
        ),
        DocsExample(
            example_id="model-reuse.reuse-model.output",
            path=DOCS / "model-reuse.md",
            render=lambda: render_file_example(
                language="python",
                path=EXPECTED_MAIN / "jsonschema" / "json_reuse_enum.py",
                strip_python_header=True,
            ),
        ),
        DocsExample(
            example_id="model-reuse.reuse-scope-tree.output",
            path=DOCS / "model-reuse.md",
            render=render_reuse_scope_tree_example,
        ),
        DocsExample(
            example_id="model-reuse.use-type-alias.schema",
            path=DOCS / "model-reuse.md",
            render=lambda: render_file_example(
                language="json",
                path=TEST_DATA / "jsonschema" / "reduce_duplicate_field_types.json",
            ),
        ),
        DocsExample(
            example_id="model-reuse.use-type-alias.output",
            path=DOCS / "model-reuse.md",
            render=lambda: render_file_example(
                language="python",
                path=EXPECTED_MAIN / "jsonschema" / "reduce_duplicate_field_types.py",
                strip_python_header=True,
            ),
        ),
    )


def replace_example(content: str, example: DocsExample) -> tuple[str, bool]:
    """Replace one generated example section in Markdown."""
    begin_marker = BEGIN_MARKER_TEMPLATE.format(example_id=example.example_id)
    end_marker = END_MARKER_TEMPLATE.format(example_id=example.example_id)
    pattern = re.compile(rf"{re.escape(begin_marker)}.*?{re.escape(end_marker)}", re.DOTALL)
    if not (match := pattern.search(content)):
        print(f"Warning: markers not found for {example.example_id} in {example.path}", file=sys.stderr)
        return content, False

    new_section = f"{begin_marker}{example.render()}{end_marker}"
    return content[: match.start()] + new_section + content[match.end() :], True


def iter_examples_by_path() -> Iterable[tuple[Path, tuple[DocsExample, ...]]]:
    """Yield docs examples grouped by Markdown file."""
    examples_by_path: dict[Path, list[DocsExample]] = {}
    for example in docs_examples():
        examples_by_path.setdefault(example.path, []).append(example)
    for path, examples in examples_by_path.items():
        yield path, tuple(examples)


def update_docs_examples(*, check: bool = False) -> int:
    """Update or check generated documentation examples."""
    changed_paths = []
    for path, examples in iter_examples_by_path():
        content = path.read_text(encoding="utf-8")
        updated_content = content
        for example in examples:
            updated_content, found = replace_example(updated_content, example)
            if not found:
                return 1
        if updated_content == content:
            continue
        if check:
            print(f"Docs examples are out of date: {path}", file=sys.stderr)
            print("Run 'python scripts/build_docs_examples.py' to update.", file=sys.stderr)
            return 1
        path.write_text(updated_content, encoding="utf-8")
        changed_paths.append(path)

    if changed_paths:
        for path in changed_paths:
            print(f"Updated {path}")
        return 0

    print("Docs examples are up to date.")
    return 0


def main() -> int:
    """Parse arguments and build docs examples."""
    parser = argparse.ArgumentParser(description="Build docs examples from tested fixtures")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if docs examples would change without modifying files",
    )
    args = parser.parse_args()
    return update_docs_examples(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
