# generated by datamodel-codegen:
#   filename:  double_full.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel


class Model(RootModel[float]):
    root: float = Field(..., title='Model')
