# generated by datamodel-codegen:
#   filename:  http://localhost:8888/schemas/v1/main.schema.json

from __future__ import annotations

from pydantic import Field, RootModel, constr


class Schema(RootModel[constr(pattern=r'^[0-9a-f]{8}$')]):
    root: constr(pattern=r'^[0-9a-f]{8}$') = Field(..., title='Sub')
