# generated by datamodel-codegen:
#   filename:  schema_a.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    name: str | None = None
