# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import Field, RootModel, conint


class Token(RootModel[conint(ge=2)]):
    root: conint(ge=2)


class Root(RootModel[Token]):
    root: Token = Field(..., description='An allOf value root.', title='Root')