# generated by datamodel-codegen:
#   filename:  nullable_inline.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[int | None]):
    root: int | None = Field(
        ..., description='An allOf value root.', ge=2, title='Root'
    )
