# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import Field, RootModel, conint


class Token(RootModel[conint(ge=2) | None]):
    root: conint(ge=2) | None


class Root(RootModel[Token | None]):
    root: Token | None = Field(..., description='An allOf value root.', title='Root')