<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="Plain">
    <xs:sequence>
      <xs:element name="value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="datetime_module" type="xs:string" minOccurs="0" default="reserved"/>
        <xs:element name="eventDate" type="xs:date" minOccurs="0" default="2026-06-04"/>
        <xs:element name="dates" minOccurs="0" default="2026-06-05 2026-06-06">
          <xs:simpleType>
            <xs:list itemType="xs:date"/>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
