# generated by datamodel-codegen:
#   filename:  classvar.json

from __future__ import annotations

from typing import ClassVar

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: int
    shared: ClassVar[list[int] | None] = []


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item] = Field(..., json_schema_extra={'x-python-type': 'set[Item]'})
