# generated by datamodel-codegen:
#   filename:  mutable.json

from __future__ import annotations

from tests.data.python.unique_model_sets.explicit_native import CustomHashBase


class Item(CustomHashBase):
    value: int


class Container(CustomHashBase):
    items: set[Item]
