# generated by datamodel-codegen:
#   filename:  default_factory.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: int = Field(default_factory=list)


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item] = Field(..., json_schema_extra={'x-python-type': 'set[Item]'})
