# generated by datamodel-codegen:
#   filename:  shadowed_builtin.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from tests.data.python.unique_model_sets.opaque_values import int


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: int


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
