# generated by datamodel-codegen:
#   filename:  standard_local_datetime.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, NaiveDatetime


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: NaiveDatetime


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
