# generated by datamodel-codegen:
#   filename:  standard_nested.json

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict


class DateValue(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: date


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: DateValue


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
