# generated by datamodel-codegen:
#   filename:  standard_datetime.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: AwareDatetime


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
