# generated by datamodel-codegen:
#   filename:  transported_datetime.json

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: datetime


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
