# generated by datamodel-codegen:
#   filename:  transported_collision.json

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict

from tests.data.python.unique_model_sets.transported_values import date as date_1


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: date


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
    marker: date_1 | None = None
