# generated by datamodel-codegen:
#   filename:  transported_decimal.json

from __future__ import annotations

from decimal import Decimal

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: Decimal


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
