# generated by datamodel-codegen:
#   filename:  transported_date_tuple.json

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    __hash__ = object.__hash__
    value: tuple[date, ...]


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
