# generated by datamodel-codegen:
#   filename:  tuple_any.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: tuple[Any, ...]


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
