# generated by datamodel-codegen:
#   filename:  tuple_literal.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    value: tuple[Literal[1], ...]


class Container(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    items: set[Item]
