# generated by datamodel-codegen:
#   filename:  module.openapi.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Input(BaseModel):
    name: str | None = None


class Output(BaseModel):
    output: str | None = None
    input: Input | None = None
