# generated by datamodel-codegen:
#   filename:  use_pendulum.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pendulum import Date, DateTime, Duration
from pydantic import BaseModel


class Event(BaseModel):
    name: str
    created_at: DateTime
    event_date: Optional[Date] = None
    duration: Optional[Duration] = None
