# generated by datamodel-codegen:
#   filename:  additional_properties.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class Pet(BaseModel):
    class Config:
        extra = Extra.forbid

    id: int
    name: str
    tag: str | None = None


class Pets(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: list[Pet]


class User(BaseModel):
    class Config:
        extra = Extra.forbid

    id: int
    name: str
    tag: str | None = None


class Users(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: list[User]


class Id(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: str


class Rules(BaseModel):
    class Config:
        extra = Extra.forbid

    __root__: list[str]


class Error(BaseModel):
    class Config:
        extra = Extra.forbid

    code: int
    message: str


class Event(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str | None = None


class Result(BaseModel):
    class Config:
        extra = Extra.forbid

    event: Event | None = None


class Broken(BaseModel):
    class Config:
        extra = Extra.forbid

    foo: str | None = None
    bar: int | None = None


class BrokenArray(BaseModel):
    class Config:
        extra = Extra.forbid

    broken: dict[str, list[Broken]] | None = None


class FileSetUpload(BaseModel):
    class Config:
        extra = Extra.forbid

    task_id: str | None = Field(None, title='task id')
    tags: dict[str, list[str]] = Field(
        ..., title='Dict of tags, each containing a list of file names'
    )


class Test(BaseModel):
    class Config:
        extra = Extra.forbid

    broken: dict[str, Broken] | None = None
    failing: dict[str, str] | None = {}
