# generated by datamodel-codegen:
#   filename:  allof_partial_override_non_array_field.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Thing(BaseModel):
    name: str | None = 'default_name'
    count: int | None = 0


class Person(Thing):
    name: str | None = Field(None, title='Person name')
    count: int | None = Field(None, description='Count value')
