# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class ScopedInner(RootModel[str]):
    root: str = Field(..., min_length=2)


class Value(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScopedContainer(RootModel[list[ScopedInner]]):
    root: list[ScopedInner]


class ScopedBase(BaseModel):
    values: ScopedContainer


class ScopedChild(ScopedBase):
    values: list[Value]
