# generated by datamodel-codegen:
#   filename:  allof_partial_unconstrained_schemas.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, constr


class ScalarValue(RootModel[constr(min_length=2)]):
    root: constr(min_length=2)


class ScalarArray(RootModel[list[ScalarValue]]):
    root: list[ScalarValue] = Field(..., min_length=2)


class ScalarMapping(RootModel[dict[str, ScalarValue]]):
    root: dict[str, ScalarValue] = Field(..., min_length=2)


class Item(BaseModel):
    code: constr(min_length=2)


class PrefixItemsNeutralItem(RootModel[constr(min_length=2)]):
    root: constr(min_length=2)


class LegacyItemsNeutralItem(RootModel[constr(min_length=2)]):
    root: constr(min_length=2)


class UnevaluatedItemsNeutralItem(RootModel[constr(min_length=2)]):
    root: constr(min_length=2)


class InlineObjectNeutral(BaseModel):
    code: constr(min_length=2)


class Base(BaseModel):
    arrayValue: list[Item]
    mappingValue: dict[str, Item]
    anyEmptyValue: Item
    anyTrueValue: Item
    oneEmptyValue: Item
    oneTrueValue: Item
    allEmptyValue: Item
    allTrueValue: Item
    nullableValue: Item
    nullableObjectValue: Item
    directScalarValue: ScalarValue
    directScalarInferred: ScalarValue
    inlineScalarInferred: constr(min_length=2)
    scalarArrayInferred: list[ScalarValue]
    scalarMappingInferred: dict[str, ScalarValue]
    scalarDeepInferred: list[list[ScalarValue]]
    scalarArrayRootInferred: ScalarArray
    scalarMappingRootInferred: ScalarMapping
    arrayNeutralComposition: list[Item]
    mappingNeutralComposition: dict[str, Item]
    deepArrayNeutralComposition: list[list[Item]]
    scalarArrayWeaker: list[ScalarValue]
    scalarMappingWeaker: dict[str, ScalarValue]
    scalarDeepWeaker: list[list[ScalarValue]]
    prefixItemsNeutral: tuple[PrefixItemsNeutralItem, int]
    legacyItemsNeutral: tuple[LegacyItemsNeutralItem, int]
    unevaluatedItemsNeutral: tuple[UnevaluatedItemsNeutralItem, int]
    inlineObjectNeutral: InlineObjectNeutral
    refObjectNeutral: Item


class Child(Base):
    arrayValue: list[Item]
    mappingValue: dict[str, Item]
    anyEmptyValue: Item
    anyTrueValue: Item
    oneEmptyValue: Item
    oneTrueValue: Item
    allEmptyValue: Item
    allTrueValue: Item
    nullableValue: Item
    nullableObjectValue: Item
    directScalarValue: constr(min_length=1)
    directScalarInferred: constr(min_length=1)
    inlineScalarInferred: constr(min_length=1)
    scalarArrayInferred: list[constr(min_length=1)]
    scalarMappingInferred: dict[str, constr(min_length=1)]
    scalarDeepInferred: list[list[constr(min_length=1)]]
    scalarArrayRootInferred: list[ScalarValue] = Field(..., min_length=1)
    scalarMappingRootInferred: dict[str, ScalarValue] = Field(..., min_length=1)
    arrayNeutralComposition: list[Item]
    mappingNeutralComposition: dict[str, Item]
    deepArrayNeutralComposition: list[list[Item]]
    scalarArrayWeaker: list[constr(min_length=1)]
    scalarMappingWeaker: dict[str, constr(min_length=1)]
    scalarDeepWeaker: list[list[constr(min_length=1)]]
    prefixItemsNeutral: tuple[PrefixItemsNeutralItem, int]
    legacyItemsNeutral: tuple[LegacyItemsNeutralItem, int]
    unevaluatedItemsNeutral: tuple[UnevaluatedItemsNeutralItem, int]
    inlineObjectNeutral: InlineObjectNeutral
    refObjectNeutral: Item
