# generated by datamodel-codegen:
#   filename:  allof_partial_override_non_array_field.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Thing(BaseModel):
    name: Optional[str] = 'default_name'
    count: Optional[int] = 0


class Person(Thing):
    name: Optional[str] = Field(None, title='Person name')
    count: Optional[int] = Field(None, description='Count value')
