# generated by datamodel-codegen:
#   filename:  allof_with_required_inherited_edge_cases.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, RootModel, conint, model_validator


class BaseRef(BaseModel):
    id: int | None = None


class StatusEnum(Enum):
    active = 'active'
    inactive = 'inactive'


class SingleAllofPrimitive(RootModel[str]):
    root: str


class AllofNestedAnyof(RootModel[str | int]):
    root: str | int


class AllofConstraintOnly(RootModel[Any]):
    root: Any


class AllofMaxConstraints(RootModel[conint(le=50)]):
    root: conint(le=50)


class AllofUniqueItems(RootModel[list[str]]):
    root: list[str]

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_unique_key(value):
            value = json_schema_runtime_value(value)
            if isinstance(value, bool) or value is None or isinstance(value, str):
                return (type(value).__name__, value)
            if isinstance(value, (int, float)):
                return ('number', value)
            if isinstance(value, list):
                return ('array', tuple(json_schema_unique_key(item) for item in value))
            if isinstance(value, dict):
                return (
                    'object',
                    tuple(
                        sorted(
                            (key, json_schema_unique_key(item))
                            for key, item in value.items()
                        )
                    ),
                )
            return (type(value).__name__, value)

        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(
                    mode='python', by_alias=True, exclude_unset=True
                )
            if isinstance(value, (list, tuple)):
                return [json_schema_runtime_value(item) for item in value]
            if isinstance(value, dict):
                return {
                    key: json_schema_runtime_value(item) for key, item in value.items()
                }
            return value

        root_value = json_schema_runtime_value(self.root)
        if not (
            (isinstance(root_value, list))
            and (
                (
                    not isinstance(root_value, list)
                    or all(
                        (lambda extra_item: isinstance(extra_item, str))(extra_item)
                        for extra_item in root_value
                    )
                )
            )
            and (
                (
                    not isinstance(root_value, list)
                    or len(root_value)
                    == len(
                        {
                            json_schema_unique_key(unique_item)
                            for unique_item in root_value
                        }
                    )
                )
            )
        ):
            raise ValueError('root object does not match schema')
        return self


class ObjectWithoutAdditional(BaseModel):
    nested: str | None = None


class MultipleAdditionalProps(RootModel[dict[str, Any]]):
    root: dict[str, Any]

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(
                    mode='python', by_alias=True, exclude_unset=True
                )
            if isinstance(value, (list, tuple)):
                return [json_schema_runtime_value(item) for item in value]
            if isinstance(value, dict):
                return {
                    key: json_schema_runtime_value(item) for key, item in value.items()
                }
            return value

        root_value = json_schema_runtime_value(self.root)
        if not (
            (
                (isinstance(root_value, dict))
                and (
                    (
                        not isinstance(root_value, dict)
                        or all(
                            (lambda extra_value: isinstance(extra_value, str))(
                                extra_value
                            )
                            for extra_key, extra_value in root_value.items()
                            if not ((extra_key in {}))
                        )
                    )
                )
            )
            and (
                (isinstance(root_value, dict))
                and (
                    (
                        not isinstance(root_value, dict)
                        or all(
                            (
                                lambda extra_value: (isinstance(extra_value, dict))
                                and (
                                    (
                                        not isinstance(extra_value, dict)
                                        or 'id' not in extra_value
                                        or (
                                            lambda extra_value_property_0: isinstance(
                                                extra_value_property_0, int
                                            )
                                            and not isinstance(
                                                extra_value_property_0, bool
                                            )
                                        )(extra_value['id'])
                                    )
                                )
                            )(extra_value)
                            for extra_key, extra_value in root_value.items()
                            if not ((extra_key in {}))
                        )
                    )
                )
            )
        ):
            raise ValueError('root object does not match schema')
        return self


class L3(BaseModel):
    l4: str | None = None


class L2(BaseModel):
    l3: L3 | None = None


class L1(BaseModel):
    l2: L2 | None = None


class DepthLimitTest(BaseModel):
    l1: L1 | None = None


class ProjectedEdgeCases(BaseModel):
    single_allof_primitive: SingleAllofPrimitive | None = None
    single_allof_ref: BaseRef | None = None
    allof_with_enum: StatusEnum | None = None
    allof_nested_anyof: AllofNestedAnyof | None = None
    allof_constraint_only: AllofConstraintOnly | None = None
    allof_max_constraints: AllofMaxConstraints | None = None
    allof_unique_items: AllofUniqueItems | None = None
    object_without_additional: ObjectWithoutAdditional | None = None
    object_only_type: dict[str, Any] | None = None
    multiple_additional_props: MultipleAdditionalProps | None = None
    depth_limit_test: DepthLimitTest | None = None
    cycle_detection: BaseRef | None = None
    type_list_field: str | int | None = None
    allof_multiple_refs_only: BaseRef | None = None


class EdgeCases(ProjectedEdgeCases):
    extra: str | None = None
    single_allof_primitive: str
    single_allof_ref: BaseRef
    allof_with_enum: StatusEnum
    allof_nested_anyof: str | int
    allof_constraint_only: Any
    allof_max_constraints: conint(le=50)
    allof_unique_items: list[str]
    object_without_additional: dict[str, Any]
    object_only_type: dict[str, Any]
    multiple_additional_props: dict[str, BaseRef]
    depth_limit_test: dict[str, Any]
    cycle_detection: BaseRef
    type_list_field: str | int
    allof_multiple_refs_only: BaseRef
