# generated by datamodel-codegen:
#   filename:  allof_partial_override_deeply_nested_array.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Thing(BaseModel):
    cube: Optional[list[list[list[str]]]] = [[['a']]]


class Person(Thing):
    cube: Optional[list[list[list[str]]]] = [[['b']]]
