# generated by datamodel-codegen:
#   filename:  allof_with_required_inherited_fields.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class ProjectedPet(BaseModel):
    id: int | None = None
    name: str | None = None


class Pet(ProjectedPet):
    tag: str | None = None
    opts: list[str]
    id: int
    name: str
