# generated by datamodel-codegen:
#   filename:  allof_partial_unconstrained_schemas.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class ScalarValue(RootModel[str]):
    root: str = Field(..., min_length=2)


class ScalarArray(RootModel[list[ScalarValue]]):
    root: list[ScalarValue] = Field(..., min_length=2)


class ScalarMapping(RootModel[dict[str, ScalarValue]]):
    root: dict[str, ScalarValue] = Field(..., min_length=2)


class Item(BaseModel):
    code: str = Field(..., min_length=2)


class PrefixItemsNeutralItem(RootModel[str]):
    root: str = Field(..., min_length=2)


class LegacyItemsNeutralItem(RootModel[str]):
    root: str = Field(..., min_length=2)


class UnevaluatedItemsNeutralItem(RootModel[str]):
    root: str = Field(..., min_length=2)


class InlineObjectNeutral(BaseModel):
    code: str = Field(..., min_length=2)


class Base(BaseModel):
    arrayValue: list[Item]
    mappingValue: dict[str, Item]
    anyEmptyValue: Item
    anyTrueValue: Item
    oneEmptyValue: Item
    oneTrueValue: Item
    allEmptyValue: Item
    allTrueValue: Item
    nullableValue: Item
    nullableObjectValue: Item
    directScalarValue: ScalarValue
    directScalarInferred: ScalarValue
    inlineScalarInferred: str = Field(..., min_length=2)
    scalarArrayInferred: list[ScalarValue]
    scalarMappingInferred: dict[str, ScalarValue]
    scalarDeepInferred: list[list[ScalarValue]]
    scalarArrayRootInferred: ScalarArray
    scalarMappingRootInferred: ScalarMapping
    arrayNeutralComposition: list[Item]
    mappingNeutralComposition: dict[str, Item]
    deepArrayNeutralComposition: list[list[Item]]
    scalarArrayWeaker: list[ScalarValue]
    scalarMappingWeaker: dict[str, ScalarValue]
    scalarDeepWeaker: list[list[ScalarValue]]
    prefixItemsNeutral: tuple[PrefixItemsNeutralItem, int]
    legacyItemsNeutral: tuple[LegacyItemsNeutralItem, int]
    unevaluatedItemsNeutral: tuple[UnevaluatedItemsNeutralItem, int]
    inlineObjectNeutral: InlineObjectNeutral
    refObjectNeutral: Item


class ScalarArrayInferredItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScalarMappingInferred(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScalarDeepInferredItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScalarArrayWeakerItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScalarMappingWeaker(RootModel[str]):
    root: str = Field(..., min_length=1)


class ScalarDeepWeakerItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Child(Base):
    arrayValue: list[Item]
    mappingValue: dict[str, Item]
    anyEmptyValue: Item
    anyTrueValue: Item
    oneEmptyValue: Item
    oneTrueValue: Item
    allEmptyValue: Item
    allTrueValue: Item
    nullableValue: Item
    nullableObjectValue: Item
    directScalarValue: str = Field(..., min_length=1)
    directScalarInferred: str = Field(..., min_length=1)
    inlineScalarInferred: str = Field(..., min_length=1)
    scalarArrayInferred: list[ScalarArrayInferredItem]
    scalarMappingInferred: dict[str, ScalarMappingInferred]
    scalarDeepInferred: list[list[ScalarDeepInferredItem]]
    scalarArrayRootInferred: list[ScalarValue] = Field(..., min_length=1)
    scalarMappingRootInferred: dict[str, ScalarValue] = Field(..., min_length=1)
    arrayNeutralComposition: list[Item]
    mappingNeutralComposition: dict[str, Item]
    deepArrayNeutralComposition: list[list[Item]]
    scalarArrayWeaker: list[ScalarArrayWeakerItem]
    scalarMappingWeaker: dict[str, ScalarMappingWeaker]
    scalarDeepWeaker: list[list[ScalarDeepWeakerItem]]
    prefixItemsNeutral: tuple[PrefixItemsNeutralItem, int]
    legacyItemsNeutral: tuple[LegacyItemsNeutralItem, int]
    unevaluatedItemsNeutral: tuple[UnevaluatedItemsNeutralItem, int]
    inlineObjectNeutral: InlineObjectNeutral
    refObjectNeutral: Item
