# generated by datamodel-codegen:
#   filename:  allof_materialize_defaults.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, conint, constr


class Parent(BaseModel):
    name: Optional[constr(min_length=1)] = 'parent_default'
    count: Optional[conint(ge=0)] = 10


class Child(Parent):
    name: Optional[constr(min_length=1, max_length=100)] = 'parent_default'
    count: Optional[conint(ge=0, le=1000)] = 10
