# generated by datamodel-codegen:
#   filename:  allof_required_inherited_model_references.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel, confloat, conint, constr


class Detail(BaseModel):
    code: constr(min_length=1)


class ForwardEvent(BaseModel):
    latitude: confloat(ge=-90.0, le=90.0)


class ForwardWindow(BaseModel):
    start_at: conint(ge=0) = Field(..., alias='startAt')


class ForwardBasePickup(BaseModel):
    detail: Detail | None = None
    forward_events: list[ForwardEvent] | None = Field(None, alias='forwardEvents')
    forward_window: ForwardWindow | None = Field(None, alias='forwardWindow')


class LegacyContact(BaseModel):
    legacy_name: str | None = Field(None, alias='legacyName')


class BasePickup(BaseModel):
    contact_details: LegacyContact | None = Field(None, alias='contactDetails')


class ContactDetails(BaseModel):
    legacy_name: str | None = Field(None, alias='legacyName')
    name: constr(min_length=1)


class Event(ForwardEvent):
    pass


class PickupWindow(BaseModel):
    start_at: int = Field(..., alias='startAt')
    end_at: int = Field(..., alias='endAt')


class LabelPackage(BaseModel):
    label_id: constr(min_length=1) = Field(..., alias='labelId')


class Package(BaseModel):
    sku: constr(min_length=1)


class TrackingCode(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ForwardDeclaredPickup(ForwardBasePickup):
    detail: Detail
    forward_events: list[ForwardEvent] = Field(..., alias='forwardEvents')
    forward_window: ForwardWindow = Field(..., alias='forwardWindow')


class ForwardInlineRequiredPickup(ForwardDeclaredPickup):
    pass


class ForwardPartialPickup(ForwardBasePickup):
    detail: Detail | None = None
    forward_events: list[ForwardEvent] | None = Field(None, alias='forwardEvents')


class PackageModel(LabelPackage):
    alternative_identifiers: list[constr(min_length=1)] = Field(
        ..., alias='alternativeIdentifiers'
    )


class Pickup(BasePickup):
    contact_details: ContactDetails | None = Field(
        None, alias='contactDetails', title='contact_details'
    )
    events: list[Event] | None = None
    packages: list[PackageModel] | None = None
    package: Package | None = None
    tracking_code: TrackingCode | None = Field(None, alias='trackingCode')
    pickup_window: PickupWindow | None = Field(
        None, alias='pickupWindow', title='pickup_window'
    )
    mode: str | None = 'standard'


class ScheduledPickup(Pickup):
    contact_details: ContactDetails = Field(
        ..., alias='contactDetails', title='contact_details'
    )
    events: list[Event]
    packages: list[PackageModel]
    package: Package
    tracking_code: TrackingCode = Field(..., alias='trackingCode')
    pickup_window: PickupWindow = Field(
        ..., alias='pickupWindow', title='pickup_window'
    )
    mode: str = 'scheduled'
    fallback_field: Any = Field(..., alias='fallbackField')


class ReverseScheduledPickup(Pickup):
    note: str | None = None
    contact_details: ContactDetails = Field(
        ..., alias='contactDetails', title='contact_details'
    )
    events: list[Event]
    packages: list[PackageModel]
