# generated by datamodel-codegen:
#   filename:  builtin_type_field_names.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class BuiltinTypeFieldNames(BaseModel):
    bool_: bool | None = Field(None, alias='bool')
    bytearray: bytes | None = None
    bytes_: bytes | None = Field(None, alias='bytes')
    classmethod: str | None = None
    complex: float | None = None
    dict_: dict[str, Any] | None = Field(None, alias='dict')
    enumerate: str | None = None
    filter: str | None = None
    float_: float | None = Field(None, alias='float')
    frozenset: list[str] | None = None
    int_: int | None = Field(None, alias='int')
    list_: list[str] | None = Field(None, alias='list')
    map: str | None = None
    memoryview: str | None = None
    object: dict[str, Any] | None = None
    property: str | None = None
    range: str | None = None
    reversed: str | None = None
    set: list[str] | None = None
    slice: str | None = None
    staticmethod: str | None = None
    str_: str | None = Field(None, alias='str')
    super: str | None = None
    tuple: list[str] | None = None
    type: str | None = None
    zip: str | None = None
    normal_field: str | None = None
