# generated by datamodel-codegen:
#   filename:  byte_format.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Base64Str, BaseModel, Field, RootModel


class Data(RootModel[Base64Str]):
    root: Base64Str = Field(..., description='The version of this API')


class Api(BaseModel):
    data: Data
