# generated by datamodel-codegen:
#   filename:  collapse_root_models_recursive_invalid_dotted.yaml

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, RootModel


class Value(RootModel[Optional[Union[str, list["Value"], dict[str, "Value"]]]]):
    root: Optional[Union[str, list["Value"], dict[str, "Value"]]] = None


class Field1(BaseModel):
    pass


class SaveRequest(BaseModel):
    trifecta: Field1 | None = None
    value: Value | None = None


Value.model_rebuild()
