# generated by datamodel-codegen:
#   filename:  const.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class Namespace(BaseModel):
    apiVersion: Literal['v1'] = Field('v1', const=True)
    kind: Literal['Namespace'] = Field('Namespace', const=True)
