# generated by datamodel-codegen:
#   filename:  dataclass_inheritance_field_ordering.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ParentWithDefault:
    name: str | None = 'default_name'
    read_only_field: str | None = None


@dataclass
class ChildWithRequired(ParentWithDefault):
    child_id: str = field(kw_only=True)
