# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from custom_base import Base
from typing_extensions import TypeAlias


@dataclass
class Pet(Base):
    id: int
    name: str
    tag: Optional[str] = None


Pets: TypeAlias = List[Pet]


@dataclass
class User(Base):
    id: int
    name: str
    tag: Optional[str] = None


Users: TypeAlias = List[User]


Id: TypeAlias = str


Rules: TypeAlias = List[str]


@dataclass
class Error(Base):
    code: int
    message: str


@dataclass
class Api(Base):
    apiKey: Optional[str] = None
    apiVersionNumber: Optional[str] = None
    apiUrl: Optional[str] = None
    apiDocumentationUrl: Optional[str] = None


Apis: TypeAlias = List[Api]


@dataclass
class Event(Base):
    name: Optional[str] = None


@dataclass
class Result(Base):
    event: Optional[Event] = None
