# generated by datamodel-codegen:
#   filename:  date_class.yaml
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, PastDate


class Event(BaseModel):
    eventDate: PastDate = Field(..., examples=['2023-12-25'])
