# generated by datamodel-codegen:
#   filename:  default_values_parameters.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Filter(BaseModel):
    name: str | None = None


class UsersGetParametersQuery(BaseModel):
    status: str | None = 'active'
    filter: Filter | None = Field(default_factory=lambda: Filter.parse_obj({}))


class User(BaseModel):
    id: int | None = None
    name: str | None = None


class UserList(BaseModel):
    __root__: list[User]
