# generated by datamodel-codegen:
#   filename:  deprecated_field.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Service(BaseModel):
    name: str = Field(..., description='Name of the service')
    location: str | None = Field(
        None, deprecated=True, description='Location of the service (deprecated)'
    )
    old_id: int | None = Field(None, deprecated=True)
