# generated by datamodel-codegen:
#   filename:  duplicate_models2.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, RootModel


class PetType(Enum):
    pet = 'pet'


class PetDetails(BaseModel):
    race: str | None = None


class Pet(BaseModel):
    id: int
    name: str
    tag: str | None = None
    type: PetType
    details: PetDetails | None = None


class CarType(Enum):
    car = 'car'


class CarDetails(BaseModel):
    brand: str | None = None


class Car(BaseModel):
    id: int
    name: str
    tag: str | None = None
    type: CarType
    details: CarDetails | None = None


class Cars(RootModel[Any]):
    root: Any
