# generated by datamodel-codegen:
#   filename:  empty_list_default.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Container(BaseModel):
    name: str | None = None


class PodSpec(BaseModel):
    containers: list[Container] | None = Field(default_factory=list)
