# generated by datamodel-codegen:
#   filename:  api_file_uri.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from mypackage.shared.models import User
from pydantic import BaseModel


class UserResponse(BaseModel):
    user: User
