# generated by datamodel-codegen:
#   filename:  type_alias_mutual_recursive.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypeAlias, Union

NodeA: TypeAlias = Union[int, "NodeB"]


NodeB: TypeAlias = str | NodeA
