# generated by datamodel-codegen:
#   filename:  empty_dict_default.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Union

from msgspec import UNSET, Struct, UnsetType, field


class ObjectMeta(Struct):
    name: Union[str, UnsetType] = UNSET
    namespace: Union[str, UnsetType] = UNSET


class PodSpec(Struct):
    metadata: Union[ObjectMeta, UnsetType] = field(default_factory=dict)
