# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated, List, Optional

from msgspec import Meta, Struct
from typing_extensions import TypeAliasType


class Pet(Struct):
    id: int
    name: str
    tag: Optional[str] = None


Pets = TypeAliasType("Pets", List[Pet])


class User(Struct):
    id: int
    name: str
    tag: Optional[str] = None


Users = TypeAliasType("Users", List[User])


Id = TypeAliasType("Id", str)


Rules = TypeAliasType("Rules", List[str])


class Error(Struct):
    code: int
    message: str


class Api(Struct):
    apiKey: Optional[
        Annotated[str, Meta(description='To be used as a dataset parameter value')]
    ] = None
    apiVersionNumber: Optional[
        Annotated[str, Meta(description='To be used as a version parameter value')]
    ] = None
    apiUrl: Optional[
        Annotated[str, Meta(description="The URL describing the dataset's fields")]
    ] = None
    apiDocumentationUrl: Optional[
        Annotated[str, Meta(description='A URL to the API console for each API')]
    ] = None


Apis = TypeAliasType("Apis", List[Api])


class Event(Struct):
    name: Optional[str] = None


class Result(Struct):
    event: Optional[Event] = None
