# generated by datamodel-codegen:
#   filename:  nullable_31.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Apple(BaseModel):
    pass


class Basket(BaseModel):
    apples: list[Apple] | None
