# generated by datamodel-codegen:
#   filename:  webhooks.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Pet(BaseModel):
    id: int
    name: str
    tag: str | None = None


class PetUpdate(BaseModel):
    id: int | None = None
    name: str | None = None
    tag: str | None = None
