# generated by datamodel-codegen:
#   filename:  non_operations_and_security.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Pet(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class PetsGetResponse(BaseModel):
    __root__: List[Pet]
