# generated by datamodel-codegen:
#   filename:  pattern_lookaround.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import ConfigDict, constr
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(regex_engine="python-re"))
class Info:
    name: constr(pattern=r'.*foo.*(?<!baz)bar.*') | None = None
