# generated by datamodel-codegen:
#   filename:  dataclass_inheritance_field_ordering.yaml

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class ParentWithDefault:
    name: str | None = 'default_name'
    read_only_field: str | None = None


@dataclass
class ChildWithRequired(ParentWithDefault):
    child_id: str = Field(..., kw_only=True)
