# generated by datamodel-codegen:
#   filename:  read_only_write_only_union.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel


class UserRequest(BaseModel):
    name: str
    metadata: Optional[Union[str, int]] = None


class UserResponse(BaseModel):
    id: int
    name: str


class User(BaseModel):
    id: int
    name: str
    metadata: Optional[Union[str, int]] = None
