# generated by datamodel-codegen:
#   filename:  read_only_write_only_variant_graph.yaml

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import BaseModel, model_validator


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = ()
    __json_schema_property_count_rule__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_property_count(data)
        data = cls._validate_json_schema_conditional_required(data)
        return data

    @classmethod
    def _validate_json_schema_conditional_required(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data
        for rule in cls.__json_schema_conditional_required__:
            condition_matches = all(
                any(name in data and data[name] in expected for name in names)
                for names, expected in rule['condition']
            )
            required_groups = (
                rule['then_required_groups']
                if condition_matches
                else rule['else_required_groups']
            )
            for group in required_groups:
                if all(any(name in data for name in names) for names in group):
                    continue
                raise ValueError('Conditional required properties are missing')
        return data

    @classmethod
    def _validate_json_schema_property_count(cls, data: Any) -> Any:
        if not (rule := cls.__json_schema_property_count_rule__):
            return data
        if not isinstance(data, dict):
            return data
        property_count = len(data)
        min_properties, max_properties = rule
        if min_properties is not None and property_count < min_properties:
            raise ValueError(f'Expected at least {min_properties} properties')
        if max_properties is not None and property_count > max_properties:
            raise ValueError(f'Expected at most {max_properties} properties')
        return data


class ApiReadOnlyLeafRequestModel(BaseModel):
    pass


class ApiReadOnlyLeafResponseModel(BaseModel):
    id: int


class ApiConditionalEnvelopeRequestModel(_JsonSchemaRuntimeValidationBase):
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = (
        {
            'condition': ((('kind',), ('metric',)),),
            'then_required_groups': ((('metricLeaf',),),),
            'else_required_groups': ((('noteLeaf',),),),
        },
    )

    __json_schema_property_count_rule__: ClassVar[tuple[Any, ...]] = (
        2,
        2,
    )

    kind: str
    metricLeaf: ApiReadOnlyLeafRequestModel | None = None
    noteLeaf: ApiReadOnlyLeafRequestModel | None = None


class ApiConditionalEnvelopeResponseModel(_JsonSchemaRuntimeValidationBase):
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = (
        {
            'condition': ((('kind',), ('metric',)),),
            'then_required_groups': ((('metricLeaf',),),),
            'else_required_groups': ((('noteLeaf',),),),
        },
    )

    __json_schema_property_count_rule__: ClassVar[tuple[Any, ...]] = (
        2,
        2,
    )

    kind: str
    metricLeaf: ApiReadOnlyLeafResponseModel | None = None
    noteLeaf: ApiReadOnlyLeafResponseModel | None = None


class ApiConditionalForwardWrapperRequestModel(BaseModel):
    payload: ApiConditionalEnvelopeRequestModel


class ApiConditionalForwardWrapperResponseModel(BaseModel):
    payload: ApiConditionalEnvelopeResponseModel
