# generated by datamodel-codegen:
#   filename:  read_only_write_only_allof_url_ref.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class ChildRequest(BaseModel):
    id: int
    password: str | None = None
    child_field: str | None = None


class ChildResponse(BaseModel):
    id: int
    created_at: AwareDatetime | None = None
    child_field: str | None = None


class BaseObjectRequest(BaseModel):
    id: int
    password: str | None = None


class BaseObjectResponse(BaseModel):
    id: int
    created_at: AwareDatetime | None = None


class BaseObject(BaseModel):
    id: int
    created_at: AwareDatetime | None = None
    password: str | None = None


class Child(BaseObject):
    child_field: str | None = None
