# generated by datamodel-codegen:
#   filename:  read_only_write_only_empty_base.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class EmptyBase(BaseModel):
    pass


class HasFieldBase(BaseModel):
    base_field: str | None = None


class ChildRequest(BaseModel):
    base_field: str | None = None


class Child(EmptyBase, HasFieldBase):
    id: int | None = None
