# generated by datamodel-codegen:
#   filename:  read_only_write_only.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel


class User(BaseModel):
    id: int
    name: str
    password: str
    created_at: Optional[AwareDatetime] = None
    secret_token: Optional[str] = None
