# generated by datamodel-codegen:
#   filename:  entities.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CatDetails(BaseModel):
    name: str = Field(..., description='Name of this cat')
    birthYear: float = Field(..., description="Year of this cat's birth")


class CatInfo(BaseModel):
    cat_id: str = Field(..., description='ID of this cat')
    details: CatDetails | None = None
