# generated by datamodel-codegen:
#   filename:  special_yaml_keywords.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class None_1(BaseModel):
    pass


class false1(BaseModel):
    pass


class True_1(BaseModel):
    pass


class On(BaseModel):
    pass


class NestedKeywords(BaseModel):
    None_: None_1 = Field(..., alias='None')
    false: false1
    True_: True_1 = Field(..., alias='True')
    on: On
