# generated by datamodel-codegen:
#   filename:  type_alias_forward_ref_multiple.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypeAlias, Union

from pydantic import BaseModel


class RegularModel(BaseModel):
    name: str | None = None


Third: TypeAlias = str


Second: TypeAlias = Union["First", Third, RegularModel]


First: TypeAlias = Second
