# generated by datamodel-codegen:
#   filename:  unique_items_default_set.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class TestModel(Struct):
    tags: set[str] | UnsetType = field(default_factory=lambda: {'tag1', 'tag2'})
    empty_tags: set[str] | UnsetType = field(default_factory=set)
    numbers: set[int] | UnsetType = field(default_factory=lambda: {1, 2, 3})
