# generated by datamodel-codegen:
#   filename:  unique_items_default_set.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class TestModel:
    tags: set[str] | None = field(default_factory=lambda: {'tag1', 'tag2'})
    empty_tags: set[str] | None = field(default_factory=set)
    numbers: set[int] | None = field(default_factory=lambda: {1, 2, 3})
