# generated by datamodel-codegen:
#   filename:  x_enum_names.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum, IntEnum


class CustomerColor(IntEnum):
    BloodOrange = 1
    Sunflower = 2
    LightGreen = 3
    SkyBlue = 4
    Purple = 5


class StringStatus(Enum):
    Pending = 'pending'
    Active = 'active'
    Closed = 'closed'


class PriorityTest(IntEnum):
    VarnameOne = 1
    VarnameTwo = 2


class ShortNames(IntEnum):
    First = 1
    Second = 2
    integer_3 = 3
    integer_4 = 4
