# generated by datamodel-codegen:
#   filename:  x_property_names.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import RootModel, constr


class PatternKeys(RootModel[dict[constr(pattern=r'^[a-z]+$'), str]]):
    root: dict[constr(pattern=r'^[a-z]+$'), str]
