# generated by datamodel-codegen:
#   filename:  person.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import UNSET, Meta, Struct, UnsetType


class Person(Struct, omit_defaults=True, tag='"; builtin_template_data_marker = True #\rprint("never")'):
    firstName: (
        Annotated[str, Meta(description="The person's first name.")] | UnsetType
    ) = UNSET
    lastName: (
        Annotated[str, Meta(description="The person's last name.")] | None | UnsetType
    ) = UNSET
    age: (
        Annotated[
            int,
            Meta(
                description='Age in years which must be equal to or greater than zero.',
                ge=0,
            ),
        ]
        | UnsetType
    ) = UNSET
    friends: list[Any] | UnsetType = UNSET
    comment: None | UnsetType = UNSET
