# generated by datamodel-codegen:
#   filename:  nested.json

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import SupportsIndex, overload

from pydantic import Field, RootModel


class Values(RootModel[list[list[int]]], Sequence[list[int]]):
    root: list[list[int]] = Field(..., title='Values')

    def __iter__(self) -> Iterator[list[int]]:
        return iter(self.root)

    @overload
    def __getitem__(self, index: SupportsIndex) -> list[int]:
        pass

    @overload
    def __getitem__(self, index: slice) -> list[list[int]]:
        pass

    def __getitem__(self, index: SupportsIndex | slice) -> list[int] | list[list[int]]:
        return self.root[index]

    def __len__(self) -> int:
        return len(self.root)
