# generated by datamodel-codegen:
#   filename:  reuse.json

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import SupportsIndex, overload

from pydantic import BaseModel, Field, RootModel


class ItemA(BaseModel):
    value: int


class A(RootModel[list[ItemA]], Sequence[ItemA]):
    root: list[ItemA]

    def __iter__(self) -> Iterator[ItemA]:
        return iter(self.root)

    @overload
    def __getitem__(self, index: SupportsIndex) -> ItemA:
        pass

    @overload
    def __getitem__(self, index: slice) -> list[ItemA]:
        pass

    def __getitem__(self, index: SupportsIndex | slice) -> ItemA | list[ItemA]:
        return self.root[index]

    def __len__(self) -> int:
        return len(self.root)


class Values(RootModel[list[A]], Sequence[A]):
    root: list[A] = Field(..., title='Values')

    def __iter__(self) -> Iterator[A]:
        return iter(self.root)

    @overload
    def __getitem__(self, index: SupportsIndex) -> A:
        pass

    @overload
    def __getitem__(self, index: slice) -> list[A]:
        pass

    def __getitem__(self, index: SupportsIndex | slice) -> A | list[A]:
        return self.root[index]

    def __len__(self) -> int:
        return len(self.root)
