# generated by datamodel-codegen:
#   filename:  union.json

from __future__ import annotations

from pydantic import Field, RootModel


class Values(RootModel[set[int | str]]):
    root: set[int | str] = Field(..., title='Values')
