# generated by datamodel-codegen:
#   filename:  union.json

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import SupportsIndex, overload

from pydantic import Field, RootModel


class Values(RootModel[list[int | str]], Sequence[int | str]):
    root: list[int | str] = Field(..., title='Values')

    def __iter__(self) -> Iterator[int | str]:
        return iter(self.root)

    @overload
    def __getitem__(self, index: SupportsIndex) -> int | str:
        pass

    @overload
    def __getitem__(self, index: slice) -> list[int | str]:
        pass

    def __getitem__(self, index: SupportsIndex | slice) -> int | str | list[int | str]:
        return self.root[index]

    def __len__(self) -> int:
        return len(self.root)
