# generated by datamodel-codegen:
#   filename:  direct.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, Union

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any


class TargetItem(BaseModel):
    first: str


class TargetItem1(BaseModel):
    second: str


class Target1(BaseModel):
    third: str


class Target2(TargetItem, Target1):
    pass


class Target3(TargetItem1, Target1):
    pass


class Target(BaseModel):
    __root__: Union[Target2, Target3]
