# generated by datamodel-codegen:
#   filename:  bytes_full.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from pydantic import Field, RootModel


class Model(RootModel[bytes]):
    root: bytes = Field(..., title='Model')
