# generated by datamodel-codegen:
#   filename:  protobuf-local-import.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ProtoImportChild(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | None = ''


class ProtoImportEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    child: ProtoImportChild | None = None
