# generated by datamodel-codegen:
#   filename:  protobuf-schema-format.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ProtoChild(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None


class ProtoEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    children: list[ProtoChild] | None = Field([], validate_default=True)
