# generated by datamodel-codegen:
#   filename:  stable-surface.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, EmailStr


class OpenApiDecorated(BaseModel):
    openapiId: str | None = None


class WrapperWithoutFormat(BaseModel):
    wrapped: bool | None = None


class User(BaseModel):
    id: str
    email: EmailStr | None = None


class UserCreatedHeaders(BaseModel):
    traceId: str
    attempt: int | None = None


class UserCreatedAckPayload(BaseModel):
    accepted: bool
    reason: str | None = None


class UserCreatedPayload(BaseModel):
    eventId: str
    user: User
