# generated by datamodel-codegen:
#   filename:  unknown-version.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class FallbackModel(BaseModel):
    value: str | None = None
