# generated by datamodel-codegen:
#   filename:  xml-schema-format.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class UserType(BaseModel):
    id: str


class XmlEventsXmlNameEventPayload(RootModel[str]):
    root: str = Field(..., title='Name')


class XmlEventsXmlEventPayload(BaseModel):
    user: UserType
