# generated by datamodel-codegen:
#   filename:  additional_properties_object_schema_with_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class KnownAndObjectExtraAdditionalProperty(BaseModel):
    count: int


class KnownAndObjectExtra(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __pydantic_extra__: dict[str, KnownAndObjectExtraAdditionalProperty]
    name: str
