# generated by datamodel-codegen:
#   filename:  additional_properties_ref_schema_with_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ExtraValue(BaseModel):
    count: int


class KnownAndRefExtra(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __pydantic_extra__: dict[str, ExtraValue]
    name: str
