# generated by datamodel-codegen:
#   filename:  additional_properties_enum_schema_with_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict

from pydantic import BaseModel, ConfigDict


class KnownAndEnumExtraAdditionalProperty(Enum):
    red = 'red'
    blue = 'blue'


class KnownAndEnumExtra(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str


KnownAndEnumExtra.__annotations__['__pydantic_extra__'] = Dict[
    str, KnownAndEnumExtraAdditionalProperty
]
KnownAndEnumExtra.model_rebuild(force=True)
