# generated by datamodel-codegen:
#   filename:  additional_properties_const_schema_with_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Dict, Literal

from pydantic import BaseModel, ConfigDict


class KnownAndConstExtra(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str


KnownAndConstExtra.__annotations__['__pydantic_extra__'] = Dict[str, Literal['red']]
KnownAndConstExtra.model_rebuild(force=True)
