# generated by datamodel-codegen:
#   filename:  additional_properties_self_ref.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict


class Node(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, "Node"],
    }
    name: str


Node.model_rebuild()
