# generated by datamodel-codegen:
#   filename:  additional_properties_array_schema_with_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict


class KnownAndArrayExtra(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str


KnownAndArrayExtra.__annotations__['__pydantic_extra__'] = Dict[str, list[str | int]]
KnownAndArrayExtra.model_rebuild(force=True)
