# generated by datamodel-codegen:
#   filename:  additional_properties_unevaluated_object.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, model_validator


class AdditionalPropertiesUnevaluatedObject(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        extra_values = getattr(self, '__pydantic_extra__', None) or {}

        for extra_key, extra_value in extra_values.items():
            if not (
                (isinstance(extra_value, dict))
                and (
                    (not isinstance(extra_value, dict) or {'id'}.issubset(extra_value))
                )
                and (
                    (
                        not isinstance(extra_value, dict)
                        or 'id' not in extra_value
                        or (
                            lambda extra_value_property_0: isinstance(
                                extra_value_property_0, int
                            )
                            and not isinstance(extra_value_property_0, bool)
                        )(extra_value['id'])
                    )
                )
                and (
                    (
                        not isinstance(extra_value, dict)
                        or all((extra_key in {'id'}) for extra_key in extra_value)
                    )
                )
            ):
                raise ValueError(
                    'additional property ' + extra_key + ' does not match schema'
                )
        return self
