# generated by datamodel-codegen:
#   filename:  alias_generator.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class AliasGeneratorModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    first_name: str
    last_name: str | None = None
    foo_bar: str
    weird_url: int
