# generated by datamodel-codegen:
#   filename:  all_of_ref_self.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class Version(RootModel[None]):
    root: None


class Model(BaseModel):
    version: Version | None = None
