# generated by datamodel-codegen:
#   filename:  all_of_multi_ref_with_property_override.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, constr


class Thing(BaseModel):
    type: str
    name: constr(min_length=1)


class Location(BaseModel):
    address: constr(min_length=5)


class Person(Thing, Location):
    type: str | None = 'playground:Person'
    name: constr(min_length=1) | None = None
    age: int | None = None
