# generated by datamodel-codegen:
#   filename:  all_of_hierarchy_property_not_in_ancestor.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Grandparent(BaseModel):
    name: str | None = None


class Parent(Grandparent):
    category: Any | None = 'parent-category'


class Child(Parent):
    category: Any | None = 'child-category'
