# generated by datamodel-codegen:
#   filename:  all_of_merge_same_property.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Links(BaseModel):
    self: str | None = None
    collection: str | None = None


class Model(BaseModel):
    links: Links


class Links1(BaseModel):
    self: str | None = None


class SelfLink(BaseModel):
    links: Links1


class Links2(BaseModel):
    collection: str | None = None


class CollectionLink(BaseModel):
    links: Links2
