# generated by datamodel-codegen:
#   filename:  all_of_deep_hierarchy_property_override.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, constr


class Entity(BaseModel):
    type: str


class Thing(Entity):
    type: str
    name: constr(min_length=1)


class Person(Thing):
    type: str | None = 'playground:Person'
