# generated by datamodel-codegen:
#   filename:  all_of_merge_boolean_property.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    data: Any | None = None


class Data(BaseModel):
    value: str | None = None


class Base1(BaseModel):
    data: Data | None = None


class Base2(BaseModel):
    data: Any | None = None
