# generated by datamodel-codegen:
#   filename:  allof_root_map_values.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class AllofRootMapValues(RootModel[dict[constr(pattern=r'^x_'), str]]):
    root: dict[constr(pattern=r'^x_'), str] = Field(..., title='AllofRootMapValues')
