# generated by datamodel-codegen:
#   filename:  allof_ref_true_schema.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Anything(RootModel[Any]):
    root: Any


class AllOfRefTrue(RootModel[Anything]):
    root: Anything
