# generated by datamodel-codegen:
#   filename:  allof_type_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class IntNumber(RootModel[int]):
    root: int


class NullableString(RootModel[str]):
    root: str


class ListValue(RootModel[int]):
    root: int


class AllOfTypeIntersection(BaseModel):
    intNumber: IntNumber
    nullableString: NullableString
    listValue: ListValue
