# generated by datamodel-codegen:
#   filename:  allof_root_map_constraint_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint


class AllofRootMapConstraintIntersection(RootModel[dict[str, conint(ge=1)]]):
    root: dict[str, conint(ge=1)] = Field(
        ..., max_length=2, min_length=1, title='AllofRootMapConstraintIntersection'
    )
