# generated by datamodel-codegen:
#   filename:  allof_property_value_schemas.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, RootModel, constr


class Name(RootModel[constr(min_length=1, max_length=16)]):
    root: constr(min_length=1, max_length=16)


class Bag(RootModel[dict[Literal['primary'], int]]):
    root: dict[Literal['primary'], int]


class Values(RootModel[list[str | int]]):
    root: list[str | int]


class Choice(RootModel[str | int]):
    root: str | int


class AllofPropertyValueSchemas(BaseModel):
    name: Name | None = None
    bag: Bag | None = None
    values: Values | None = None
    choice: Choice | None = None
