# generated by datamodel-codegen:
#   filename:  anyof_type_literal_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field, RootModel


class AnyOfTypeLiteralIntersection(RootModel[Literal['ok']]):
    root: Literal['ok'] = Field(..., title='AnyOfTypeLiteralIntersection')
