# generated by datamodel-codegen:
#   filename:  anyof_const_with_constraints.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, conint


class Model(BaseModel):
    SomeValue: Literal[500000] | conint(ge=0, le=65534) | None = None
