# generated by datamodel-codegen:
#   filename:  builtin_field_names_target_python_version.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    ExceptionGroup_: ExceptionGroup | None = Field(None, alias='ExceptionGroup')
    BaseExceptionGroup_: BaseExceptionGroup | None = Field(
        None, alias='BaseExceptionGroup'
    )
    PythonFinalizationError_: PythonFinalizationError | None = Field(
        None, alias='PythonFinalizationError'
    )
