# generated by datamodel-codegen:
#   filename:  collapse_root_models_dict_key_self_reference.json

from __future__ import annotations

from typing import Any, Union

from pydantic import BaseModel, RootModel


class JsonValue(RootModel[Union[str, list["JsonValue"]]]):
    root: Union[str, list["JsonValue"]]


class KeyMap(RootModel[dict["KeyMap", str]]):
    root: dict["KeyMap", str]


class Model(BaseModel):
    value: JsonValue | None = None
    keys: KeyMap | None = None
    missing: Any | None = None


JsonValue.model_rebuild()
