# generated by datamodel-codegen:
#   filename:  collapse_root_models_parse_warning.json

from __future__ import annotations

from typing import Any, Union

from pydantic import BaseModel, RootModel


class JsonValue(RootModel[Union[str, list["JsonValue"]]]):
    root: Union[str, list["JsonValue"]]


class BooleanSchema(RootModel[Any]):
    root: Any


class Model(BaseModel):
    value: JsonValue | None = None


JsonValue.model_rebuild()
