# generated by datamodel-codegen:
#   filename:  collapse_root_models_dict_key_self_reference_legacy.json

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    keys: dict[, str | dict[, str]] | None = None
