# generated by datamodel-codegen:
#   filename:  complex_one_of.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class ModelItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: str


class Model(RootModel[int | list[ModelItem]]):
    root: int | list[ModelItem]
