# generated by datamodel-codegen:
#   filename:  conditional_integer_number_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint


class ConditionalIntegerNumberIntersection(RootModel[conint(ge=2)]):
    root: conint(ge=2) = Field(..., title='ConditionalIntegerNumberIntersection')
