# generated by datamodel-codegen:
#   filename:  const_optional_primitive.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class ConstOptionalPrimitive(BaseModel):
    negated: Literal[True] | None = None
    retries: Literal[3] | None = None
    mode: Literal['fast'] | None = None
    schemaVersion: Literal['1.0.0']
