# generated by datamodel-codegen:
#   filename:  contains_tuple_max_contains_limit.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class ContainsTupleMaxContainsLimit(BaseModel):
    values: tuple[Literal['a']]
