# generated by datamodel-codegen:
#   filename:  custom_base_paths_list.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from mixins import AuditMixin, TimestampMixin


class User(AuditMixin, TimestampMixin):
    name: str
    email: str
