# generated by datamodel-codegen:
#   filename:  custom_template_docstring_escaping.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class CustomTemplateDescription:
    """class description\"\"\"; assert False; \"\"\"still a description"""

    value: str
    safe: str
    other: int
