# SPDX-License-Identifier: MIT
#
# generated by datamodel-codegen:
#   filename:  custom_file_header_schema_description_future.json

from __future__ import annotations

from pydantic import BaseModel


class Foo(BaseModel):
    """
    before
    from __future__ import annotations
    after
    """
