# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, TypeAlias

Model: TypeAlias = Any


@dataclass
class User:
    name: str | None = None
    pets: list[User] = field(default_factory=list)


@dataclass
class Pet:
    name: str | None = None
