# generated by datamodel-codegen:
#   filename:  enum_member_special_defaults.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class Mode(Enum):
    don_t = 'don\'t'
    a_b = 'a-b'


class Quoted(Enum):
    a = 'a'
    field_a_ = '\'a\''


@dataclass
class Model:
    mode: Mode | None = Mode.don_t
    modes: list[Mode] | None = field(default_factory=lambda: [Mode.don_t, Mode.a_b])
    quoted: Quoted | None = Quoted.field_a_
