# generated by datamodel-codegen:
#   filename:  deprecated_dataclass.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass

from typing_extensions import deprecated


@deprecated('LegacyUser is deprecated.')
@dataclass
class LegacyUser:
    name: str
    email: str | None = None
