# generated by datamodel-codegen:
#   filename:  discriminator_with_type_string.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from msgspec import UNSET, Struct, UnsetType


class SystemMessage(Struct, tag_field='role', tag='system'):
    content: str


class UserMessage(Struct, tag_field='role', tag='user'):
    content: str


class Model(Struct):
    message: SystemMessage | UserMessage | UnsetType = UNSET
