# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType


class Type1(Struct, tag_field='type_', tag='a'):
    pass


class Type2(Struct, tag_field='type_', tag='b'):
    ref_type: Annotated[Type1, Meta(description='A referenced type.')] | UnsetType = (
        UNSET
    )


class Type4(Struct, tag_field='type_', tag='d'):
    pass


class Type5(Struct, tag_field='type_', tag='e'):
    pass


class Type3(Struct, tag_field='type_', tag='c'):
    pass


class Response(Struct):
    inner: Annotated[Type1 | Type2 | Type3 | Type4 | Type5, Meta(title='Inner')]
