# generated by datamodel-codegen:
#   filename:  dynamic_ref_in_defs.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class TreeNode(BaseModel):
    value: str | None = None
    children: list[TreeNode] | None = None


class Model(BaseModel):
    __root__: TreeNode


TreeNode.update_forward_refs()
