# generated by datamodel-codegen:
#   filename:  empty_field_name.json

from __future__ import annotations

from typing import Annotated, TypeAlias

from msgspec import UNSET, Meta, Struct, UnsetType, field


class RequiredEmpty(Struct):
    field_: str = field(name='')
    a: str | UnsetType = UNSET


class OptionalEmpty(Struct):
    field_: str | UnsetType = field(name='', default=UNSET)
    a: str | UnsetType = UNSET


class AllOfRequiredEmpty(Struct):
    field_: str = field(name='')
    a: str | UnsetType = UNSET


class AllOfOverrideEmpty(OptionalEmpty):
    field_: str = field(name='')


class ReadWriteEmpty(Struct):
    field_: str = field(name='')
    field__1: int = field(name='field_')
    shared: bool | UnsetType = UNSET


EmptyFieldRoot: TypeAlias = Annotated[RequiredEmpty, Meta(title='EmptyFieldRoot')]
