# generated by datamodel-codegen:
#   filename:  enum_member_typed_defaults.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class StrOne(Enum):
    int_1 = 1
    field_1 = '1'


class IntTwo(Enum):
    field_2 = '2'
    int_2 = 2


class Model(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    str_one: StrOne = '1'
    int_two: IntTwo = 2
