# generated by datamodel-codegen:
#   filename:  enum_member_type_reuse.json

from __future__ import annotations

from enum import Enum, IntEnum

from pydantic import BaseModel, Field


class State(Enum):
    # member_data_types_shared = False
    READY = 'ready'
    IN_PROGRESS = 'in-progress'
    EMPTY = ''


class Rank(IntEnum):
    # member_data_types_shared = False
    ZERO = 0
    ONE = 1
    NEGATIVE_ONE = -1


class Choice(Enum):
    # member_data_types_shared = False
    NONE = None
    ENABLED = True
    INTEGER = 2
    NUMBER = 2.5
    TEXT = 'two'


class EnumMemberTypes(BaseModel):
    state: State
    rank: Rank
    choice: Choice
