# generated by datamodel-codegen:
#   filename:  explicit_alias_names_unicode.json

from __future__ import annotations

from typing import Any

from pydantic import Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType

Text = TypeAliasType("Text", str)


@dataclass
class AliasNames:
    b: Any
    café: Text = Field(..., alias='a')
