# generated by datamodel-codegen:
#   filename:  root.json

from __future__ import annotations

from pydantic import BaseModel


class AnchoredChild(BaseModel):
    name: str | None = None


class LegacyChild(BaseModel):
    count: int | None = None


class ExternalAnchor(BaseModel):
    anchored: AnchoredChild | None = None
    anchored_again: AnchoredChild | None = None
    legacy: LegacyChild | None = None
