# generated by datamodel-codegen:
#   filename:  extras_in_oneof.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class OneofProp(BaseModel):
    shared_prop: str | None = Field(
        None, json_schema_extra={'x-shared': 'shared_value'}
    )
    variant_a_prop: str | None = Field(
        None, json_schema_extra={'x-variant': 'variant_a_value'}
    )


class OneofProp1(BaseModel):
    shared_prop: str | None = Field(
        None, json_schema_extra={'x-shared': 'shared_value'}
    )
    variant_b_prop: int | None = Field(
        None, json_schema_extra={'x-variant': 'variant_b_value'}
    )


class AnyofProp(BaseModel):
    any_a_prop: str | None = Field(None, json_schema_extra={'x-any': 'any_a_value'})


class AnyofProp1(BaseModel):
    any_b_prop: bool | None = Field(None, json_schema_extra={'x-any': 'any_b_value'})


class ExtrasInOneOf(BaseModel):
    simple_prop: str | None = Field(
        None, json_schema_extra={'x-custom': 'simple_value'}
    )
    oneof_prop: OneofProp | OneofProp1 | None = Field(
        None, json_schema_extra={'x-parent-custom': 'parent_value'}
    )
    anyof_prop: AnyofProp | AnyofProp1 | None = None
