# generated by datamodel-codegen:
#   filename:  extras_in_oneof.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, model_validator


class OneofProp(BaseModel):
    shared_prop: str | None = Field(
        None, json_schema_extra={'x-shared': 'shared_value'}
    )
    variant_a_prop: str | None = Field(
        None, json_schema_extra={'x-variant': 'variant_a_value'}
    )


class OneofProp1(BaseModel):
    shared_prop: str | None = Field(
        None, json_schema_extra={'x-shared': 'shared_value'}
    )
    variant_b_prop: int | None = Field(
        None, json_schema_extra={'x-variant': 'variant_b_value'}
    )


class AnyofProp(BaseModel):
    any_a_prop: str | None = Field(None, json_schema_extra={'x-any': 'any_a_value'})


class AnyofProp1(BaseModel):
    any_b_prop: bool | None = Field(None, json_schema_extra={'x-any': 'any_b_value'})


class ExtrasInOneOf(BaseModel):
    simple_prop: str | None = Field(
        None, json_schema_extra={'x-custom': 'simple_value'}
    )
    oneof_prop: OneofProp | OneofProp1 | None = Field(
        None, json_schema_extra={'x-parent-custom': 'parent_value'}
    )
    anyof_prop: AnyofProp | AnyofProp1 | None = None

    @model_validator(mode='before')
    @classmethod
    def validate_json_schema_input_constraints(cls, data):
        if isinstance(data, dict):
            if 'oneof_prop' in data:
                oneof_prop_raw_value = data['oneof_prop']
                if not (
                    (
                        (
                            not isinstance(oneof_prop_raw_value, dict)
                            or 'shared_prop' not in oneof_prop_raw_value
                            or (
                                lambda oneof_prop_raw_value_property_0: isinstance(
                                    oneof_prop_raw_value_property_0, str
                                )
                            )(oneof_prop_raw_value['shared_prop'])
                        )
                    )
                    and (
                        sum(
                            1
                            for matched in (
                                (isinstance(oneof_prop_raw_value, dict))
                                and (
                                    (
                                        not isinstance(oneof_prop_raw_value, dict)
                                        or 'variant_a_prop' not in oneof_prop_raw_value
                                        or (
                                            lambda oneof_prop_raw_value_property_0: isinstance(
                                                oneof_prop_raw_value_property_0, str
                                            )
                                        )(oneof_prop_raw_value['variant_a_prop'])
                                    )
                                ),
                                (isinstance(oneof_prop_raw_value, dict))
                                and (
                                    (
                                        not isinstance(oneof_prop_raw_value, dict)
                                        or 'variant_b_prop' not in oneof_prop_raw_value
                                        or (
                                            lambda oneof_prop_raw_value_property_0: isinstance(
                                                oneof_prop_raw_value_property_0, int
                                            )
                                            and not isinstance(
                                                oneof_prop_raw_value_property_0, bool
                                            )
                                        )(oneof_prop_raw_value['variant_b_prop'])
                                    )
                                ),
                            )
                            if matched
                        )
                        == 1
                    )
                ):
                    raise ValueError('oneof_prop' + ' does not match schema')
        return data
