# generated by datamodel-codegen:
#   filename:  false_reference_fast_path.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, TypeAlias

Never: TypeAlias = Any


EscapedNeverValue: TypeAlias = Any


Allowed: TypeAlias = Any


Indirect: TypeAlias = Never


Text: TypeAlias = str


Escaped1never0value: TypeAlias = Any


@dataclass
class FalseReferenceFastPath:
    any_value: Text | None = None
    one_value: int | None = None
    allowed_value: Allowed | str | None = None
    indirect_value: Indirect | int | None = None
