# generated by datamodel-codegen:
#   filename:  falsy_default_enum_member.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from enum import Enum, IntEnum

from pydantic import BaseModel


class Status(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Name(Enum):
    field_ = ''
    non_empty = 'non-empty'


class Model(BaseModel):
    status: Status | None = Status.integer_0
    name: Name | None = Name.field_
