# generated by datamodel-codegen:
#   filename:  field_type_collision_rename_type.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Fruit_(Enum):
    apple = 'apple'
    banana = 'banana'


class Test(BaseModel):
    Fruit: Fruit_ | None = None
