# generated by datamodel-codegen:
#   filename:  field_has_same_name.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TestObject(BaseModel):
    test_string: str | None = None


class Test(BaseModel):
    TestObject: TestObject | None = Field(None, title='TestObject')
