# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True, kw_only=True)
class Person:
    firstName: str | None = None
    lastName: str | None = None
    age: int | None = None
    friends: list[Any] | None = None
    comment: None = None
