# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass(frozen=True, kw_only=True)
class Person:
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    age: Optional[int] = None
    friends: Optional[List] = None
    comment: None = None
