# generated by datamodel-codegen:
#   filename:  strict_types_coverage.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from decimal import Decimal

from pydantic import BaseModel, Field, StrictStr


class StrictTypesCoverage(BaseModel):
    int_with_range: int | None = Field(None, ge=1, le=100)
    float_with_range: float | None = Field(None, ge=1.5, le=99.9)
    decimal_value: Decimal | None = None
    decimal_with_range: Decimal | None = Field(None, ge=0, le=1000)
    hostname_value: StrictStr | None = Field(
        None,
        pattern='^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]{0,61}[A-Za-z0-9])$',
    )
