# generated by datamodel-codegen:
#   filename:  inheritance_forward_ref.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DogBase(BaseModel):
    name: str | None = Field(None, title='Name')
    woof: bool | None = Field(True, title='Woof')


class PersonBase(BaseModel):
    name: str | None = Field(None, title='Name')


class PersonsBestFriend(BaseModel):
    people: list[Person] | None = Field(None, title='People')
    dogs: list[Dog] | None = Field(None, title='Dogs')
    dog_base: DogBase | None = None
    dog_relationships: DogRelationships | None = None
    person_base: PersonBase | None = None
    person_relationships: PersonRelationships | None = None


class DogRelationships(BaseModel):
    people: list[Person] | None = Field(None, title='People')


class PersonRelationships(BaseModel):
    people: list[Person] | None = Field(None, title='People')


class Dog(DogBase, DogRelationships):
    pass


class Person(PersonBase, PersonRelationships):
    pass


PersonsBestFriend.update_forward_refs()
DogRelationships.update_forward_refs()
PersonRelationships.update_forward_refs()
Dog.update_forward_refs()
Person.update_forward_refs()
