# generated by datamodel-codegen:
#   filename:  integer_fractional_constraints.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class Model(BaseModel):
    ge_field: conint(ge=1) | None = None
    any_multiple: int | None = None
    gt_field: conint(ge=-1) | None = None
    fraction_multiple: conint(multiple_of=3) | None = None
    le_field: conint(le=2) | None = None
    lt_field: conint(le=2) | None = None
