# generated by datamodel-codegen:
#   filename:  collapse_root_models_with_optional.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    field: str | None = None
