# generated by datamodel-codegen:
#   filename:  allof_enum_no_external_ref.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any


class MassUnit(Enum):
    g = 'g'
    kg = 'kg'
    t = 't'
