# generated by datamodel-codegen:
#   filename:  collapse_root_models_transitive_reference_cycle.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, RootModel


class Plain(BaseModel):
    x: int | None = None


class Model(BaseModel):
    a: ModelA | None = None
    b: ModelB | None = None


class ModelA(RootModel[Union[str, Plain, "ModelB"]]):
    root: Union[str, Plain, "ModelB"]


class ModelB(RootModel[float | ModelA]):
    root: float | ModelA


Model.model_rebuild()
ModelA.model_rebuild()
