# generated by datamodel-codegen:
#   filename:  empty_items_array.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Model(BaseModel):
    datum_kwargs: Optional[Dict[str, List[Any]]] = None
    simple_list: Optional[List[Any]] = None
