# generated by datamodel-codegen:
#   filename:  multiple_types_with_object.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class External(BaseModel):
    name: str | None = None


class Config(BaseModel):
    value: int | None = None


class TopLevelMultiType1(BaseModel):
    enabled: bool | None = None


class TopLevelMultiType(BaseModel):
    __root__: TopLevelMultiType1 | bool


class Model(BaseModel):
    external: External | bool | None = None
    config: Config | str | None = None
    top_level_ref: TopLevelMultiType | None = None
