# generated by datamodel-codegen:
#   filename:  root.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class First(BaseModel):
    name: str


class Second(BaseModel):
    count: int


class Local(RootModel[str]):
    root: str


class Root(BaseModel):
    first: First
    second: Second
    local: Local
    child: Child


class Child(BaseModel):
    nested: Nested
    first: First


class Nested(BaseModel):
    child: Child


Root.model_rebuild()
Child.model_rebuild()
