# generated by datamodel-codegen:
#   filename:  collapse_root_models_name_strategy_complex.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class UserWrapper(BaseModel):
    name: str
    email: str | None = None


class AdminWrapper(UserWrapper):
    role: str


class SettingsWrapper(BaseModel):
    theme: str | None = None
    language: str | None = None


class Model(BaseModel):
    user: UserWrapper | None = None
    admin: AdminWrapper | None = None
    settings: SettingsWrapper | None = None
