# generated by datamodel-codegen:
#   filename:  default_values_override.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class Model(RootModel[Any]):
    root: Any


class User(BaseModel):
    name: str
    status: str | None = 'active'
    page: int | None = 1
