# generated by datamodel-codegen:
#   filename:  hierarchical_aliases.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    user_name: Optional[str] = Field(None, alias='name')
    id: Optional[int] = None


class Address(BaseModel):
    address_name: Optional[str] = Field(None, alias='name')
    city: Optional[str] = None


class Root(BaseModel):
    root_name: Optional[str] = Field(None, alias='name')
    user: Optional[User] = Field(None, title='User')
    address: Optional[Address] = Field(None, title='Address')
