# generated by datamodel-codegen:
#   filename:  keep_model_order_field_references.json
#   timestamp: 2019-07-26T00:00:00+00:00

from typing import List, Optional

from pydantic import BaseModel


class Metadata(BaseModel):
    title: Optional[str] = None


class DescriptionType(BaseModel):
    metadata: Optional[List[Metadata]] = None
