# generated by datamodel-codegen:
#   filename:  missing_sentinel.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field
from pydantic.experimental.missing_sentinel import MISSING


class MissingSentinel(BaseModel):
    required: int
    requiredNullable: Optional[int]
    unrequired: Union[int, MISSING] = MISSING
    nullableUnrequired: Union[Optional[int], MISSING] = MISSING
    withDefault: Optional[int] = 1
    nullDefault: Optional[int] = None
    aliased_field: Union[str, MISSING] = Field(MISSING, alias='aliased-field')
