# generated by datamodel-codegen:
#   filename:  model_metadata_base_model_name.json

from __future__ import annotations

from pydantic import BaseModel


class BaseModelModel(BaseModel):
    value: str


class Container(BaseModel):
    base_model: BaseModelModel
