# generated by datamodel-codegen:
#   filename:  msgspec_alias_default_controls.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType


class Item(BaseModel):
    id: int


Numbers = TypeAliasType("Numbers", list[int])


ItemMap = TypeAliasType("ItemMap", dict[str, Item])


class DefaultControls(BaseModel):
    direct: Item | None = Field({'id': 1}, validate_default=True)
    direct_list: list[Item] | None = Field([{'id': 2}], validate_default=True)
    empty_list: list[Item] | None = Field([], validate_default=True)
    numbers: Numbers | None = [1, 2]
    mapping: ItemMap | None = Field({'item': {'id': 3}}, validate_default=True)
    empty_mapping: ItemMap | None = Field({}, validate_default=True)
