# generated by datamodel-codegen:
#   filename:  native_pydantic_renderer.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Profile(BaseModel):
    email: str
    active: bool | None = True


class NativeRendererModel(BaseModel):
    identifier: int
    """Stable identifier."""
    display_name: str | None = Field(None, alias='display-name')
    """Human readable display name."""
    tags: list[str] | None = []
    profile: Profile
