# generated by datamodel-codegen:
#   filename:  nested_lookaround_array.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class LookaroundStringArray(RootModel[list[str]]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: list[constr(pattern=r'^(?=.*[A-Z])(?=.*[0-9]).+$', min_length=1)] = Field(
        ..., description='Array of strings with lookaround pattern applied to items.'
    )


class Model(BaseModel):
    codes: LookaroundStringArray | None = None
