# generated by datamodel-codegen:
#   filename:  nullable_string_enum_null_only_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class NullableStringEnumNullOnlyIntersection(BaseModel):
    value: None
