# generated by datamodel-codegen:
#   filename:  nullable_combined_const_excludes_null_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class OneOfValue(Enum):
    on = 'on'
    off = 'off'


class AnyOfValue(Enum):
    red = 'red'
    blue = 'blue'


class NullableCombinedConstExcludesNullIntersection(BaseModel):
    oneOfValue: OneOfValue
    anyOfValue: AnyOfValue
