# generated by datamodel-codegen:
#   filename:  nullable_object_conditional_required_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class Payload(BaseModel):
    kind: str
    code: conint(le=5)


class NullableObjectConditionalRequiredIntersection(BaseModel):
    payload: Payload | None
