# generated by datamodel-codegen:
#   filename:  nullable_array_count_constraints.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class NullableArrayCountConstraints(BaseModel):
    value: list[Any] | None = Field(..., max_length=3, min_length=2)
