# generated by datamodel-codegen:
#   filename:  nullable_combined_count_constraints.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class NullableCombinedCountConstraints(BaseModel):
    oneOfArray: list[Any] = Field(..., max_length=1, min_length=1)
    allOfAnyArray: list[Any] | None = Field(..., min_length=1)
