# generated by datamodel-codegen:
#   filename:  object_context_alias_validators.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

import re

from pydantic import BaseModel, ConfigDict, Field, model_validator


class ObjectContextAliasValidators(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    credit_card: float | None = Field(None, alias='credit-card')
    billing_address: str | None = Field(None, alias='billing-address')
    x_count: int | None = Field(None, alias='x-count')
    mode_type: str | None = Field(None, alias='mode-type')
    service_code: str | None = Field(None, alias='service-code')

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(mode='python', exclude_unset=True)
            if isinstance(value, (list, tuple)):
                return [json_schema_runtime_value(item) for item in value]
            if isinstance(value, dict):
                return {
                    key: json_schema_runtime_value(item) for key, item in value.items()
                }
            return value

        extra_values = getattr(self, '__pydantic_extra__', None) or {}
        provided_keys = set(self.model_fields_set)
        provided_keys.update(extra_values)
        field_original_names = {
            'credit_card': 'credit-card',
            'billing_address': 'billing-address',
            'x_count': 'x-count',
            'mode_type': 'mode-type',
            'service_code': 'service-code',
        }
        model_data = {
            field_original_names.get(field_name, field_name): json_schema_runtime_value(
                getattr(self, field_name)
            )
            for field_name in self.model_fields_set
        }
        model_data.update(
            {
                key: json_schema_runtime_value(value)
                for key, value in extra_values.items()
            }
        )
        if 'credit_card' in provided_keys:
            missing = {'billing_address'} - provided_keys
            if missing:
                raise ValueError(
                    'credit_card'
                    + ' requires properties: '
                    + ', '.join(sorted(missing))
                )
        if 'credit_card' in provided_keys and not (
            (
                (
                    not isinstance(model_data, dict)
                    or all(
                        (
                            lambda property_key: isinstance(property_key, str)
                            and re.search(
                                '^(credit-card|billing-address|x-count)$', property_key
                            )
                            is not None
                        )(property_key)
                        for property_key in model_data
                    )
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or {'billing-address'}.issubset(model_data)
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or 'billing-address' not in model_data
                    or (
                        lambda model_data_property_1: (
                            isinstance(model_data_property_1, str)
                        )
                        and (
                            isinstance(model_data_property_1, str)
                            and len(model_data_property_1) >= 3
                        )
                    )(model_data['billing-address'])
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or all(
                        re.search('^x-', extra_key) is None
                        or (
                            lambda model_data_pattern_property_0: (
                                isinstance(model_data_pattern_property_0, int)
                                and not isinstance(model_data_pattern_property_0, bool)
                            )
                            and (
                                isinstance(model_data_pattern_property_0, (int, float))
                                and not isinstance(model_data_pattern_property_0, bool)
                                and model_data_pattern_property_0 >= 1
                            )
                        )(extra_value)
                        for extra_key, extra_value in model_data.items()
                    )
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or all(
                        (extra_key in {'credit-card', 'billing-address'})
                        or (re.search('^x-', extra_key) is not None)
                        for extra_key in model_data
                    )
                )
            )
        ):
            raise ValueError('credit_card' + ' requires dependent schema to match')

        if (
            (not isinstance(model_data, dict) or {'mode-type'}.issubset(model_data))
        ) and (
            (
                not isinstance(model_data, dict)
                or 'mode-type' not in model_data
                or (lambda model_data_property_0: model_data_property_0 == 'strict')(
                    model_data['mode-type']
                )
            )
        ):
            if not (
                (
                    (
                        not isinstance(model_data, dict)
                        or {'service-code'}.issubset(model_data)
                    )
                )
                and (
                    (
                        not isinstance(model_data, dict)
                        or 'service-code' not in model_data
                        or (
                            lambda model_data_property_1: (
                                isinstance(model_data_property_1, str)
                            )
                            and (
                                isinstance(model_data_property_1, str)
                                and re.search('^S-', model_data_property_1) is not None
                            )
                        )(model_data['service-code'])
                    )
                )
                and (
                    (
                        not isinstance(model_data, dict)
                        or all(
                            (extra_key in {'mode-type', 'service-code', 'x-count'})
                            for extra_key in model_data
                        )
                    )
                )
            ):
                raise ValueError('then schema must match')

        if (
            (not isinstance(model_data, dict) or {'bad-code'}.issubset(model_data))
        ) and (
            (
                not isinstance(model_data, dict)
                or 'bad-code' not in model_data
                or (lambda model_data_property_0: model_data_property_0 is True)(
                    model_data['bad-code']
                )
            )
        ):
            raise ValueError('not schema must not match')
        return self
