# generated by datamodel-codegen:
#   filename:  object_context_schema_validators.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

import re

from pydantic import BaseModel, ConfigDict, model_validator


class ObjectContextSchemaValidators(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    mode: str | None = None
    code: str | None = None
    flag: bool | None = None
    loose: bool | None = None

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(mode='python')
            return value

        extra_values = getattr(self, '__pydantic_extra__', None) or {}
        provided_keys = set(self.model_fields_set)
        provided_keys.update(extra_values)
        model_data = {
            field_name: json_schema_runtime_value(getattr(self, field_name))
            for field_name in self.model_fields_set
        }
        model_data.update(
            {
                key: json_schema_runtime_value(value)
                for key, value in extra_values.items()
            }
        )
        if 'flag' in provided_keys and not (
            ((not isinstance(model_data, dict) or len(model_data) >= 2))
            and (
                (
                    not isinstance(model_data, dict)
                    or all(
                        (
                            lambda property_key: isinstance(property_key, str)
                            and re.search('^(mode|code|flag|x-[a-z]+)$', property_key)
                            is not None
                        )(property_key)
                        for property_key in model_data
                    )
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or all(
                        re.search('^x-', extra_key) is None
                        or (
                            lambda model_data_pattern_property_0: (
                                isinstance(model_data_pattern_property_0, int)
                                and not isinstance(model_data_pattern_property_0, bool)
                            )
                            and (
                                isinstance(model_data_pattern_property_0, (int, float))
                                and not isinstance(model_data_pattern_property_0, bool)
                                and model_data_pattern_property_0 >= 1
                            )
                        )(extra_value)
                        for extra_key, extra_value in model_data.items()
                    )
                )
            )
            and (
                (
                    not isinstance(model_data, dict)
                    or all(
                        (extra_key in {'mode', 'code', 'flag'})
                        or (re.search('^x-', extra_key) is not None)
                        for extra_key in model_data
                    )
                )
            )
        ):
            raise ValueError('flag' + ' requires dependent schema to match')

        if ((not isinstance(model_data, dict) or {'mode'}.issubset(model_data))) and (
            (
                not isinstance(model_data, dict)
                or 'mode' not in model_data
                or (lambda model_data_property_0: model_data_property_0 == 'strict')(
                    model_data['mode']
                )
            )
        ):
            if not (
                ((not isinstance(model_data, dict) or {'code'}.issubset(model_data)))
                and (
                    (
                        not isinstance(model_data, dict)
                        or 'code' not in model_data
                        or (
                            lambda model_data_property_1: (
                                isinstance(model_data_property_1, str)
                            )
                            and (
                                isinstance(model_data_property_1, str)
                                and re.search('^S-', model_data_property_1) is not None
                            )
                        )(model_data['code'])
                    )
                )
                and (
                    (
                        not isinstance(model_data, dict)
                        or all(
                            re.search('^x-', extra_key) is None
                            or (
                                lambda model_data_pattern_property_0: (
                                    isinstance(model_data_pattern_property_0, int)
                                    and not isinstance(
                                        model_data_pattern_property_0, bool
                                    )
                                )
                                and (
                                    isinstance(
                                        model_data_pattern_property_0, (int, float)
                                    )
                                    and not isinstance(
                                        model_data_pattern_property_0, bool
                                    )
                                    and model_data_pattern_property_0 >= 1
                                )
                            )(extra_value)
                            for extra_key, extra_value in model_data.items()
                        )
                    )
                )
                and (
                    (
                        not isinstance(model_data, dict)
                        or all(
                            (extra_key in {'mode', 'code'})
                            or (re.search('^x-', extra_key) is not None)
                            for extra_key in model_data
                        )
                    )
                )
            ):
                raise ValueError('then schema must match')
        else:
            if not (
                (
                    (
                        not isinstance(model_data, dict)
                        or 'code' not in model_data
                        or (
                            lambda model_data_property_3: (
                                isinstance(model_data_property_3, str)
                            )
                            and (
                                isinstance(model_data_property_3, str)
                                and re.search('^L-', model_data_property_3) is not None
                            )
                        )(model_data['code'])
                    )
                )
                and (
                    (
                        not isinstance(model_data, dict)
                        or all(
                            (
                                lambda extra_value: (
                                    isinstance(extra_value, int)
                                    and not isinstance(extra_value, bool)
                                )
                                and (
                                    isinstance(extra_value, (int, float))
                                    and not isinstance(extra_value, bool)
                                    and extra_value >= 0
                                )
                            )(extra_value)
                            for extra_key, extra_value in model_data.items()
                            if not ((extra_key in {'mode', 'flag', 'loose', 'code'}))
                        )
                    )
                )
            ):
                raise ValueError('else schema must match')

        if ((not isinstance(model_data, dict) or len(model_data) >= 1)) and (
            (
                not isinstance(model_data, dict)
                or all(
                    (
                        lambda property_key: isinstance(property_key, str)
                        and re.search('^bad$', property_key) is not None
                    )(property_key)
                    for property_key in model_data
                )
            )
        ):
            raise ValueError('not schema must not match')
        return self
