# generated by datamodel-codegen:
#   filename:  oneof_const_enum_nested.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class Config(BaseModel):
    mode: Optional[Literal['fast', 'slow']] = Field(None, title='Mode')
    modes: Optional[List[Literal['a', 'b']]] = None
