# generated by datamodel-codegen:
#   filename:  oneof_const_enum_int_nullable.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import IntEnum

from pydantic import Field, RootModel


class OptionalCountEnum(IntEnum):
    one = 1
    two = 2


class OptionalCount(RootModel[OptionalCountEnum | None]):
    root: OptionalCountEnum | None = Field(None, title='Optional Count')
