# generated by datamodel-codegen:
#   filename:  oneof_const_enum_type_list_no_null.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum


class MultiType(Enum):
    value1 = 'value1'
    value2 = 'value2'
