# generated by datamodel-codegen:
#   filename:  oneof_const_enum_nested.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Mode(Enum):
    fast = 'fast'
    slow = 'slow'


class Mode1(Enum):
    a = 'a'
    b = 'b'


class Config(BaseModel):
    mode: Mode | None = Field(None, title='Mode')
    modes: list[Mode1] | None = None
