# generated by datamodel-codegen:
#   filename:  pattern_properties_by_reference.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Stt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = Field(None, title='STT Timeout')


class TextResponse(RootModel[dict[constr(pattern=r'^[a-z]{1}[0-9]{1}$'), Any]]):
    root: dict[constr(pattern=r'^[a-z]{1}[0-9]{1}$'), Any]


class SomeschemaSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    KeyWithExplicitPatternProperties: (
        dict[constr(pattern=r'^[a-z]{1}[0-9]{1}$'), Any] | None
    ) = None
    KeyWithPatternPropertiesByReference: TextResponse | None = None
    SomeOtherBoringReference: Stt | None = None
