# generated by datamodel-codegen:
#   filename:  pattern_properties_all_false.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import RootModel


class Model(RootModel[None]):
    root: None
