# generated by datamodel-codegen:
#   filename:  property_names_pattern_properties_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, conint, constr


class PropertyNamesPatternPropertiesIntersection(BaseModel):
    scores: dict[constr(pattern=r'^x_', min_length=4), conint(ge=1)]
