# generated by datamodel-codegen:
#   filename:  property_names_min_max_length.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class LengthKeys(RootModel[dict[constr(min_length=2, max_length=10), int]]):
    root: dict[constr(min_length=2, max_length=10), int] = Field(
        ..., title='LengthKeys'
    )
