# generated by datamodel-codegen:
#   filename:  pydantic_v2_dataclass_dict_default_edge_cases.json

from __future__ import annotations

from typing import ClassVar

from pydantic.dataclasses import dataclass


@dataclass
class Payload:
    required_value: dict[str, int]
    class_value: ClassVar[dict[str, int] | None] = {}
    count: int | None = 1
