# generated by datamodel-codegen:
#   filename:  recursive_fixed_length_array.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class RecursiveFixedLengthArray(RootModel[tuple[Any, Any]]):
    root: tuple[Any, Any] = Field(..., title='RecursiveFixedLengthArray')
