# generated by datamodel-codegen:
#   filename:  ref_sibling_constraint_intersection.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, conint, constr


class RefSiblingConstraintIntersection(BaseModel):
    relaxedCode: constr(min_length=2, max_length=4) | None = None
    strictCode: constr(min_length=3, max_length=3) | None = None
    relaxedMap: dict[constr(pattern=r'^x_'), conint(ge=1)] | None = Field(
        None, max_length=2, min_length=1
    )
    strictMap: dict[constr(pattern=r'^x_', min_length=4), conint(ge=2)] | None = Field(
        None, max_length=1, min_length=1
    )


class ShortCode(RootModel[constr(min_length=2, max_length=4)]):
    root: constr(min_length=2, max_length=4)


class BoundedMap(RootModel[dict[constr(pattern=r'^x_'), conint(ge=1)]]):
    root: dict[constr(pattern=r'^x_'), conint(ge=1)] = Field(
        ..., max_length=2, min_length=1
    )
