# generated by datamodel-codegen:
#   filename:  ref_nullable_import_fast_path.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    name: str


class RefNullableImportFastPath(BaseModel):
    maybe_user: Optional[User]
