# generated by datamodel-codegen:
#   filename:  ref_with_const.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel


class Status(Enum):
    active = 'active'
    inactive = 'inactive'


class NullableStatus(Enum):
    active = 'active'
    inactive = 'inactive'


class Model(BaseModel):
    status: Literal['active']
    nullable_status: Literal['active'] = 'active'
