# generated by datamodel-codegen:
#   filename:  ref_nullable_with_nonstandard_metadata.yaml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    name: str | None = None


class Model(BaseModel):
    user: User | None = None
