# generated by datamodel-codegen:
#   filename:  https://example.com/schemas/root.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Person(BaseModel):
    name: str | None = None


class RemoteRoot(BaseModel):
    person: Person | None = None
