# generated by datamodel-codegen:
#   filename:  required_and_any_of_required.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Foo(BaseModel):
    bar: int
    baz: int
    qux: int | None = None


class Foo1(BaseModel):
    bar: int
    baz: int | None = None
    qux: int


class Model(BaseModel):
    foo: Foo | Foo1
