# generated by datamodel-codegen:
#   filename:  reserved_field_name_schema.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ModelWithSchemaField(BaseModel):
    schema_: str = Field(
        ...,
        alias='schema',
        description="A field named 'schema' that should not be renamed in non-Pydantic models",
    )
    name: str
