# generated by datamodel-codegen:
#   filename:  reserved_property.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ReservedNames(BaseModel):
    json_: str = Field(..., alias='json')
    schema_: str = Field(..., alias='schema')
    dict_: int = Field(..., alias='dict')
