# generated by datamodel-codegen:
#   filename:  resolve_ref_cache_fast_path.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    name: str


class ResolveRefCacheFastPath(BaseModel):
    first: User
    second: User
