# generated by datamodel-codegen:
#   filename:  reuse_model_inline_definitions.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Pos(BaseModel):
    start: int | None = None
    end: int | None = None


class Node1(BaseModel):
    pos: Pos | None = None


class Model(BaseModel):
    node1: Node1 | None = None
    node2: Node1 | None = None
    node3: Node1 | None = None
