# generated by datamodel-codegen:
#   filename:  reuse_model_inline_definitions.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic.dataclasses import dataclass


@dataclass(frozen=True, kw_only=True)
class Pos:
    start: int | None = None
    end: int | None = None


@dataclass(frozen=True, kw_only=True)
class Node1:
    pos: Pos | None = None


@dataclass(frozen=True, kw_only=True)
class Node2(Node1):
    pass


@dataclass(frozen=True, kw_only=True)
class Node3(Node1):
    pass


@dataclass(frozen=True, kw_only=True)
class Model:
    node1: Node1 | None = None
    node2: Node2 | None = None
    node3: Node3 | None = None
