# generated by datamodel-codegen:
#   filename:  root_array_unevaluated_items_contains_validators.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint, model_validator


class RootArrayUnevaluatedItemsContainsValidators(RootModel[list[str | conint(ge=1)]]):
    root: list[str | conint(ge=1)] = Field(
        ..., title='root array unevaluated items contains validators'
    )

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(
                    mode='python', by_alias=True, exclude_unset=True
                )
            if isinstance(value, (list, tuple)):
                return [json_schema_runtime_value(item) for item in value]
            if isinstance(value, dict):
                return {
                    key: json_schema_runtime_value(item) for key, item in value.items()
                }
            return value

        if self.root is not None:
            root_match_count = sum(
                1
                for item in self.root
                if (
                    lambda item: (isinstance(item, int) and not isinstance(item, bool))
                    and (
                        isinstance(item, (int, float))
                        and not isinstance(item, bool)
                        and item >= 1
                    )
                )(json_schema_runtime_value(item))
            )
            if root_match_count < 1:
                raise ValueError('root' + ' must contain at least 1 matching item(s)')

        if self.root is not None and not (
            (
                (
                    not isinstance(self.root, list)
                    or len(self.root) <= 0
                    or (lambda extra_item: isinstance(extra_item, str))(self.root[0])
                )
            )
            and (
                (
                    not isinstance(self.root, list)
                    or all(
                        (
                            lambda extra_item: (
                                isinstance(extra_item, int)
                                and not isinstance(extra_item, bool)
                            )
                            and (
                                isinstance(extra_item, (int, float))
                                and not isinstance(extra_item, bool)
                                and extra_item >= 1
                            )
                        )(extra_item)
                        for extra_item in self.root[1:]
                    )
                )
            )
        ):
            raise ValueError('root' + ' does not match array schema')
        return self
