# generated by datamodel-codegen:
#   filename:  root_model_with_additional_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class CustomNestedObjectResult(BaseModel):
    status: int


class CustomNestedEnumResult(Enum):
    red = 'red'
    green = 'green'


class CustomOneOfResult(BaseModel):
    description: str | None = None


class CustomAnyOfResult(BaseModel):
    description: str | None = None


class CustomUser(BaseModel):
    name: str | None = None


class CustomAllOfResult(CustomUser):
    description: str | None = None


class CustomModel(BaseModel):
    test_id: str = Field(..., description='test ID')
    test_ip: str = Field(..., description='test IP')
    result: dict[str, int]
    nested_object_result: dict[str, CustomNestedObjectResult]
    nested_enum_result: dict[str, CustomNestedEnumResult]
    all_of_result: dict[str, CustomAllOfResult] | None = None
    one_of_result: dict[str, CustomUser | CustomOneOfResult] | None = None
    any_of_result: dict[str, CustomUser | CustomAnyOfResult] | None = None
    all_of_with_unknown_object: dict[str, CustomUser] | None = None
    objectRef: dict[str, CustomUser] | None = None
    deepNestedObjectRef: dict[str, dict[str, dict[str, CustomUser]]] | None = None
