# generated by datamodel-codegen:
#   filename:  root_logical_runtime_validators.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel, model_validator


class RootLogicalRuntimeValidators(RootModel[Any | str]):
    root: Any | str = Field(..., title='root logical runtime validators')

    @model_validator(mode='after')
    def validate_json_schema_constraints(self):
        def json_schema_runtime_value(value):
            if hasattr(value, 'model_dump'):
                return value.model_dump(
                    mode='python', by_alias=True, exclude_unset=True
                )
            if isinstance(value, (list, tuple)):
                return [json_schema_runtime_value(item) for item in value]
            if isinstance(value, dict):
                return {
                    key: json_schema_runtime_value(item) for key, item in value.items()
                }
            return value

        root_value = json_schema_runtime_value(self.root)
        if not (
            (sum(1 for matched in (True, isinstance(root_value, str)) if matched) == 1)
            and (not (root_value is None))
        ):
            raise ValueError('root object does not match schema')
        return self
