# generated by datamodel-codegen:
#   filename:  root_model_default_value_branches.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, Field, RootModel


class CountType(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=100)]


class Model(BaseModel):
    count_with_default: Annotated[
        Optional[CountType],
        Field(default_factory=lambda: CountType.model_validate(CountType(10))),
    ]
    count_no_default: Optional[CountType] = None
    count_list_default: Annotated[
        Optional[List[CountType]],
        Field(default_factory=lambda: [CountType.model_validate(v) for v in [1, 2, 3]]),
    ]
