# generated by datamodel-codegen:
#   filename:  same_file_ref_fast_path.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    name: str


class SameFileRefFastPath(BaseModel):
    user: User
