# generated by datamodel-codegen:
#   filename:  schema_id.json
#   timestamp: 1985-10-26T08:21:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    __schema_id__: ClassVar[str] = "https://example.com/schemas/user"
    __path__: ClassVar[str] = "#"
    id: str
    name: str


class Address(BaseModel):
    __schema_id__: ClassVar[str] = "#address"
    __path__: ClassVar[str] = "#/definitions/Address"
    street: str
    city: str | None = None
