# generated by datamodel-codegen:
#   filename:  schema_version_strict_nullable.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class NullableString(RootModel[str | None]):
    root: str | None = None


class Root(BaseModel):
    item: NullableString | None = None
