# generated by datamodel-codegen:
#   filename:  schema_version_strict_password.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel, SecretStr


class PasswordField(RootModel[SecretStr]):
    root: SecretStr


class Root(BaseModel):
    secret: PasswordField | None = None
