# generated by datamodel-codegen:
#   filename:  selective_constraint_kwargs.json

from __future__ import annotations

from pydantic import BaseModel, conbytes, conint, constr


class SelectiveConstraintKwargs(BaseModel):
    count: conint(ge=1, le=9, multiple_of=2)
    name: constr(pattern=r'^[A-Z]+$', min_length=2, max_length=8)
    payload: conbytes(min_length=4, max_length=12)
    enabled: bool
