# generated by datamodel-codegen:
#   filename:  special_enum.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class ModelEnum(Enum):
    True_ = True
    False_ = False
    special_ = ''
    special__1 = '\n'
    special__ = '\r\n'
    special__2 = '\t'
    special_x08 = '\\x08'
    special__3 = '\\'


class Model(BaseModel):
    __root__: ModelEnum | None = None
