# generated by datamodel-codegen:
#   filename:  special_enum.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import RootModel


class ModelEnum(Enum):
    True_ = True
    False_ = False
    field_ = ''
    field__1 = '\n'
    field__ = '\r\n'
    field__2 = '\t'
    field_x08 = '\\x08'
    field__3 = '\\'


class Model(RootModel[ModelEnum | None]):
    root: ModelEnum | None = None
