# generated by datamodel-codegen:
#   filename:  special_field_name.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SpecialField(BaseModel):
    global_: str | None = Field(None, alias='global')
    with_: str | None = Field(None, alias='with')
    class_: int | None = Field(None, alias='class')
    class_s: int | None = Field(None, alias="class's")
    class_s_1: str | None = Field(None, alias='class-s')
    field_: str | None = Field(None, alias='#')
