# generated by datamodel-codegen:
#   filename:  string_dict.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class MyStringDict(BaseModel):
    __root__: dict[str, str]
