# generated by datamodel-codegen:
#   filename:  typed_dict_closed.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing_extensions import NotRequired, TypedDict


class ClosedModel(TypedDict, closed=True):
    name: str
    age: NotRequired[int]
