# generated by datamodel-codegen:
#   filename:  type_alias_inline_union_default_object_one_of.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class A(BaseModel):
    type: Literal['a'] | None = None


class B(BaseModel):
    type: Literal['b'] | None = None


class Model(BaseModel):
    x_value: Annotated[A | B | None, Field(validate_default=True)] = {'type': 'b'}
