# generated by datamodel-codegen:
#   filename:  non_finite_number_values.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired


class Model(TypedDict):
    big_default: NotRequired[float]
    small_default: NotRequired[float]
    big_min: NotRequired[float]
