# generated by datamodel-codegen:
#   filename:  type_alias.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated, Any, TypeAlias

from pydantic import BaseModel, Field

Model: TypeAlias = Any


SimpleString: TypeAlias = str


UnionType: TypeAlias = str | int


ArrayType: TypeAlias = list[str]


AnnotatedType: TypeAlias = Annotated[str | bool, Field(..., title='MyAnnotatedType')]
"""
An annotated union type
"""


class ModelWithTypeAliasField(BaseModel):
    simple_field: SimpleString | None = None
    union_field: UnionType | None = None
    array_field: ArrayType | None = None
    annotated_field: AnnotatedType | None = None
