# generated by datamodel-codegen:
#   filename:  type_alias.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated, Any, List, Optional, Union

from pydantic import BaseModel, Field

type Model = Any


type SimpleString = str


type UnionType = Union[str, int]


type ArrayType = List[str]


type AnnotatedType = Annotated[Union[str, bool], Field(..., title='MyAnnotatedType')]
"""
An annotated union type
"""


class ModelWithTypeAliasField(BaseModel):
    simple_field: Optional[SimpleString] = None
    union_field: Optional[UnionType] = None
    array_field: Optional[ArrayType] = None
    annotated_field: Optional[AnnotatedType] = None
