# generated by datamodel-codegen:
#   filename:  typed_dict_mixed_closed.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Any, TypeAlias

from typing_extensions import NotRequired, TypedDict

Model: TypeAlias = Any


class ClosedModel(TypedDict, closed=True):
    name: str


class OpenModel(TypedDict):
    value: NotRequired[str]
