# generated by datamodel-codegen:
#   filename:  type_alias_forward_ref.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypedDict

from typing_extensions import TypeAliasType


class BlobPart(TypedDict):
    type: Literal['blob']
    data: str


FieldPlaceholder = TypeAliasType("FieldPlaceholder", None)


class TextPart(TypedDict):
    type: Literal['text']
    content: str


SystemInstructions = TypeAliasType("SystemInstructions", list[TextPart | BlobPart])
