# generated by datamodel-codegen:
#   filename:  type_alias_forward_ref.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict, Union


class BlobPart(TypedDict):
    type: Literal['blob']
    data: str


FieldPlaceholder: TypeAlias = None


class TextPart(TypedDict):
    type: Literal['text']
    content: str


SystemInstructions: TypeAlias = list[Union[TextPart, BlobPart]]
