# generated by datamodel-codegen:
#   filename:  type_array_only_null.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    requiredNull: None
    optionalNull: None = None
