# generated by datamodel-codegen:
#   filename:  unevaluated_properties_true.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class Resource(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
