# generated by datamodel-codegen:
#   filename:  unique_items_enum_set.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Status(Enum):
    active = 'active'
    inactive = 'inactive'
    pending = 'pending'


class Item(BaseModel):
    __hash__ = object.__hash__
    name: str | None = None


class Container(BaseModel):
    statuses: set[Status] | None = None
    items: set[Item] | None = None
