# generated by datamodel-codegen:
#   filename:  use_generic_base_class_enum_only.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any


class MyEnum(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
