# generated by datamodel-codegen:
#   filename:  uuid_format_versions.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import UUID1, UUID3, UUID4, UUID5, BaseModel


class Model(BaseModel):
    u: UUID | None = None
    u1: UUID1 | None = None
    u2: UUID | None = None
    u3: UUID3 | None = None
    u4: UUID4 | None = None
    u5: UUID5 | None = None
