# generated by datamodel-codegen:
#   filename:  x_python_type_compatible_set.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired


class Model(TypedDict):
    items: NotRequired[set[str]]
