# generated by datamodel-codegen:
#   filename:  x_python_type_target_backports.json

from __future__ import annotations

from typing import TypedDict

from typing_extensions import (
    Buffer,
    LiteralString,
    Never,
    NoDefault,
    NotRequired,
    ReadOnly,
    Required,
    Self,
    TypeAliasType,
    TypeForm,
    TypeIs,
    TypeVarTuple,
    Unpack,
    override,
)


class TargetBackportModel(TypedDict):
    buffer: Buffer
    qualifiers_a: tuple[LiteralString, Never, NotRequired[str]]
    qualifiers_b: tuple[ReadOnly[str], Required[str], Self]
    aliases: tuple[TypeAliasType, TypeIs[str], TypeVarTuple, Unpack[tuple[str]]]
    qualified_type_is: TypeIs[str]
    future: tuple[override, NoDefault, TypeForm[str]]
