# generated by datamodel-codegen:
#   filename:  x_python_type_callable.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from collections.abc import Callable
from typing import TypedDict

from typing_extensions import NotRequired


class Model(TypedDict):
    callback: NotRequired[Callable[[str], str]]
