from datamodel_code_generator.imports import Import

IMPORT_STRING = Import.from_full_path('schematics.types.StringType')
IMPORT_INT = Import.from_full_path('schematics.types.IntType')
IMPORT_FLOAT = Import.from_full_path('schematics.types.FloatType')
IMPORT_DECIMAL = Import.from_full_path('schematics.types.DecimalType')
IMPORT_BOOLEAN = Import.from_full_path('schematics.types.BooleanType')
IMPORT_ANY = Import.from_full_path('schematics.types.BaseType')
IMPORT_LIST = Import.from_full_path('schematics.types.ListType')
IMPORT_SEQUENCE = Import.from_full_path('schematics.types.ListType')
IMPORT_ENUM = Import.from_full_path('enum.Enum')
IMPORT_ANNOTATIONS = Import.from_full_path('__future__.annotations')
IMPORT_DICT = Import.from_full_path('schematics.types.DictType')
IMPORT_DATE = Import.from_full_path('schematics.types.DateType')
#IMPORT_DATETIME = Import.from_full_path('schematics.types.DateTimeType')
IMPORT_DATETIME = Import.from_full_path('applications.models.custom_types.DateTimeType')

IMPORT_TIME = Import.from_full_path('schematics.types.DateTimeType')
IMPORT_UUID = Import.from_full_path('schematics.types.UUIDType')
IMPORT_MODEL = Import.from_full_path('schematics.types.ModelType')


IMPORT_CONSTR = Import.from_full_path('schematics.types.StringType')
IMPORT_CONINT = Import.from_full_path('schematics.types.IntType')
IMPORT_CONFLOAT = Import.from_full_path('schematics.types.FloatType')
IMPORT_CONDECIMAL = Import.from_full_path('schematics.types.DecimalType')
IMPORT_CONBYTES = Import.from_full_path('schematics.types.IntType')
IMPORT_POSITIVE_INT = Import.from_full_path('schematics.types.IntType')
IMPORT_NEGATIVE_INT = Import.from_full_path('schematics.types.IntType')
IMPORT_POSITIVE_FLOAT = Import.from_full_path('schematics.types.FloatType')
IMPORT_NEGATIVE_FLOAT = Import.from_full_path('schematics.types.FloatType')
IMPORT_SECRET_STR = Import.from_full_path('schematics.types.StringType')
IMPORT_EMAIL_STR = Import.from_full_path('schematics.types.EmailType')
IMPORT_UUID1 = Import.from_full_path('schematics.types.UUIDType')
IMPORT_UUID2 = Import.from_full_path('schematics.types.UUIDType')
IMPORT_UUID3 = Import.from_full_path('schematics.types.UUIDType')
IMPORT_UUID4 = Import.from_full_path('schematics.types.UUIDType')
IMPORT_UUID5 = Import.from_full_path('schematics.types.UUIDType')
IMPORT_ANYURL = Import.from_full_path('schematics.types.URLType')
IMPORT_IPV4ADDRESS = Import.from_full_path('schematics.types.IPv4Type')
IMPORT_IPV6ADDRESS = Import.from_full_path('pschematics.types.IPv6Type')
IMPORT_EXTRA = Import.from_full_path('schematics.types.BaseType')
IMPORT_FIELD = Import.from_full_path('schematics.types.BaseType')
IMPORT_STRICT_INT = Import.from_full_path('schematics.types.IntType')
IMPORT_STRICT_FLOAT = Import.from_full_path('schematics.types.FloatType')
IMPORT_STRICT_STR = Import.from_full_path('schematics.types.StringType')
IMPORT_STRICT_BOOL = Import.from_full_path('schematics.types.BooleanType')
IMPORT_STRICT_BYTES = Import.from_full_path('schematics.types.IntType')
