# Generated by scripts/compile_builtin_templates.py; do not edit directly.
# Source: PydanticV2TypeAlias.jinja2 (sha256:295d39d20574add4)
from __future__ import annotations

from typing import Any

from datamodel_code_generator.model._compiled_template_runtime import (
    Scope as _Scope,
    getattr_ as _getattr,
    getitem as _getitem,
)

from .typealiasannotation import render_with_scope as _include_0
from .typealiastype import render_with_scope as _include_1


def render(**context: Any) -> str:
    return render_with_scope(_Scope(context))


def render_with_scope(_scope: _Scope) -> str:
    _context_fields = _scope.get("fields")
    _parts: list[str] = []
    if _context_fields and _getattr(_getattr(_getitem(_context_fields, 0), "data_type"), "reference"):
        _include_scope_0 = _scope.child()
        _parts.append(_include_0(_include_scope_0))
    else:
        _include_scope_1 = _scope.child()
        _parts.append(_include_1(_include_scope_1))
    return "".join(_parts)
