# Generated by scripts/compile_builtin_templates.py; do not edit directly.
# Source: pydantic_v2/schema_runtime_validation_helpers.jinja2 (sha256:02466160c81907f0)
from __future__ import annotations

from typing import Any

from datamodel_code_generator.model._compiled_template_runtime import (
    Scope as _Scope,
    stringify as _stringify,
)


def render(**context: Any) -> str:
    return render_with_scope(_Scope(context))


def render_with_scope(_scope: _Scope) -> str:
    _context_has_conditional_required = _scope.get("has_conditional_required")
    _context_has_pattern_properties = _scope.get("has_pattern_properties")
    _context_has_property_count = _scope.get("has_property_count")
    _context_has_required_groups = _scope.get("has_required_groups")
    _context_schema_runtime_validation_base_class_name = _scope.get("schema_runtime_validation_base_class_name")
    _parts: list[str] = []
    _value_0 = _stringify(_context_schema_runtime_validation_base_class_name)
    _parts.append(f"class {_value_0}(BaseModel):")
    if _context_has_pattern_properties:
        _parts.append("\n    __json_schema_pattern_properties__: ClassVar[tuple[Any, ...]] = ()")
    if _context_has_required_groups:
        _parts.append(
            "\n    __json_schema_one_of_required_groups__: ClassVar[tuple[Any, ...]] = ()\n    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = ()"
        )
    if _context_has_conditional_required:
        _parts.append("\n    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = ()")
    if _context_has_property_count:
        _parts.append("\n    __json_schema_property_count_rule__: ClassVar[tuple[Any, ...]] = ()")
    _parts.append(
        "\n\n    @model_validator(mode='before')\n    @classmethod\n    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:"
    )
    if _context_has_property_count:
        _parts.append("\n        data = cls._validate_json_schema_property_count(data)")
    if _context_has_pattern_properties:
        _parts.append("\n        data = cls._validate_json_schema_pattern_properties(data)")
    if _context_has_required_groups:
        _parts.append(
            "\n        data = cls._validate_json_schema_required_groups(\n            data,\n            required_group_rules=cls.__json_schema_one_of_required_groups__,\n            require_exactly_one=True,\n        )\n        data = cls._validate_json_schema_required_groups(\n            data,\n            required_group_rules=cls.__json_schema_any_of_required_groups__,\n            require_exactly_one=False,\n        )"
        )
    if _context_has_conditional_required:
        _parts.append("\n        data = cls._validate_json_schema_conditional_required(data)")
    _parts.append("\n        return data")
    if _context_has_pattern_properties:
        _parts.append(
            "\n\n    @classmethod\n    def _validate_json_schema_pattern_properties(cls, data: Any) -> Any:\n        if not isinstance(data, dict):\n            return data\n        values = dict(data)\n        for rule in cls.__json_schema_pattern_properties__:\n            for key, value in data.items():\n                if key in rule['declared_properties']:\n                    continue\n                if any(\n                    re.search(pattern, key) for pattern in rule['rejected_patterns']\n                ):\n                    raise ValueError(\n                        f'Property {key!r} is not allowed by patternProperties'\n                    )\n                matched = False\n                for pattern, value_type in rule['pattern_properties']:\n                    if not re.search(pattern, key):\n                        continue\n                    matched = True\n                    value = TypeAdapter(value_type).validate_python(value)\n                if matched:\n                    values[key] = value\n                    continue\n                if rule['additional_property_type'] is not None:\n                    values[key] = TypeAdapter(\n                        rule['additional_property_type']\n                    ).validate_python(value)\n                    continue\n                if not rule['allow_unmatched']:\n                    raise ValueError(f'Unexpected property {key!r}')\n        return values"
        )
    if _context_has_required_groups:
        _parts.append(
            "\n\n    @classmethod\n    def _validate_json_schema_required_groups(\n        cls,\n        data: Any,\n        *,\n        required_group_rules: tuple[Any, ...],\n        require_exactly_one: bool,\n    ) -> Any:\n        if not required_group_rules or not isinstance(data, dict):\n            return data\n        for required_groups in required_group_rules:\n            matches = sum(\n                all(any(name in data for name in names) for names in group)\n                for group in required_groups\n            )\n            if require_exactly_one:\n                if matches != 1:\n                    raise ValueError(\n                        'Expected exactly one required property group to be present'\n                    )\n            elif matches == 0:\n                raise ValueError(\n                    'Expected at least one required property group to be present'\n                )\n        return data"
        )
    if _context_has_conditional_required:
        _parts.append(
            "\n\n    @classmethod\n    def _validate_json_schema_conditional_required(cls, data: Any) -> Any:\n        if not isinstance(data, dict):\n            return data\n        for rule in cls.__json_schema_conditional_required__:\n            condition_matches = all(\n                any(name in data and data[name] in expected for name in names)\n                for names, expected in rule['condition']\n            )\n            required_groups = (\n                rule['then_required_groups']\n                if condition_matches\n                else rule['else_required_groups']\n            )\n            for group in required_groups:\n                if all(any(name in data for name in names) for names in group):\n                    continue\n                raise ValueError('Conditional required properties are missing')\n        return data"
        )
    if _context_has_property_count:
        _parts.append(
            "\n\n    @classmethod\n    def _validate_json_schema_property_count(cls, data: Any) -> Any:\n        if not (rule := cls.__json_schema_property_count_rule__) or not isinstance(data, dict):\n            return data\n        property_count = len(data)\n        min_properties, max_properties = rule\n        if min_properties is not None and property_count < min_properties:\n            raise ValueError(f'Expected at least {min_properties} properties')\n        if max_properties is not None and property_count > max_properties:\n            raise ValueError(f'Expected at most {max_properties} properties')\n        return data"
        )
    _value_1 = _stringify("\n\n")
    _parts.append(f"\n{_value_1}")
    return "".join(_parts)
