# generated by datamodel-codegen:
#   filename:  core/platform-extension-ref.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class PlatformExtensionRef(BaseModel):
    uri: str | None = None


class Uri(RootModel[str]):
    root: str
