# generated by datamodel-codegen:
#   filename:  namespace_simple.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class Z(BaseModel):
    f: Z


class Y(BaseModel):
    e: Z


Z.model_rebuild()
