# generated by datamodel-codegen:
#   filename:  union.avsc
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import Field, RootModel


class Model(RootModel[str | int | None]):
    root: str | int | None = Field(..., title='Model')
