# generated by datamodel-codegen:
#   filename:  minimum_maximum.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Root1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    a: int = Field(..., ge=2, le=5)


class Root2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    b: int


class Root(
    RootModel[dict[constr(pattern=r'^x'), Root1] | dict[constr(pattern=r'x$'), Root2]]
):
    root: dict[constr(pattern=r'^x'), Root1] | dict[
        constr(pattern=r'x$'), Root2
    ] = Field(..., title='Root')
