# generated by datamodel-codegen:
#   filename:  minimum_custom.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Root1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )

    a: conint(ge=2)


class Root2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )

    b: int


class Root(
    RootModel[dict[constr(pattern=r'^x'), Root1] | dict[constr(pattern=r'x$'), Root2]]
):

    root: dict[constr(pattern=r'^x'), Root1] | dict[constr(pattern=r'x$'), Root2] = (
        Field(..., title='Root')
    )
