# generated by datamodel-codegen:
#   filename:  suffix_prefix.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Root1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    b: int


class Root2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    a: int


class Root(
    RootModel[dict[constr(pattern=r'y$'), Root1] | dict[constr(pattern=r'^x'), Root2]]
):
    root: dict[constr(pattern=r'y$'), Root1] | dict[constr(pattern=r'^x'), Root2] = (
        Field(..., title='Root')
    )
