# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations
from pydantic import RootModel
from .right.deep import consumer


class Model(RootModel[consumer.Consumer]):
    root: consumer.Consumer
