# generated by datamodel-codegen:
#   filename:  shared.py

from __future__ import annotations

from pydantic import BaseModel, Field


class Inner(BaseModel):
    text: str | None = None
    number: int | None = None
    wire_name: str | None = Field(None, alias='wire-name')
    next: Inner | None = None


Inner.model_rebuild()
