# generated by datamodel-codegen:
#   filename:  jsonschema_alias_default.json

from __future__ import annotations

from msgspec import Struct, UnsetType, field


class A(Struct):
    pass


class B(Struct):
    a_value: str = field(name='a-value')
    note: str | UnsetType = 'saved'


class Payload(A, B, kw_only=True):
    c: int
