# generated by datamodel-codegen:
#   filename:  jsonschema_empty.json

from __future__ import annotations

from msgspec import Struct


class A(Struct):
    pass


class B(Struct):
    a: str


class Payload(A, B):
    c: int
