# generated by datamodel-codegen:
#   filename:  jsonschema_diamond_one.json

from __future__ import annotations

from msgspec import Struct


class A(Struct):
    a: str


class B(A):
    b: int


class D(A):
    pass


class Payload(B, D):
    c: int
