# generated by datamodel-codegen:
#   filename:  jsonschema_imported_root.json

from __future__ import annotations

from msgspec import UnsetType
from msgspec.inspect import IntType


class A(IntType, kw_only=True):
    gt: int | UnsetType = 0


class B(IntType, kw_only=True):
    gt: int | UnsetType = 0


class Payload(A, B, kw_only=True):
    c: int
