# generated by datamodel-codegen:
#   filename:  scoped.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class Base(BaseModel):
    kind: str


class Dog(Base):
    bark: str | None = None
    kind: Literal['dog']


class Cat(Base):
    meow: str | None = None
    kind: Literal['cat']


class Species(Enum):
    cat = 'cat'


class CatModel(BaseModel):
    species: Literal['cat']
    purr: int


class Species1(Enum):
    dog = 'dog'


class Dog1(BaseModel):
    species: Literal['dog']
    woof: int


class BaseModel1(BaseModel):
    species: str


class DogModel(Base):
    bark: str | None = None
    kind: Literal['dog']


class Wrapper(BaseModel):
    local: Dog | Cat = Field(..., discriminator='kind')
    left: DogModel | Cat = Field(..., discriminator='kind')
    right: CatModel | Dog1 = Field(..., discriminator='species')
