# generated by datamodel-codegen:
#   filename:  other.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ModelB(BaseModel):
    id: Optional[int] = None


class Model(BaseModel):
    info: Optional[ModelB] = None
