# generated by datamodel-codegen:
#   filename:  format_float.json

from __future__ import annotations

from pydantic import RootModel


class Root(RootModel[int]):
    root: int


class Base(RootModel[float]):
    root: float
