# generated by datamodel-codegen:
#   filename:  integer_number.json

from __future__ import annotations

from pydantic import RootModel, conint


class Root(RootModel[conint(ge=2, le=10)]):
    root: conint(ge=2, le=10)


class Base(RootModel[conint(ge=0)]):
    root: conint(ge=0)
