# generated by datamodel-codegen:
#   filename:  nullable_child.json

from __future__ import annotations

from pydantic import RootModel, confloat, conint


class Root(RootModel[conint(ge=2)]):
    root: conint(ge=2)


class Base(RootModel[confloat(ge=2.0)]):
    root: confloat(ge=2.0)
