# generated by datamodel-codegen:
#   filename:  nullable_number_same.json

from __future__ import annotations

from pydantic import Field, RootModel


class Root(RootModel[float | None]):
    root: float | None = Field(..., ge=2.0)


class Base(RootModel[float | None]):
    root: float | None = Field(..., ge=2.0)
