# generated by datamodel-codegen:
#   filename:  number_number.json

from __future__ import annotations

from pydantic import RootModel, confloat


class Root(RootModel[confloat(ge=2.0, le=10.0)]):
    root: confloat(ge=2.0, le=10.0)


class Base(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)
