# generated by datamodel-codegen:
#   filename:  direct_tool.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class ReadResourceInput(BaseModel):
    uri: str
