# generated by datamodel-codegen:
#   filename:  servers_list.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class CreateCommentInput(BaseModel):
    issue_id: str
    body: str
