# generated by datamodel-codegen:
#   filename:  server_definition.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class GetUserInput(BaseModel):
    user_id: str


class GetUserOutput(BaseModel):
    name: str
    active: bool
