# generated by datamodel-codegen:
#   filename:  top_level_tool_definitions.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class ArchiveIssueInput(BaseModel):
    issue_id: str
    reason: str | None = None
