# generated by datamodel-codegen:
#   filename:  nested_person.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from pydantic import BaseModel

from .empty_parent.nested import deep as deep_1
from .nested import deep


class NestedPerson(BaseModel):
    nested_deep_childJson: deep.Json | None = None
    nested_deep_childAnother: deep.Another | None = None
    empty_parent_nested_deep_childJson: deep_1.Json | None = None
