# generated by datamodel-codegen:
#   filename:  root_model_with_additional_properties.json
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Dict, Literal

from pydantic import BaseModel, Extra, Field


class Result(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: int


class NestedObjectResult(BaseModel):
    class Config:
        extra = Extra.allow

    status: int


class Model(BaseModel):
    test_id: str = Field(..., description='test ID')
    test_ip: str = Field(..., description='test IP')
    result: Dict[str, Result]
    nested_object_result: Dict[str, NestedObjectResult]
    nested_enum_result: Dict[str, Literal['red', 'green']]
