name: codspeed-benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: codespeed-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  benchmarks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      # uv standalone build is not compatible with CodSpeedHQ
      # https://github.com/astral-sh/uv/issues/11006
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14.2"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Install dependencies
        run: uv sync --all-extras --group benchmark
      - name: Run benchmarks
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: .venv/bin/pytest tests/main/test_performance.py --codspeed
          mode: "walltime"
