name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: uv sync
    - name: build site
      run:  mkdocs build --verbose --clean --strict
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
