name: Update README

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/datamodel_code_generator/**'
      - 'README.md'
      - 'docs/index.md'

permissions:
  contents: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv
      - name: Setup environment
        run: tox run -vv --notest --skip-missing-interpreters false -e readme
        env:
          UV_PYTHON_PREFERENCE: "only-managed"
      - name: Update README
        run: .tox/readme/bin/python scripts/update_command_help_on_markdown.py
