# generated by datamodel-codegen:
#   filename:  test.yml
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from . import common


class Test(Struct):
    uid: Annotated[common.Ulid, Meta(description='ulid of this object')]
