# generated by datamodel-codegen:
#   filename:  shared.py
#   timestamp: 2019-07-26T00:00:00+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class SharedModel:
    id: Optional[int] = None
    name: Optional[str] = None
